[build-system]
requires = [
    "setuptools",
    "wheel",
    "numpy"
]
build-backend = "setuptools.build_meta"

[project]
name = "pygsl"
version = "2.5.2"
dependencies = [
    "numpy",
]

description = "GNU Scientific Library Interface"
# long_description = "This project provides a python interface for the GNU scientific library (gsl)"
# license = "GPL"
authors = [
   {name = "Achim Gaedke", email="AchimGaedke@users.sourceforge.net"},
   {name = "Pierre Schnizer", email="pierre.schnizer@helmholtz-berlin.de"},
   {name = "Charl Linssen" }
]


[project.urls]
homepage = "https://github.com/pygsl/pygsl"
