{"fine_structure",GSL_CONST_NUM_FINE_STRUCTURE,"1"},
{"avogadro",GSL_CONST_NUM_AVOGADRO,"1 / mol"},
{"yotta",GSL_CONST_NUM_YOTTA,"1"},
{"zetta",GSL_CONST_NUM_ZETTA,"1"},
{"exa",GSL_CONST_NUM_EXA,"1"},
{"peta",GSL_CONST_NUM_PETA,"1"},
{"tera",GSL_CONST_NUM_TERA,"1"},
{"giga",GSL_CONST_NUM_GIGA,"1"},
{"mega",GSL_CONST_NUM_MEGA,"1"},
{"kilo",GSL_CONST_NUM_KILO,"1"},
{"milli",GSL_CONST_NUM_MILLI,"1"},
{"micro",GSL_CONST_NUM_MICRO,"1"},
{"nano",GSL_CONST_NUM_NANO,"1"},
{"pico",GSL_CONST_NUM_PICO,"1"},
{"femto",GSL_CONST_NUM_FEMTO,"1"},
{"atto",GSL_CONST_NUM_ATTO,"1"},
{"zepto",GSL_CONST_NUM_ZEPTO,"1"},
{"yocto",GSL_CONST_NUM_YOCTO,"1"},
