{"speed_of_light",GSL_CONST_MKSA_SPEED_OF_LIGHT,"m / s"},
{"gravitational_constant",GSL_CONST_MKSA_GRAVITATIONAL_CONSTANT,"m^3 / kg s^2"},
{"plancks_constant_h",GSL_CONST_MKSA_PLANCKS_CONSTANT_H,"kg m^2 / s"},
{"plancks_constant_hbar",GSL_CONST_MKSA_PLANCKS_CONSTANT_HBAR,"kg m^2 / s"},
{"astronomical_unit",GSL_CONST_MKSA_ASTRONOMICAL_UNIT,"m"},
{"light_year",GSL_CONST_MKSA_LIGHT_YEAR,"m"},
{"parsec",GSL_CONST_MKSA_PARSEC,"m"},
{"grav_accel",GSL_CONST_MKSA_GRAV_ACCEL,"m / s^2"},
{"electron_volt",GSL_CONST_MKSA_ELECTRON_VOLT,"kg m^2 / s^2"},
{"mass_electron",GSL_CONST_MKSA_MASS_ELECTRON,"kg"},
{"mass_muon",GSL_CONST_MKSA_MASS_MUON,"kg"},
{"mass_proton",GSL_CONST_MKSA_MASS_PROTON,"kg"},
{"mass_neutron",GSL_CONST_MKSA_MASS_NEUTRON,"kg"},
{"rydberg",GSL_CONST_MKSA_RYDBERG,"kg m^2 / s^2"},
{"boltzmann",GSL_CONST_MKSA_BOLTZMANN,"kg m^2 / K s^2"},
{"molar_gas",GSL_CONST_MKSA_MOLAR_GAS,"kg m^2 / K mol s^2"},
{"standard_gas_volume",GSL_CONST_MKSA_STANDARD_GAS_VOLUME,"m^3 / mol"},
{"minute",GSL_CONST_MKSA_MINUTE,"s"},
{"hour",GSL_CONST_MKSA_HOUR,"s"},
{"day",GSL_CONST_MKSA_DAY,"s"},
{"week",GSL_CONST_MKSA_WEEK,"s"},
{"inch",GSL_CONST_MKSA_INCH,"m"},
{"foot",GSL_CONST_MKSA_FOOT,"m"},
{"yard",GSL_CONST_MKSA_YARD,"m"},
{"mile",GSL_CONST_MKSA_MILE,"m"},
{"nautical_mile",GSL_CONST_MKSA_NAUTICAL_MILE,"m"},
{"fathom",GSL_CONST_MKSA_FATHOM,"m"},
{"mil",GSL_CONST_MKSA_MIL,"m"},
{"point",GSL_CONST_MKSA_POINT,"m"},
{"texpoint",GSL_CONST_MKSA_TEXPOINT,"m"},
{"micron",GSL_CONST_MKSA_MICRON,"m"},
{"angstrom",GSL_CONST_MKSA_ANGSTROM,"m"},
{"hectare",GSL_CONST_MKSA_HECTARE,"m^2"},
{"acre",GSL_CONST_MKSA_ACRE,"m^2"},
{"barn",GSL_CONST_MKSA_BARN,"m^2"},
{"liter",GSL_CONST_MKSA_LITER,"m^3"},
{"us_gallon",GSL_CONST_MKSA_US_GALLON,"m^3"},
{"quart",GSL_CONST_MKSA_QUART,"m^3"},
{"pint",GSL_CONST_MKSA_PINT,"m^3"},
{"cup",GSL_CONST_MKSA_CUP,"m^3"},
{"fluid_ounce",GSL_CONST_MKSA_FLUID_OUNCE,"m^3"},
{"tablespoon",GSL_CONST_MKSA_TABLESPOON,"m^3"},
{"teaspoon",GSL_CONST_MKSA_TEASPOON,"m^3"},
{"canadian_gallon",GSL_CONST_MKSA_CANADIAN_GALLON,"m^3"},
{"uk_gallon",GSL_CONST_MKSA_UK_GALLON,"m^3"},
{"miles_per_hour",GSL_CONST_MKSA_MILES_PER_HOUR,"m / s"},
{"kilometers_per_hour",GSL_CONST_MKSA_KILOMETERS_PER_HOUR,"m / s"},
{"knot",GSL_CONST_MKSA_KNOT,"m / s"},
{"pound_mass",GSL_CONST_MKSA_POUND_MASS,"kg"},
{"ounce_mass",GSL_CONST_MKSA_OUNCE_MASS,"kg"},
{"ton",GSL_CONST_MKSA_TON,"kg"},
{"metric_ton",GSL_CONST_MKSA_METRIC_TON,"kg"},
{"uk_ton",GSL_CONST_MKSA_UK_TON,"kg"},
{"troy_ounce",GSL_CONST_MKSA_TROY_OUNCE,"kg"},
{"carat",GSL_CONST_MKSA_CARAT,"kg"},
{"unified_atomic_mass",GSL_CONST_MKSA_UNIFIED_ATOMIC_MASS,"kg"},
{"gram_force",GSL_CONST_MKSA_GRAM_FORCE,"kg m / s^2"},
{"pound_force",GSL_CONST_MKSA_POUND_FORCE,"kg m / s^2"},
{"kilopound_force",GSL_CONST_MKSA_KILOPOUND_FORCE,"kg m / s^2"},
{"poundal",GSL_CONST_MKSA_POUNDAL,"kg m / s^2"},
{"calorie",GSL_CONST_MKSA_CALORIE,"kg m^2 / s^2"},
{"btu",GSL_CONST_MKSA_BTU,"kg m^2 / s^2"},
{"therm",GSL_CONST_MKSA_THERM,"kg m^2 / s^2"},
{"horsepower",GSL_CONST_MKSA_HORSEPOWER,"kg m^2 / s^3"},
{"bar",GSL_CONST_MKSA_BAR,"kg / m s^2"},
{"std_atmosphere",GSL_CONST_MKSA_STD_ATMOSPHERE,"kg / m s^2"},
{"torr",GSL_CONST_MKSA_TORR,"kg / m s^2"},
{"meter_of_mercury",GSL_CONST_MKSA_METER_OF_MERCURY,"kg / m s^2"},
{"inch_of_mercury",GSL_CONST_MKSA_INCH_OF_MERCURY,"kg / m s^2"},
{"inch_of_water",GSL_CONST_MKSA_INCH_OF_WATER,"kg / m s^2"},
{"psi",GSL_CONST_MKSA_PSI,"kg / m s^2"},
{"poise",GSL_CONST_MKSA_POISE,"kg m^-1 s^-1"},
{"stokes",GSL_CONST_MKSA_STOKES,"m^2 / s"},
{"stilb",GSL_CONST_MKSA_STILB,"cd / m^2"},
{"lumen",GSL_CONST_MKSA_LUMEN,"cd sr"},
{"lux",GSL_CONST_MKSA_LUX,"cd sr / m^2"},
{"phot",GSL_CONST_MKSA_PHOT,"cd sr / m^2"},
{"footcandle",GSL_CONST_MKSA_FOOTCANDLE,"cd sr / m^2"},
{"lambert",GSL_CONST_MKSA_LAMBERT,"cd sr / m^2"},
{"footlambert",GSL_CONST_MKSA_FOOTLAMBERT,"cd sr / m^2"},
{"curie",GSL_CONST_MKSA_CURIE,"1 / s"},
{"roentgen",GSL_CONST_MKSA_ROENTGEN,"A s / kg"},
{"rad",GSL_CONST_MKSA_RAD,"m^2 / s^2"},
{"solar_mass",GSL_CONST_MKSA_SOLAR_MASS,"kg"},
{"bohr_radius",GSL_CONST_MKSA_BOHR_RADIUS,"m"},
{"newton",GSL_CONST_MKSA_NEWTON,"kg m / s^2"},
{"dyne",GSL_CONST_MKSA_DYNE,"kg m / s^2"},
{"joule",GSL_CONST_MKSA_JOULE,"kg m^2 / s^2"},
{"erg",GSL_CONST_MKSA_ERG,"kg m^2 / s^2"},
{"stefan_boltzmann_constant",GSL_CONST_MKSA_STEFAN_BOLTZMANN_CONSTANT,"kg / K^4 s^3"},
{"thomson_cross_section",GSL_CONST_MKSA_THOMSON_CROSS_SECTION,"m^2"},
{"bohr_magneton",GSL_CONST_MKSA_BOHR_MAGNETON,"A m^2"},
{"nuclear_magneton",GSL_CONST_MKSA_NUCLEAR_MAGNETON,"A m^2"},
{"electron_magnetic_moment",GSL_CONST_MKSA_ELECTRON_MAGNETIC_MOMENT,"A m^2"},
{"proton_magnetic_moment",GSL_CONST_MKSA_PROTON_MAGNETIC_MOMENT,"A m^2"},
{"faraday",GSL_CONST_MKSA_FARADAY,"A s / mol"},
{"electron_charge",GSL_CONST_MKSA_ELECTRON_CHARGE,"A s"},
{"vacuum_permittivity",GSL_CONST_MKSA_VACUUM_PERMITTIVITY,"A^2 s^4 / kg m^3"},
{"vacuum_permeability",GSL_CONST_MKSA_VACUUM_PERMEABILITY,"kg m / A^2 s^2"},
{"debye",GSL_CONST_MKSA_DEBYE,"A s^2 / m^2"},
{"gauss",GSL_CONST_MKSA_GAUSS,"kg / A s^2"},
