{"speed_of_light",GSL_CONST_CGS_SPEED_OF_LIGHT,"cm / s"},
{"gravitational_constant",GSL_CONST_CGS_GRAVITATIONAL_CONSTANT,"cm^3 / g s^2"},
{"plancks_constant_h",GSL_CONST_CGS_PLANCKS_CONSTANT_H,"g cm^2 / s"},
{"plancks_constant_hbar",GSL_CONST_CGS_PLANCKS_CONSTANT_HBAR,"g cm^2 / s"},
{"astronomical_unit",GSL_CONST_CGS_ASTRONOMICAL_UNIT,"cm"},
{"light_year",GSL_CONST_CGS_LIGHT_YEAR,"cm"},
{"parsec",GSL_CONST_CGS_PARSEC,"cm"},
{"grav_accel",GSL_CONST_CGS_GRAV_ACCEL,"cm / s^2"},
{"electron_volt",GSL_CONST_CGS_ELECTRON_VOLT,"g cm^2 / s^2"},
{"mass_electron",GSL_CONST_CGS_MASS_ELECTRON,"g"},
{"mass_muon",GSL_CONST_CGS_MASS_MUON,"g"},
{"mass_proton",GSL_CONST_CGS_MASS_PROTON,"g"},
{"mass_neutron",GSL_CONST_CGS_MASS_NEUTRON,"g"},
{"rydberg",GSL_CONST_CGS_RYDBERG,"g cm^2 / s^2"},
{"boltzmann",GSL_CONST_CGS_BOLTZMANN,"g cm^2 / K s^2"},
{"molar_gas",GSL_CONST_CGS_MOLAR_GAS,"g cm^2 / K mol s^2"},
{"standard_gas_volume",GSL_CONST_CGS_STANDARD_GAS_VOLUME,"cm^3 / mol"},
{"minute",GSL_CONST_CGS_MINUTE,"s"},
{"hour",GSL_CONST_CGS_HOUR,"s"},
{"day",GSL_CONST_CGS_DAY,"s"},
{"week",GSL_CONST_CGS_WEEK,"s"},
{"inch",GSL_CONST_CGS_INCH,"cm"},
{"foot",GSL_CONST_CGS_FOOT,"cm"},
{"yard",GSL_CONST_CGS_YARD,"cm"},
{"mile",GSL_CONST_CGS_MILE,"cm"},
{"nautical_mile",GSL_CONST_CGS_NAUTICAL_MILE,"cm"},
{"fathom",GSL_CONST_CGS_FATHOM,"cm"},
{"mil",GSL_CONST_CGS_MIL,"cm"},
{"point",GSL_CONST_CGS_POINT,"cm"},
{"texpoint",GSL_CONST_CGS_TEXPOINT,"cm"},
{"micron",GSL_CONST_CGS_MICRON,"cm"},
{"angstrom",GSL_CONST_CGS_ANGSTROM,"cm"},
{"hectare",GSL_CONST_CGS_HECTARE,"cm^2"},
{"acre",GSL_CONST_CGS_ACRE,"cm^2"},
{"barn",GSL_CONST_CGS_BARN,"cm^2"},
{"liter",GSL_CONST_CGS_LITER,"cm^3"},
{"us_gallon",GSL_CONST_CGS_US_GALLON,"cm^3"},
{"quart",GSL_CONST_CGS_QUART,"cm^3"},
{"pint",GSL_CONST_CGS_PINT,"cm^3"},
{"cup",GSL_CONST_CGS_CUP,"cm^3"},
{"fluid_ounce",GSL_CONST_CGS_FLUID_OUNCE,"cm^3"},
{"tablespoon",GSL_CONST_CGS_TABLESPOON,"cm^3"},
{"teaspoon",GSL_CONST_CGS_TEASPOON,"cm^3"},
{"canadian_gallon",GSL_CONST_CGS_CANADIAN_GALLON,"cm^3"},
{"uk_gallon",GSL_CONST_CGS_UK_GALLON,"cm^3"},
{"miles_per_hour",GSL_CONST_CGS_MILES_PER_HOUR,"cm / s"},
{"kilometers_per_hour",GSL_CONST_CGS_KILOMETERS_PER_HOUR,"cm / s"},
{"knot",GSL_CONST_CGS_KNOT,"cm / s"},
{"pound_mass",GSL_CONST_CGS_POUND_MASS,"g"},
{"ounce_mass",GSL_CONST_CGS_OUNCE_MASS,"g"},
{"ton",GSL_CONST_CGS_TON,"g"},
{"metric_ton",GSL_CONST_CGS_METRIC_TON,"g"},
{"uk_ton",GSL_CONST_CGS_UK_TON,"g"},
{"troy_ounce",GSL_CONST_CGS_TROY_OUNCE,"g"},
{"carat",GSL_CONST_CGS_CARAT,"g"},
{"unified_atomic_mass",GSL_CONST_CGS_UNIFIED_ATOMIC_MASS,"g"},
{"gram_force",GSL_CONST_CGS_GRAM_FORCE,"cm g / s^2"},
{"pound_force",GSL_CONST_CGS_POUND_FORCE,"cm g / s^2"},
{"kilopound_force",GSL_CONST_CGS_KILOPOUND_FORCE,"cm g / s^2"},
{"poundal",GSL_CONST_CGS_POUNDAL,"cm g / s^2"},
{"calorie",GSL_CONST_CGS_CALORIE,"g cm^2 / s^2"},
{"btu",GSL_CONST_CGS_BTU,"g cm^2 / s^2"},
{"therm",GSL_CONST_CGS_THERM,"g cm^2 / s^2"},
{"horsepower",GSL_CONST_CGS_HORSEPOWER,"g cm^2 / s^3"},
{"bar",GSL_CONST_CGS_BAR,"g / cm s^2"},
{"std_atmosphere",GSL_CONST_CGS_STD_ATMOSPHERE,"g / cm s^2"},
{"torr",GSL_CONST_CGS_TORR,"g / cm s^2"},
{"meter_of_mercury",GSL_CONST_CGS_METER_OF_MERCURY,"g / cm s^2"},
{"inch_of_mercury",GSL_CONST_CGS_INCH_OF_MERCURY,"g / cm s^2"},
{"inch_of_water",GSL_CONST_CGS_INCH_OF_WATER,"g / cm s^2"},
{"psi",GSL_CONST_CGS_PSI,"g / cm s^2"},
{"poise",GSL_CONST_CGS_POISE,"g / cm s"},
{"stokes",GSL_CONST_CGS_STOKES,"cm^2 / s"},
{"stilb",GSL_CONST_CGS_STILB,"cd / cm^2"},
{"lumen",GSL_CONST_CGS_LUMEN,"cd sr"},
{"lux",GSL_CONST_CGS_LUX,"cd sr / cm^2"},
{"phot",GSL_CONST_CGS_PHOT,"cd sr / cm^2"},
{"footcandle",GSL_CONST_CGS_FOOTCANDLE,"cd sr / cm^2"},
{"lambert",GSL_CONST_CGS_LAMBERT,"cd sr / cm^2"},
{"footlambert",GSL_CONST_CGS_FOOTLAMBERT,"cd sr / cm^2"},
{"curie",GSL_CONST_CGS_CURIE,"1 / s"},
{"roentgen",GSL_CONST_CGS_ROENTGEN,"A s / g"},
{"rad",GSL_CONST_CGS_RAD,"cm^2 / s^2"},
{"solar_mass",GSL_CONST_CGS_SOLAR_MASS,"g"},
{"bohr_radius",GSL_CONST_CGS_BOHR_RADIUS,"cm"},
{"newton",GSL_CONST_CGS_NEWTON,"cm g / s^2"},
{"dyne",GSL_CONST_CGS_DYNE,"cm g / s^2"},
{"joule",GSL_CONST_CGS_JOULE,"g cm^2 / s^2"},
{"erg",GSL_CONST_CGS_ERG,"g cm^2 / s^2"},
{"stefan_boltzmann_constant",GSL_CONST_CGS_STEFAN_BOLTZMANN_CONSTANT,"g / K^4 s^3"},
{"thomson_cross_section",GSL_CONST_CGS_THOMSON_CROSS_SECTION,"cm^2"},
