/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.17u-20030109-1609
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

#define SWIGPYTHON

#include "Python.h"

/***********************************************************************
 * common.swg
 *
 *     This file contains generic SWIG runtime support for pointer
 *     type checking as well as a few commonly used macros to control
 *     external linkage.
 *
 * Author : David Beazley (beazley@cs.uchicago.edu)
 *
 * Copyright (c) 1999-2000, The University of Chicago
 * 
 * This file may be freely redistributed without license or fee provided
 * this copyright message remains intact.
 ************************************************************************/

#include <string.h>

#if defined(_WIN32) || defined(__WIN32__)
#       if defined(_MSC_VER)
#               if defined(STATIC_LINKED)
#                       define SWIGEXPORT(a) a
#                       define SWIGIMPORT(a) extern a
#               else
#                       define SWIGEXPORT(a) __declspec(dllexport) a
#                       define SWIGIMPORT(a) extern a
#               endif
#       else
#               if defined(__BORLANDC__)
#                       define SWIGEXPORT(a) a _export
#                       define SWIGIMPORT(a) a _export
#               else
#                       define SWIGEXPORT(a) a
#                       define SWIGIMPORT(a) a
#               endif
#       endif
#else
#       define SWIGEXPORT(a) a
#       define SWIGIMPORT(a) a
#endif

#ifdef SWIG_GLOBAL
#define SWIGRUNTIME(a) SWIGEXPORT(a)
#else
#define SWIGRUNTIME(a) static a
#endif

#ifdef __cplusplus
extern "C" {
#endif

typedef void *(*swig_converter_func)(void *);
typedef struct swig_type_info *(*swig_dycast_func)(void **);

typedef struct swig_type_info {
  const char             *name;                 
  swig_converter_func     converter;
  const char             *str;
  void                   *clientdata;	
  swig_dycast_func        dcast;
  struct swig_type_info  *next;
  struct swig_type_info  *prev;
} swig_type_info;

#ifdef SWIG_NOINCLUDE

SWIGIMPORT(swig_type_info *) SWIG_TypeRegister(swig_type_info *);
SWIGIMPORT(swig_type_info *) SWIG_TypeCheck(char *c, swig_type_info *);
SWIGIMPORT(void *)           SWIG_TypeCast(swig_type_info *, void *);
SWIGIMPORT(swig_type_info *) SWIG_TypeDynamicCast(swig_type_info *, void **);
SWIGIMPORT(swig_type_info *) SWIG_TypeQuery(const char *);
SWIGIMPORT(void)             SWIG_TypeClientData(swig_type_info *, void *);

#else

static swig_type_info *swig_type_list = 0;

/* Register a type mapping with the type-checking */
SWIGRUNTIME(swig_type_info *)
SWIG_TypeRegister(swig_type_info *ti)
{
  swig_type_info *tc, *head, *ret, *next;
  /* Check to see if this type has already been registered */
  tc = swig_type_list;
  while (tc) {
    if (strcmp(tc->name, ti->name) == 0) {
      /* Already exists in the table.  Just add additional types to the list */
      if (tc->clientdata) ti->clientdata = tc->clientdata;	
      head = tc;
      next = tc->next;
      goto l1;
    }
    tc = tc->prev;
  }
  head = ti;
  next = 0;

  /* Place in list */
  ti->prev = swig_type_list;
  swig_type_list = ti;

  /* Build linked lists */
 l1:
  ret = head;
  tc = ti + 1;
  /* Patch up the rest of the links */
  while (tc->name) {
    head->next = tc;
    tc->prev = head;
    head = tc;
    tc++;
  }
  head->next = next;
  return ret;
}

/* Check the typename */
SWIGRUNTIME(swig_type_info *) 
SWIG_TypeCheck(char *c, swig_type_info *ty)
{
  swig_type_info *s;
  if (!ty) return 0;        /* Void pointer */
  s = ty->next;             /* First element always just a name */
  do {
    if (strcmp(s->name,c) == 0) {
      if (s == ty->next) return s;
      /* Move s to the top of the linked list */
      s->prev->next = s->next;
      if (s->next) {
	s->next->prev = s->prev;
      }
      /* Insert s as second element in the list */
      s->next = ty->next;
      if (ty->next) ty->next->prev = s;
      ty->next = s;
      return s;
    }
    s = s->next;
  } while (s && (s != ty->next));
  return 0;
}

/* Cast a pointer up an inheritance hierarchy */
SWIGRUNTIME(void *) 
SWIG_TypeCast(swig_type_info *ty, void *ptr) 
{
  if ((!ty) || (!ty->converter)) return ptr;
  return (*ty->converter)(ptr);
}

/* Dynamic pointer casting. Down an inheritance hierarchy */
SWIGRUNTIME(swig_type_info *) 
SWIG_TypeDynamicCast(swig_type_info *ty, void **ptr) 
{
  swig_type_info *lastty = ty;
  if (!ty || !ty->dcast) return ty;
  while (ty && (ty->dcast)) {
     ty = (*ty->dcast)(ptr);
     if (ty) lastty = ty;
  }
  return lastty;
}

/* Search for a swig_type_info structure */
SWIGRUNTIME(swig_type_info *)
SWIG_TypeQuery(const char *name) {
  swig_type_info *ty = swig_type_list;
  while (ty) {
    if (ty->str && (strcmp(name,ty->str) == 0)) return ty;
    if (ty->name && (strcmp(name,ty->name) == 0)) return ty;
    ty = ty->prev;
  }
  return 0;
}

/* Set the clientdata field for a type */
SWIGRUNTIME(void)
SWIG_TypeClientData(swig_type_info *ti, void *clientdata) {
  swig_type_info *tc, *equiv;
  if (ti->clientdata == clientdata) return;
  ti->clientdata = clientdata;
  equiv = ti->next;
  while (equiv) {
    if (!equiv->converter) {
      tc = swig_type_list;
      while (tc) {
	if ((strcmp(tc->name, equiv->name) == 0))
	  SWIG_TypeClientData(tc,clientdata);
	tc = tc->prev;
      }
    }
    equiv = equiv->next;
  }
}
#endif

#ifdef __cplusplus
}

#endif

/***********************************************************************
 * python.swg
 *
 *     This file contains the runtime support for Python modules
 *     and includes code for managing global variables and pointer
 *     type checking.
 *
 * Author : David Beazley (beazley@cs.uchicago.edu)
 ************************************************************************/

#include "Python.h"

#ifdef __cplusplus
extern "C" {
#endif

#define SWIG_PY_INT     1
#define SWIG_PY_FLOAT   2
#define SWIG_PY_STRING  3
#define SWIG_PY_POINTER 4
#define SWIG_PY_BINARY  5

/* Flags for pointer conversion */

#define SWIG_POINTER_EXCEPTION     0x1
#define SWIG_POINTER_DISOWN        0x2

/* Exception handling in wrappers */
#define SWIG_fail   goto fail

/* Constant information structure */
typedef struct swig_const_info {
    int type;
    char *name;
    long lvalue;
    double dvalue;
    void   *pvalue;
    swig_type_info **ptype;
} swig_const_info;

#ifdef SWIG_NOINCLUDE

SWIGEXPORT(PyObject *)        SWIG_newvarlink();
SWIGEXPORT(void)              SWIG_addvarlink(PyObject *, char *, PyObject *(*)(void), int (*)(PyObject *));
SWIGEXPORT(int)               SWIG_ConvertPtr(PyObject *, void **, swig_type_info *, int);
SWIGEXPORT(int)               SWIG_ConvertPacked(PyObject *, void *, int sz, swig_type_info *, int);
SWIGEXPORT(char *)            SWIG_PackData(char *c, void *, int);
SWIGEXPORT(char *)            SWIG_UnpackData(char *c, void *, int);
SWIGEXPORT(PyObject *)        SWIG_NewPointerObj(void *, swig_type_info *,int own);
SWIGEXPORT(PyObject *)        SWIG_NewPackedObj(void *, int sz, swig_type_info *);
SWIGEXPORT(void)              SWIG_InstallConstants(PyObject *d, swig_const_info constants[]);
#else

/* -----------------------------------------------------------------------------
 * global variable support code.
 * ----------------------------------------------------------------------------- */

typedef struct swig_globalvar {   
  char       *name;                  /* Name of global variable */
  PyObject *(*get_attr)(void);       /* Return the current value */
  int       (*set_attr)(PyObject *); /* Set the value */
  struct swig_globalvar *next;
} swig_globalvar;

typedef struct swig_varlinkobject {
  PyObject_HEAD
  swig_globalvar *vars;
} swig_varlinkobject;

static PyObject *
swig_varlink_repr(swig_varlinkobject *v) {
  v = v;
  return PyString_FromString("<Global variables>");
}

static int
swig_varlink_print(swig_varlinkobject *v, FILE *fp, int flags) {
  swig_globalvar  *var;
  flags = flags;
  fprintf(fp,"Global variables { ");
  for (var = v->vars; var; var=var->next) {
    fprintf(fp,"%s", var->name);
    if (var->next) fprintf(fp,", ");
  }
  fprintf(fp," }\n");
  return 0;
}

static PyObject *
swig_varlink_getattr(swig_varlinkobject *v, char *n) {
  swig_globalvar *var = v->vars;
  while (var) {
    if (strcmp(var->name,n) == 0) {
      return (*var->get_attr)();
    }
    var = var->next;
  }
  PyErr_SetString(PyExc_NameError,"Unknown C global variable");
  return NULL;
}

static int
swig_varlink_setattr(swig_varlinkobject *v, char *n, PyObject *p) {
  swig_globalvar *var = v->vars;
  while (var) {
    if (strcmp(var->name,n) == 0) {
      return (*var->set_attr)(p);
    }
    var = var->next;
  }
  PyErr_SetString(PyExc_NameError,"Unknown C global variable");
  return 1;
}

statichere PyTypeObject varlinktype = {
  PyObject_HEAD_INIT(0)              
  0,
  (char *)"swigvarlink",                      /* Type name    */
  sizeof(swig_varlinkobject),         /* Basic size   */
  0,                                  /* Itemsize     */
  0,                                  /* Deallocator  */ 
  (printfunc) swig_varlink_print,     /* Print        */
  (getattrfunc) swig_varlink_getattr, /* get attr     */
  (setattrfunc) swig_varlink_setattr, /* Set attr     */
  0,                                  /* tp_compare   */
  (reprfunc) swig_varlink_repr,       /* tp_repr      */    
  0,                                  /* tp_as_number */
  0,                                  /* tp_as_mapping*/
  0,                                  /* tp_hash      */
};

/* Create a variable linking object for use later */
SWIGRUNTIME(PyObject *)
SWIG_newvarlink(void) {
  swig_varlinkobject *result = 0;
  result = PyMem_NEW(swig_varlinkobject,1);
  varlinktype.ob_type = &PyType_Type;    /* Patch varlinktype into a PyType */
  result->ob_type = &varlinktype;
  result->vars = 0;
  result->ob_refcnt = 0;
  Py_XINCREF((PyObject *) result);
  return ((PyObject*) result);
}

SWIGRUNTIME(void)
SWIG_addvarlink(PyObject *p, char *name,
	   PyObject *(*get_attr)(void), int (*set_attr)(PyObject *p)) {
  swig_varlinkobject *v;
  swig_globalvar *gv;
  v= (swig_varlinkobject *) p;
  gv = (swig_globalvar *) malloc(sizeof(swig_globalvar));
  gv->name = (char *) malloc(strlen(name)+1);
  strcpy(gv->name,name);
  gv->get_attr = get_attr;
  gv->set_attr = set_attr;
  gv->next = v->vars;
  v->vars = gv;
}

/* Pack binary data into a string */
SWIGRUNTIME(char *)
SWIG_PackData(char *c, void *ptr, int sz) {
  static char hex[17] = "0123456789abcdef";
  int i;
  unsigned char *u = (unsigned char *) ptr;
  register unsigned char uu;
  for (i = 0; i < sz; i++,u++) {
    uu = *u;
    *(c++) = hex[(uu & 0xf0) >> 4];
    *(c++) = hex[uu & 0xf];
  }
  return c;
}

/* Unpack binary data from a string */
SWIGRUNTIME(char *)
SWIG_UnpackData(char *c, void *ptr, int sz) {
  register unsigned char uu = 0;
  register int d;
  unsigned char *u = (unsigned char *) ptr;
  int i;
  for (i = 0; i < sz; i++, u++) {
    d = *(c++);
    if ((d >= '0') && (d <= '9'))
      uu = ((d - '0') << 4);
    else if ((d >= 'a') && (d <= 'f'))
      uu = ((d - ('a'-10)) << 4);
    d = *(c++);
    if ((d >= '0') && (d <= '9'))
      uu |= (d - '0');
    else if ((d >= 'a') && (d <= 'f'))
      uu |= (d - ('a'-10));
    *u = uu;
  }
  return c;
}

/* Convert a pointer value */
SWIGRUNTIME(int)
SWIG_ConvertPtr(PyObject *obj, void **ptr, swig_type_info *ty, int flags) {
  swig_type_info *tc;
  char  *c;
  static PyObject *SWIG_this = 0;
  int    newref = 0;
  PyObject  *pyobj = 0;

  if (!obj) return 0;
  if (obj == Py_None) {
    *ptr = 0;
    return 0;
  }
#ifdef SWIG_COBJECT_TYPES
  if (!(PyCObject_Check(obj))) {
    if (!SWIG_this)
      SWIG_this = PyString_FromString("this");
    pyobj = obj;
    obj = PyObject_GetAttr(obj,SWIG_this);
    newref = 1;
    if (!obj) goto type_error;
    if (!PyCObject_Check(obj)) {
      Py_DECREF(obj);
      goto type_error;
    }
  }  
  *ptr = PyCObject_AsVoidPtr(obj);
  c = (char *) PyCObject_GetDesc(obj);
  if (newref) Py_DECREF(obj);
  goto cobject;
#else
  if (!(PyString_Check(obj))) {
    if (!SWIG_this)
      SWIG_this = PyString_FromString("this");
    pyobj = obj;
    obj = PyObject_GetAttr(obj,SWIG_this);
    newref = 1;
    if (!obj) goto type_error;
    if (!PyString_Check(obj)) {
      Py_DECREF(obj);
      goto type_error;
    }
  } 
  c = PyString_AsString(obj);
  /* Pointer values must start with leading underscore */
  if (*c != '_') {
    *ptr = (void *) 0;
    if (strcmp(c,"NULL") == 0) {
      if (newref) { Py_DECREF(obj); }
      return 0;
    } else {
      if (newref) { Py_DECREF(obj); }
      goto type_error;
    }
  }
  c++;
  c = SWIG_UnpackData(c,ptr,sizeof(void *));
  if (newref) { Py_DECREF(obj); }
#endif

#ifdef SWIG_COBJECT_TYPES
cobject:
#endif

  if (ty) {
    tc = SWIG_TypeCheck(c,ty);
    if (!tc) goto type_error;
    *ptr = SWIG_TypeCast(tc,(void*) *ptr);
  }

  if ((pyobj) && (flags & SWIG_POINTER_DISOWN)) {
      PyObject *zero = PyInt_FromLong(0);
      PyObject_SetAttrString(pyobj,(char*)"thisown",zero);
      Py_DECREF(zero);
  }
  return 0;

type_error:
  if (flags & SWIG_POINTER_EXCEPTION) {
    if (ty) {
      char *temp = (char *) malloc(64+strlen(ty->name));
      sprintf(temp,"Type error. Expected %s", ty->name);
      PyErr_SetString(PyExc_TypeError, temp);
      free((char *) temp);
    } else {
      PyErr_SetString(PyExc_TypeError,"Expected a pointer");
    }
  }
  return -1;
}

/* Convert a packed value value */
SWIGRUNTIME(int)
SWIG_ConvertPacked(PyObject *obj, void *ptr, int sz, swig_type_info *ty, int flags) {
  swig_type_info *tc;
  char  *c;

  if ((!obj) || (!PyString_Check(obj))) goto type_error;
  c = PyString_AsString(obj);
  /* Pointer values must start with leading underscore */
  if (*c != '_') goto type_error;
  c++;
  c = SWIG_UnpackData(c,ptr,sz);
  if (ty) {
    tc = SWIG_TypeCheck(c,ty);
    if (!tc) goto type_error;
  }
  return 0;

type_error:

  if (flags) {
    if (ty) {
      char *temp = (char *) malloc(64+strlen(ty->name));
      sprintf(temp,"Type error. Expected %s", ty->name);
      PyErr_SetString(PyExc_TypeError, temp);
      free((char *) temp);
    } else {
      PyErr_SetString(PyExc_TypeError,"Expected a pointer");
    }
  }
  return -1;
}

/* Create a new pointer object */
SWIGRUNTIME(PyObject *)
SWIG_NewPointerObj(void *ptr, swig_type_info *type, int own) {
  PyObject *robj;
  if (!ptr) {
    Py_INCREF(Py_None);
    return Py_None;
  }
#ifdef SWIG_COBJECT_TYPES
  robj = PyCObject_FromVoidPtrAndDesc((void *) ptr, (char *) type->name, NULL);
#else
  {
    char result[1024];
    char *r = result;
    *(r++) = '_';
    r = SWIG_PackData(r,&ptr,sizeof(void *));
    strcpy(r,type->name);
    robj = PyString_FromString(result);
  }
#endif
  if (!robj || (robj == Py_None)) return robj;
  if (type->clientdata) {
    PyObject *inst;
    PyObject *args = Py_BuildValue((char*)"(O)", robj);
    Py_DECREF(robj);
    inst = PyObject_CallObject((PyObject *) type->clientdata, args);
    Py_DECREF(args);
    if (inst) {
      if (own) {
	PyObject *n = PyInt_FromLong(1);
	PyObject_SetAttrString(inst,(char*)"thisown",n);
	Py_DECREF(n);
      }
      robj = inst;
    }
  }
  return robj;
}

SWIGRUNTIME(PyObject *)
SWIG_NewPackedObj(void *ptr, int sz, swig_type_info *type) {
  char result[1024];
  char *r = result;
  if ((2*sz + 1 + strlen(type->name)) > 1000) return 0;
  *(r++) = '_';
  r = SWIG_PackData(r,ptr,sz);
  strcpy(r,type->name);
  return PyString_FromString(result);
}

/* Install Constants */
SWIGRUNTIME(void)
SWIG_InstallConstants(PyObject *d, swig_const_info constants[]) {
  int i;
  PyObject *obj;
  for (i = 0; constants[i].type; i++) {
    switch(constants[i].type) {
    case SWIG_PY_INT:
      obj = PyInt_FromLong(constants[i].lvalue);
      break;
    case SWIG_PY_FLOAT:
      obj = PyFloat_FromDouble(constants[i].dvalue);
      break;
    case SWIG_PY_STRING:
      obj = PyString_FromString((char *) constants[i].pvalue);
      break;
    case SWIG_PY_POINTER:
      obj = SWIG_NewPointerObj(constants[i].pvalue, *(constants[i]).ptype,0);
      break;
    case SWIG_PY_BINARY:
      obj = SWIG_NewPackedObj(constants[i].pvalue, constants[i].lvalue, *(constants[i].ptype));
      break;
    default:
      obj = 0;
      break;
    }
    if (obj) {
      PyDict_SetItemString(d,constants[i].name,obj);
      Py_DECREF(obj);
    }
  }
}

#endif

#ifdef __cplusplus
}
#endif








/* -------- TYPES TABLE (BEGIN) -------- */

#define  SWIGTYPE_p_gsl_interp swig_types[0] 
#define  SWIGTYPE_p_gsl_spline swig_types[1] 
#define  SWIGTYPE_p_double swig_types[2] 
#define  SWIGTYPE_p_gsl_interp_type swig_types[3] 
#define  SWIGTYPE_p_gsl_interp_accel swig_types[4] 
static swig_type_info *swig_types[6];

/* -------- TYPES TABLE (END) -------- */


/*-----------------------------------------------
              @(target):= _gslwrap.so
  ------------------------------------------------*/
#define SWIG_init    init_gslwrap

#define SWIG_name    "_gslwrap"

#include <gsl/gsl_types.h>
#include <Numeric/arrayobject.h>
#include <stdio.h>

   
#include <utils/util.h>  
typedef int gsl_error_flag;


#include <gsl/gsl_vector.h>
#include <gsl/gsl_matrix.h>
#include <Numeric/arrayobject.h>
#include <typemaps/gsl_block_helpers.ic>
#include <typemaps/convert_block_description.h>
#include <utils/util.h>
#include <string.h>
#include <assert.h>


#include <gsl/gsl_errno.h>
#include <utils/util.h>
#include <typemaps/gsl_complex_helpers.ic>



#include <gsl/gsl_interp.h>
#include <gsl/gsl_spline.h>
#include <Numeric/arrayobject.h>
#include <stdio.h>

extern gsl_interp_type const *gsl_interp_linear;
extern gsl_interp_type const *gsl_interp_polynomial;
extern gsl_interp_type const *gsl_interp_cspline;
extern gsl_interp_type const *gsl_interp_cspline_periodic;
extern gsl_interp_type const *gsl_interp_akima;
extern gsl_interp_type const *gsl_interp_akima_periodic;

static PyObject* t_output_helper(PyObject* target, PyObject* o) {
    PyObject*   o2;
    PyObject*   o3;

    if (!target) {                   
        target = o;
    } else if (target == Py_None) {  
        Py_DECREF(Py_None);
        target = o;
    } else {                         
        if (!PyTuple_Check(target)) {
            o2 = target;
            target = PyTuple_New(1);
            PyTuple_SetItem(target, 0, o2);
        }
        o3 = PyTuple_New(1);            
        PyTuple_SetItem(o3, 0, o);      

        o2 = target;
        target = PySequence_Concat(o2, o3); 
        Py_DECREF(o2);                      
        Py_DECREF(o3);
    }
    return target;
}

#ifdef __cplusplus
extern "C" {
#endif
static PyObject *_wrap_gsl_spline_alloc(PyObject *self, PyObject *args, PyObject *kwargs) {
    PyObject *resultobj;
    gsl_interp_type *arg1 = (gsl_interp_type *) 0 ;
    size_t arg2 ;
    gsl_spline *result;
    PyObject * obj0  = 0 ;
    PyObject * obj1  = 0 ;
    char *kwnames[] = {
        "T","n", NULL 
    };
    
    if(!PyArg_ParseTupleAndKeywords(args,kwargs,(char *)"OO:gsl_spline_alloc",kwnames,&obj0,&obj1)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_gsl_interp_type,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    arg2 = (size_t) PyInt_AsLong(obj1);
    if (PyErr_Occurred()) SWIG_fail;
    result = (gsl_spline *)gsl_spline_alloc((gsl_interp_type const *)arg1,arg2);
    
    resultobj = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_gsl_spline, 0);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_gsl_spline_init(PyObject *self, PyObject *args, PyObject *kwargs) {
    PyObject *resultobj;
    gsl_spline *arg1 = (gsl_spline *) 0 ;
    double *arg2 ;
    double *arg3 ;
    size_t arg4 ;
    int result;
    PyObject * obj0  = 0 ;
    PyObject * obj1  = 0 ;
    char *kwnames[] = {
        "spline","xa", NULL 
    };
    
    
    PyArrayObject *_PyVector_12 = NULL;
    PyArrayObject *_PyVector_22 = NULL;
    
    if(!PyArg_ParseTupleAndKeywords(args,kwargs,(char *)"OO:gsl_spline_init",kwnames,&obj0,&obj1)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_gsl_spline,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    {
        int mysize = 0;
        _PyVector_12 = PyGSL_PyArray_PREPARE_gsl_vector_view(
        obj1, PyArray_DOUBLE, 1, -1, 2, NULL);
        if (_PyVector_12 == NULL)
        goto fail;
        
        mysize = _PyVector_12->dimensions[0];
        
        _PyVector_22 = PyGSL_PyArray_PREPARE_gsl_vector_view(
        obj1, PyArray_DOUBLE, 1, mysize, 2+1, NULL);
        if (_PyVector_22 == NULL)
        goto fail;
        
        arg2 = (double *)(_PyVector_12->data);
        arg3 = (size_t n)mysize;
        arg4 = (double *)(_PyVector_22->data);
    }
    {
        _PyVector2 = PyGSL_PyArray_PREPARE_gsl_vector_view(
        $input, PyArray_DOUBLE, 1, _gslinterp_size, 2, NULL);
        if (_PyVector2 == NULL)
        goto fail;
        arg2 = (double *)(_PyVector2->data);
    }
    {
        _PyVector3 = PyGSL_PyArray_PREPARE_gsl_vector_view(
        $input, PyArray_DOUBLE, 1, _gslinterp_size, 3, NULL);
        if (_PyVector3 == NULL)
        goto fail;
        arg3 = (double *)(_PyVector3->data);
    }
    result = (int)gsl_spline_init(arg1,(double const (*))arg2,(double const (*))arg3,arg4);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_gsl_spline_eval_e(PyObject *self, PyObject *args, PyObject *kwargs) {
    PyObject *resultobj;
    gsl_spline *arg1 = (gsl_spline *) 0 ;
    double arg2 ;
    gsl_interp_accel *arg3 = (gsl_interp_accel *) 0 ;
    double *arg4 = (double *) 0 ;
    int result;
    PyObject * obj0  = 0 ;
    PyObject * obj2  = 0 ;
    PyObject * obj3  = 0 ;
    char *kwnames[] = {
        "spline","x","a","y", NULL 
    };
    
    if(!PyArg_ParseTupleAndKeywords(args,kwargs,(char *)"OdOO:gsl_spline_eval_e",kwnames,&obj0,&arg2,&obj2,&obj3)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_gsl_spline,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    if ((SWIG_ConvertPtr(obj2,(void **) &arg3, SWIGTYPE_p_gsl_interp_accel,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    if ((SWIG_ConvertPtr(obj3,(void **) &arg4, SWIGTYPE_p_double,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    result = (int)gsl_spline_eval_e((gsl_spline const *)arg1,arg2,arg3,arg4);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_gsl_spline_eval(PyObject *self, PyObject *args, PyObject *kwargs) {
    PyObject *resultobj;
    gsl_spline *arg1 = (gsl_spline *) 0 ;
    double arg2 ;
    gsl_interp_accel *arg3 = (gsl_interp_accel *) 0 ;
    double result;
    PyObject * obj0  = 0 ;
    PyObject * obj2  = 0 ;
    char *kwnames[] = {
        "spline","x","a", NULL 
    };
    
    if(!PyArg_ParseTupleAndKeywords(args,kwargs,(char *)"OdO:gsl_spline_eval",kwnames,&obj0,&arg2,&obj2)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_gsl_spline,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    if ((SWIG_ConvertPtr(obj2,(void **) &arg3, SWIGTYPE_p_gsl_interp_accel,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    result = (double)gsl_spline_eval((gsl_spline const *)arg1,arg2,arg3);
    
    resultobj = PyFloat_FromDouble(result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_gsl_spline_eval_deriv_e(PyObject *self, PyObject *args, PyObject *kwargs) {
    PyObject *resultobj;
    gsl_spline *arg1 = (gsl_spline *) 0 ;
    double arg2 ;
    gsl_interp_accel *arg3 = (gsl_interp_accel *) 0 ;
    double *arg4 = (double *) 0 ;
    int result;
    PyObject * obj0  = 0 ;
    PyObject * obj2  = 0 ;
    PyObject * obj3  = 0 ;
    char *kwnames[] = {
        "spline","x","a","OUT", NULL 
    };
    
    if(!PyArg_ParseTupleAndKeywords(args,kwargs,(char *)"OdOO:gsl_spline_eval_deriv_e",kwnames,&obj0,&arg2,&obj2,&obj3)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_gsl_spline,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    if ((SWIG_ConvertPtr(obj2,(void **) &arg3, SWIGTYPE_p_gsl_interp_accel,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    if ((SWIG_ConvertPtr(obj3,(void **) &arg4, SWIGTYPE_p_double,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    result = (int)gsl_spline_eval_deriv_e((gsl_spline const *)arg1,arg2,arg3,arg4);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_gsl_spline_eval_deriv(PyObject *self, PyObject *args, PyObject *kwargs) {
    PyObject *resultobj;
    gsl_spline *arg1 = (gsl_spline *) 0 ;
    double arg2 ;
    gsl_interp_accel *arg3 = (gsl_interp_accel *) 0 ;
    double result;
    PyObject * obj0  = 0 ;
    PyObject * obj2  = 0 ;
    char *kwnames[] = {
        "spline","x","a", NULL 
    };
    
    if(!PyArg_ParseTupleAndKeywords(args,kwargs,(char *)"OdO:gsl_spline_eval_deriv",kwnames,&obj0,&arg2,&obj2)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_gsl_spline,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    if ((SWIG_ConvertPtr(obj2,(void **) &arg3, SWIGTYPE_p_gsl_interp_accel,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    result = (double)gsl_spline_eval_deriv((gsl_spline const *)arg1,arg2,arg3);
    
    resultobj = PyFloat_FromDouble(result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_gsl_spline_eval_deriv2_e(PyObject *self, PyObject *args, PyObject *kwargs) {
    PyObject *resultobj;
    gsl_spline *arg1 = (gsl_spline *) 0 ;
    double arg2 ;
    gsl_interp_accel *arg3 = (gsl_interp_accel *) 0 ;
    double *arg4 = (double *) 0 ;
    int result;
    PyObject * obj0  = 0 ;
    PyObject * obj2  = 0 ;
    PyObject * obj3  = 0 ;
    char *kwnames[] = {
        "spline","x","a","OUT", NULL 
    };
    
    if(!PyArg_ParseTupleAndKeywords(args,kwargs,(char *)"OdOO:gsl_spline_eval_deriv2_e",kwnames,&obj0,&arg2,&obj2,&obj3)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_gsl_spline,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    if ((SWIG_ConvertPtr(obj2,(void **) &arg3, SWIGTYPE_p_gsl_interp_accel,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    if ((SWIG_ConvertPtr(obj3,(void **) &arg4, SWIGTYPE_p_double,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    result = (int)gsl_spline_eval_deriv2_e((gsl_spline const *)arg1,arg2,arg3,arg4);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_gsl_spline_eval_deriv2(PyObject *self, PyObject *args, PyObject *kwargs) {
    PyObject *resultobj;
    gsl_spline *arg1 = (gsl_spline *) 0 ;
    double arg2 ;
    gsl_interp_accel *arg3 = (gsl_interp_accel *) 0 ;
    double result;
    PyObject * obj0  = 0 ;
    PyObject * obj2  = 0 ;
    char *kwnames[] = {
        "spline","x","a", NULL 
    };
    
    if(!PyArg_ParseTupleAndKeywords(args,kwargs,(char *)"OdO:gsl_spline_eval_deriv2",kwnames,&obj0,&arg2,&obj2)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_gsl_spline,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    if ((SWIG_ConvertPtr(obj2,(void **) &arg3, SWIGTYPE_p_gsl_interp_accel,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    result = (double)gsl_spline_eval_deriv2((gsl_spline const *)arg1,arg2,arg3);
    
    resultobj = PyFloat_FromDouble(result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_gsl_spline_eval_integ_e(PyObject *self, PyObject *args, PyObject *kwargs) {
    PyObject *resultobj;
    gsl_spline *arg1 = (gsl_spline *) 0 ;
    double arg2 ;
    double arg3 ;
    gsl_interp_accel *arg4 = (gsl_interp_accel *) 0 ;
    double *arg5 = (double *) 0 ;
    int result;
    PyObject * obj0  = 0 ;
    PyObject * obj3  = 0 ;
    PyObject * obj4  = 0 ;
    char *kwnames[] = {
        "spline","a","b","acc","OUT", NULL 
    };
    
    if(!PyArg_ParseTupleAndKeywords(args,kwargs,(char *)"OddOO:gsl_spline_eval_integ_e",kwnames,&obj0,&arg2,&arg3,&obj3,&obj4)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_gsl_spline,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    if ((SWIG_ConvertPtr(obj3,(void **) &arg4, SWIGTYPE_p_gsl_interp_accel,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    if ((SWIG_ConvertPtr(obj4,(void **) &arg5, SWIGTYPE_p_double,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    result = (int)gsl_spline_eval_integ_e((gsl_spline const *)arg1,arg2,arg3,arg4,arg5);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_gsl_spline_eval_integ(PyObject *self, PyObject *args, PyObject *kwargs) {
    PyObject *resultobj;
    gsl_spline *arg1 = (gsl_spline *) 0 ;
    double arg2 ;
    double arg3 ;
    gsl_interp_accel *arg4 = (gsl_interp_accel *) 0 ;
    double result;
    PyObject * obj0  = 0 ;
    PyObject * obj3  = 0 ;
    char *kwnames[] = {
        "spline","a","b","acc", NULL 
    };
    
    if(!PyArg_ParseTupleAndKeywords(args,kwargs,(char *)"OddO:gsl_spline_eval_integ",kwnames,&obj0,&arg2,&arg3,&obj3)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_gsl_spline,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    if ((SWIG_ConvertPtr(obj3,(void **) &arg4, SWIGTYPE_p_gsl_interp_accel,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    result = (double)gsl_spline_eval_integ((gsl_spline const *)arg1,arg2,arg3,arg4);
    
    resultobj = PyFloat_FromDouble(result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_gsl_spline_free(PyObject *self, PyObject *args, PyObject *kwargs) {
    PyObject *resultobj;
    gsl_spline *arg1 = (gsl_spline *) 0 ;
    PyObject * obj0  = 0 ;
    char *kwnames[] = {
        "spline", NULL 
    };
    
    if(!PyArg_ParseTupleAndKeywords(args,kwargs,(char *)"O:gsl_spline_free",kwnames,&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_gsl_spline,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    gsl_spline_free(arg1);
    
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
    fail:
    return NULL;
}


static int _wrap_gsl_interp_linear_set(PyObject *_val) {
    {
        void *temp;
        if ((SWIG_ConvertPtr(_val,(void **) &temp, SWIGTYPE_p_gsl_interp_type, SWIG_POINTER_EXCEPTION | SWIG_POINTER_DISOWN)) == -1) {
            PyErr_SetString(PyExc_TypeError, "C variable 'gsl_interp_linear (gsl_interp_type *)'");
            return 1;
        }
        gsl_interp_linear = (gsl_interp_type *) temp;
    }
    return 0;
}


static PyObject *_wrap_gsl_interp_linear_get() {
    PyObject *pyobj;
    
    pyobj = SWIG_NewPointerObj((void *) gsl_interp_linear, SWIGTYPE_p_gsl_interp_type, 0);
    return pyobj;
}


static int _wrap_gsl_interp_polynomial_set(PyObject *_val) {
    {
        void *temp;
        if ((SWIG_ConvertPtr(_val,(void **) &temp, SWIGTYPE_p_gsl_interp_type, SWIG_POINTER_EXCEPTION | SWIG_POINTER_DISOWN)) == -1) {
            PyErr_SetString(PyExc_TypeError, "C variable 'gsl_interp_polynomial (gsl_interp_type *)'");
            return 1;
        }
        gsl_interp_polynomial = (gsl_interp_type *) temp;
    }
    return 0;
}


static PyObject *_wrap_gsl_interp_polynomial_get() {
    PyObject *pyobj;
    
    pyobj = SWIG_NewPointerObj((void *) gsl_interp_polynomial, SWIGTYPE_p_gsl_interp_type, 0);
    return pyobj;
}


static int _wrap_gsl_interp_cspline_set(PyObject *_val) {
    {
        void *temp;
        if ((SWIG_ConvertPtr(_val,(void **) &temp, SWIGTYPE_p_gsl_interp_type, SWIG_POINTER_EXCEPTION | SWIG_POINTER_DISOWN)) == -1) {
            PyErr_SetString(PyExc_TypeError, "C variable 'gsl_interp_cspline (gsl_interp_type *)'");
            return 1;
        }
        gsl_interp_cspline = (gsl_interp_type *) temp;
    }
    return 0;
}


static PyObject *_wrap_gsl_interp_cspline_get() {
    PyObject *pyobj;
    
    pyobj = SWIG_NewPointerObj((void *) gsl_interp_cspline, SWIGTYPE_p_gsl_interp_type, 0);
    return pyobj;
}


static int _wrap_gsl_interp_cspline_periodic_set(PyObject *_val) {
    {
        void *temp;
        if ((SWIG_ConvertPtr(_val,(void **) &temp, SWIGTYPE_p_gsl_interp_type, SWIG_POINTER_EXCEPTION | SWIG_POINTER_DISOWN)) == -1) {
            PyErr_SetString(PyExc_TypeError, "C variable 'gsl_interp_cspline_periodic (gsl_interp_type *)'");
            return 1;
        }
        gsl_interp_cspline_periodic = (gsl_interp_type *) temp;
    }
    return 0;
}


static PyObject *_wrap_gsl_interp_cspline_periodic_get() {
    PyObject *pyobj;
    
    pyobj = SWIG_NewPointerObj((void *) gsl_interp_cspline_periodic, SWIGTYPE_p_gsl_interp_type, 0);
    return pyobj;
}


static int _wrap_gsl_interp_akima_set(PyObject *_val) {
    {
        void *temp;
        if ((SWIG_ConvertPtr(_val,(void **) &temp, SWIGTYPE_p_gsl_interp_type, SWIG_POINTER_EXCEPTION | SWIG_POINTER_DISOWN)) == -1) {
            PyErr_SetString(PyExc_TypeError, "C variable 'gsl_interp_akima (gsl_interp_type *)'");
            return 1;
        }
        gsl_interp_akima = (gsl_interp_type *) temp;
    }
    return 0;
}


static PyObject *_wrap_gsl_interp_akima_get() {
    PyObject *pyobj;
    
    pyobj = SWIG_NewPointerObj((void *) gsl_interp_akima, SWIGTYPE_p_gsl_interp_type, 0);
    return pyobj;
}


static int _wrap_gsl_interp_akima_periodic_set(PyObject *_val) {
    {
        void *temp;
        if ((SWIG_ConvertPtr(_val,(void **) &temp, SWIGTYPE_p_gsl_interp_type, SWIG_POINTER_EXCEPTION | SWIG_POINTER_DISOWN)) == -1) {
            PyErr_SetString(PyExc_TypeError, "C variable 'gsl_interp_akima_periodic (gsl_interp_type *)'");
            return 1;
        }
        gsl_interp_akima_periodic = (gsl_interp_type *) temp;
    }
    return 0;
}


static PyObject *_wrap_gsl_interp_akima_periodic_get() {
    PyObject *pyobj;
    
    pyobj = SWIG_NewPointerObj((void *) gsl_interp_akima_periodic, SWIGTYPE_p_gsl_interp_type, 0);
    return pyobj;
}


static PyObject *_wrap_gsl_interp_accel_alloc(PyObject *self, PyObject *args, PyObject *kwargs) {
    PyObject *resultobj;
    gsl_interp_accel *result;
    char *kwnames[] = {
        NULL 
    };
    
    if(!PyArg_ParseTupleAndKeywords(args,kwargs,(char *)":gsl_interp_accel_alloc",kwnames)) goto fail;
    result = (gsl_interp_accel *)gsl_interp_accel_alloc();
    
    resultobj = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_gsl_interp_accel, 0);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_gsl_interp_accel_find(PyObject *self, PyObject *args, PyObject *kwargs) {
    PyObject *resultobj;
    gsl_interp_accel *arg1 = (gsl_interp_accel *) 0 ;
    double *arg2 ;
    size_t arg3 ;
    double arg4 ;
    size_t result;
    PyObject * obj0  = 0 ;
    PyObject * obj1  = 0 ;
    char *kwnames[] = {
        "a","x_array","x", NULL 
    };
    
    
    PyArrayObject *_PyVector2 = NULL;
    
    if(!PyArg_ParseTupleAndKeywords(args,kwargs,(char *)"OOd:gsl_interp_accel_find",kwnames,&obj0,&obj1,&arg4)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_gsl_interp_accel,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    {
        int mysize = 0;
        _PyVector2 = PyGSL_PyArray_PREPARE_gsl_vector_view(
        obj1, PyArray_DOUBLE, 1, -1, 2, NULL);
        if (_PyVector2 == NULL)
        goto fail;
        
        mysize = _PyVector2->dimensions[0];
        arg2 = (double *)(_PyVector2->data);
        arg3 = (size_t n)mysize;
    }
    result = (size_t)gsl_interp_accel_find(arg1,(double const (*))arg2,arg3,arg4);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_gsl_interp_accel_reset(PyObject *self, PyObject *args, PyObject *kwargs) {
    PyObject *resultobj;
    gsl_interp_accel *arg1 = (gsl_interp_accel *) 0 ;
    int result;
    PyObject * obj0  = 0 ;
    char *kwnames[] = {
        "a", NULL 
    };
    
    if(!PyArg_ParseTupleAndKeywords(args,kwargs,(char *)"O:gsl_interp_accel_reset",kwnames,&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_gsl_interp_accel,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    result = (int)gsl_interp_accel_reset(arg1);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_gsl_interp_accel_free(PyObject *self, PyObject *args, PyObject *kwargs) {
    PyObject *resultobj;
    gsl_interp_accel *arg1 = (gsl_interp_accel *) 0 ;
    PyObject * obj0  = 0 ;
    char *kwnames[] = {
        "a", NULL 
    };
    
    if(!PyArg_ParseTupleAndKeywords(args,kwargs,(char *)"O:gsl_interp_accel_free",kwnames,&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_gsl_interp_accel,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    gsl_interp_accel_free(arg1);
    
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_gsl_interp_alloc(PyObject *self, PyObject *args, PyObject *kwargs) {
    PyObject *resultobj;
    gsl_interp_type *arg1 = (gsl_interp_type *) 0 ;
    size_t arg2 ;
    gsl_interp *result;
    PyObject * obj0  = 0 ;
    PyObject * obj1  = 0 ;
    char *kwnames[] = {
        "T","n", NULL 
    };
    
    if(!PyArg_ParseTupleAndKeywords(args,kwargs,(char *)"OO:gsl_interp_alloc",kwnames,&obj0,&obj1)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_gsl_interp_type,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    arg2 = (size_t) PyInt_AsLong(obj1);
    if (PyErr_Occurred()) SWIG_fail;
    result = (gsl_interp *)gsl_interp_alloc((gsl_interp_type const *)arg1,arg2);
    
    resultobj = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_gsl_interp, 0);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_gsl_interp_init(PyObject *self, PyObject *args, PyObject *kwargs) {
    PyObject *resultobj;
    gsl_interp *arg1 = (gsl_interp *) 0 ;
    double *arg2 ;
    double *arg3 ;
    size_t arg4 ;
    int result;
    PyObject * obj0  = 0 ;
    PyObject * obj1  = 0 ;
    char *kwnames[] = {
        "obj","xa", NULL 
    };
    
    
    PyArrayObject *_PyVector_12 = NULL;
    PyArrayObject *_PyVector_22 = NULL;
    
    if(!PyArg_ParseTupleAndKeywords(args,kwargs,(char *)"OO:gsl_interp_init",kwnames,&obj0,&obj1)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_gsl_interp,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    {
        int mysize = 0;
        _PyVector_12 = PyGSL_PyArray_PREPARE_gsl_vector_view(
        obj1, PyArray_DOUBLE, 1, -1, 2, NULL);
        if (_PyVector_12 == NULL)
        goto fail;
        
        mysize = _PyVector_12->dimensions[0];
        
        _PyVector_22 = PyGSL_PyArray_PREPARE_gsl_vector_view(
        obj1, PyArray_DOUBLE, 1, mysize, 2+1, NULL);
        if (_PyVector_22 == NULL)
        goto fail;
        
        arg2 = (double *)(_PyVector_12->data);
        arg3 = (size_t n)mysize;
        arg4 = (double *)(_PyVector_22->data);
    }
    {
        _PyVector2 = PyGSL_PyArray_PREPARE_gsl_vector_view(
        $input, PyArray_DOUBLE, 1, _gslinterp_size, 2, NULL);
        if (_PyVector2 == NULL)
        goto fail;
        arg2 = (double *)(_PyVector2->data);
    }
    {
        _PyVector3 = PyGSL_PyArray_PREPARE_gsl_vector_view(
        $input, PyArray_DOUBLE, 1, _gslinterp_size, 3, NULL);
        if (_PyVector3 == NULL)
        goto fail;
        arg3 = (double *)(_PyVector3->data);
    }
    result = (int)gsl_interp_init(arg1,(double const (*))arg2,(double const (*))arg3,arg4);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_gsl_interp_name(PyObject *self, PyObject *args, PyObject *kwargs) {
    PyObject *resultobj;
    gsl_interp *arg1 = (gsl_interp *) 0 ;
    char *result;
    PyObject * obj0  = 0 ;
    char *kwnames[] = {
        "interp", NULL 
    };
    
    if(!PyArg_ParseTupleAndKeywords(args,kwargs,(char *)"O:gsl_interp_name",kwnames,&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_gsl_interp,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    result = (char *)gsl_interp_name((gsl_interp const *)arg1);
    
    resultobj = result ? PyString_FromString(result) : Py_BuildValue((char*)"");
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_gsl_interp_min_size(PyObject *self, PyObject *args, PyObject *kwargs) {
    PyObject *resultobj;
    gsl_interp *arg1 = (gsl_interp *) 0 ;
    unsigned int result;
    PyObject * obj0  = 0 ;
    char *kwnames[] = {
        "interp", NULL 
    };
    
    if(!PyArg_ParseTupleAndKeywords(args,kwargs,(char *)"O:gsl_interp_min_size",kwnames,&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_gsl_interp,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    result = (unsigned int)gsl_interp_min_size((gsl_interp const *)arg1);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_gsl_interp_eval_e(PyObject *self, PyObject *args, PyObject *kwargs) {
    PyObject *resultobj;
    gsl_interp *arg1 = (gsl_interp *) 0 ;
    double *arg2 ;
    double *arg3 ;
    double arg4 ;
    gsl_interp_accel *arg5 = (gsl_interp_accel *) 0 ;
    double *arg6 = (double *) 0 ;
    int result;
    double temp6 ;
    PyObject * obj0  = 0 ;
    PyObject * obj1  = 0 ;
    PyObject * obj2  = 0 ;
    PyObject * obj4  = 0 ;
    char *kwnames[] = {
        "IN","xa","ya","x","a", NULL 
    };
    
    {
        _gslinterp_size = 0;
    }
    
    PyArrayObject *_PyVector2 = NULL;
    
    
    PyArrayObject *_PyVector3 = NULL;
    
    arg6 = &temp6;
    if(!PyArg_ParseTupleAndKeywords(args,kwargs,(char *)"OOOdO:gsl_interp_eval_e",kwnames,&obj0,&obj1,&obj2,&arg4,&obj4)) goto fail;
    {
        if(SWIG_ConvertPtr(step, (void **) &arg1, gsl_interp)){
            PyErr_SetString(PyExc_TypeError, "Could not convert gsl_interp to pointer");
            goto fail;
        }
        _gslinterp_size = (int) arg1->size;
    }
    {
        ;
    }
    {
        ;
    }
    if ((SWIG_ConvertPtr(obj4,(void **) &arg5, SWIGTYPE_p_gsl_interp_accel,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    {
        _PyVector2 = PyGSL_PyArray_PREPARE_gsl_vector_view(
        $input, PyArray_DOUBLE, 1, _gslinterp_size, 2, NULL);
        if (_PyVector2 == NULL)
        goto fail;
        arg2 = (double *)(_PyVector2->data);
    }
    {
        _PyVector3 = PyGSL_PyArray_PREPARE_gsl_vector_view(
        $input, PyArray_DOUBLE, 1, _gslinterp_size, 3, NULL);
        if (_PyVector3 == NULL)
        goto fail;
        arg3 = (double *)(_PyVector3->data);
    }
    result = (int)gsl_interp_eval_e((gsl_interp const *)arg1,(double const (*))arg2,(double const (*))arg3,arg4,arg5,arg6);
    
    resultobj = PyInt_FromLong((long)result);
    {
        PyObject *o = PyFloat_FromDouble((double) (*arg6));
        resultobj = t_output_helper(resultobj,o);
    }
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_gsl_interp_eval(PyObject *self, PyObject *args, PyObject *kwargs) {
    PyObject *resultobj;
    gsl_interp *arg1 = (gsl_interp *) 0 ;
    double *arg2 ;
    double *arg3 ;
    double arg4 ;
    gsl_interp_accel *arg5 = (gsl_interp_accel *) 0 ;
    double result;
    PyObject * obj0  = 0 ;
    PyObject * obj1  = 0 ;
    PyObject * obj2  = 0 ;
    PyObject * obj4  = 0 ;
    char *kwnames[] = {
        "IN","xa","ya","x","a", NULL 
    };
    
    {
        _gslinterp_size = 0;
    }
    
    PyArrayObject *_PyVector2 = NULL;
    
    
    PyArrayObject *_PyVector3 = NULL;
    
    if(!PyArg_ParseTupleAndKeywords(args,kwargs,(char *)"OOOdO:gsl_interp_eval",kwnames,&obj0,&obj1,&obj2,&arg4,&obj4)) goto fail;
    {
        if(SWIG_ConvertPtr(step, (void **) &arg1, gsl_interp)){
            PyErr_SetString(PyExc_TypeError, "Could not convert gsl_interp to pointer");
            goto fail;
        }
        _gslinterp_size = (int) arg1->size;
    }
    {
        ;
    }
    {
        ;
    }
    if ((SWIG_ConvertPtr(obj4,(void **) &arg5, SWIGTYPE_p_gsl_interp_accel,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    {
        _PyVector2 = PyGSL_PyArray_PREPARE_gsl_vector_view(
        $input, PyArray_DOUBLE, 1, _gslinterp_size, 2, NULL);
        if (_PyVector2 == NULL)
        goto fail;
        arg2 = (double *)(_PyVector2->data);
    }
    {
        _PyVector3 = PyGSL_PyArray_PREPARE_gsl_vector_view(
        $input, PyArray_DOUBLE, 1, _gslinterp_size, 3, NULL);
        if (_PyVector3 == NULL)
        goto fail;
        arg3 = (double *)(_PyVector3->data);
    }
    result = (double)gsl_interp_eval((gsl_interp const *)arg1,(double const (*))arg2,(double const (*))arg3,arg4,arg5);
    
    resultobj = PyFloat_FromDouble(result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_gsl_interp_eval_deriv_e(PyObject *self, PyObject *args, PyObject *kwargs) {
    PyObject *resultobj;
    gsl_interp *arg1 = (gsl_interp *) 0 ;
    double *arg2 ;
    double *arg3 ;
    double arg4 ;
    gsl_interp_accel *arg5 = (gsl_interp_accel *) 0 ;
    double *arg6 = (double *) 0 ;
    int result;
    double temp6 ;
    PyObject * obj0  = 0 ;
    PyObject * obj1  = 0 ;
    PyObject * obj2  = 0 ;
    PyObject * obj4  = 0 ;
    char *kwnames[] = {
        "IN","xa","ya","x","a", NULL 
    };
    
    {
        _gslinterp_size = 0;
    }
    
    PyArrayObject *_PyVector2 = NULL;
    
    
    PyArrayObject *_PyVector3 = NULL;
    
    arg6 = &temp6;
    if(!PyArg_ParseTupleAndKeywords(args,kwargs,(char *)"OOOdO:gsl_interp_eval_deriv_e",kwnames,&obj0,&obj1,&obj2,&arg4,&obj4)) goto fail;
    {
        if(SWIG_ConvertPtr(step, (void **) &arg1, gsl_interp)){
            PyErr_SetString(PyExc_TypeError, "Could not convert gsl_interp to pointer");
            goto fail;
        }
        _gslinterp_size = (int) arg1->size;
    }
    {
        ;
    }
    {
        ;
    }
    if ((SWIG_ConvertPtr(obj4,(void **) &arg5, SWIGTYPE_p_gsl_interp_accel,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    {
        _PyVector2 = PyGSL_PyArray_PREPARE_gsl_vector_view(
        $input, PyArray_DOUBLE, 1, _gslinterp_size, 2, NULL);
        if (_PyVector2 == NULL)
        goto fail;
        arg2 = (double *)(_PyVector2->data);
    }
    {
        _PyVector3 = PyGSL_PyArray_PREPARE_gsl_vector_view(
        $input, PyArray_DOUBLE, 1, _gslinterp_size, 3, NULL);
        if (_PyVector3 == NULL)
        goto fail;
        arg3 = (double *)(_PyVector3->data);
    }
    result = (int)gsl_interp_eval_deriv_e((gsl_interp const *)arg1,(double const (*))arg2,(double const (*))arg3,arg4,arg5,arg6);
    
    resultobj = PyInt_FromLong((long)result);
    {
        PyObject *o = PyFloat_FromDouble((double) (*arg6));
        resultobj = t_output_helper(resultobj,o);
    }
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_gsl_interp_eval_deriv(PyObject *self, PyObject *args, PyObject *kwargs) {
    PyObject *resultobj;
    gsl_interp *arg1 = (gsl_interp *) 0 ;
    double *arg2 ;
    double *arg3 ;
    double arg4 ;
    gsl_interp_accel *arg5 = (gsl_interp_accel *) 0 ;
    double result;
    PyObject * obj0  = 0 ;
    PyObject * obj1  = 0 ;
    PyObject * obj2  = 0 ;
    PyObject * obj4  = 0 ;
    char *kwnames[] = {
        "IN","xa","ya","x","a", NULL 
    };
    
    {
        _gslinterp_size = 0;
    }
    
    PyArrayObject *_PyVector2 = NULL;
    
    
    PyArrayObject *_PyVector3 = NULL;
    
    if(!PyArg_ParseTupleAndKeywords(args,kwargs,(char *)"OOOdO:gsl_interp_eval_deriv",kwnames,&obj0,&obj1,&obj2,&arg4,&obj4)) goto fail;
    {
        if(SWIG_ConvertPtr(step, (void **) &arg1, gsl_interp)){
            PyErr_SetString(PyExc_TypeError, "Could not convert gsl_interp to pointer");
            goto fail;
        }
        _gslinterp_size = (int) arg1->size;
    }
    {
        ;
    }
    {
        ;
    }
    if ((SWIG_ConvertPtr(obj4,(void **) &arg5, SWIGTYPE_p_gsl_interp_accel,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    {
        _PyVector2 = PyGSL_PyArray_PREPARE_gsl_vector_view(
        $input, PyArray_DOUBLE, 1, _gslinterp_size, 2, NULL);
        if (_PyVector2 == NULL)
        goto fail;
        arg2 = (double *)(_PyVector2->data);
    }
    {
        _PyVector3 = PyGSL_PyArray_PREPARE_gsl_vector_view(
        $input, PyArray_DOUBLE, 1, _gslinterp_size, 3, NULL);
        if (_PyVector3 == NULL)
        goto fail;
        arg3 = (double *)(_PyVector3->data);
    }
    result = (double)gsl_interp_eval_deriv((gsl_interp const *)arg1,(double const (*))arg2,(double const (*))arg3,arg4,arg5);
    
    resultobj = PyFloat_FromDouble(result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_gsl_interp_eval_deriv2_e(PyObject *self, PyObject *args, PyObject *kwargs) {
    PyObject *resultobj;
    gsl_interp *arg1 = (gsl_interp *) 0 ;
    double *arg2 ;
    double *arg3 ;
    double arg4 ;
    gsl_interp_accel *arg5 = (gsl_interp_accel *) 0 ;
    double *arg6 = (double *) 0 ;
    int result;
    double temp6 ;
    PyObject * obj0  = 0 ;
    PyObject * obj1  = 0 ;
    PyObject * obj2  = 0 ;
    PyObject * obj4  = 0 ;
    char *kwnames[] = {
        "IN","xa","ya","x","a", NULL 
    };
    
    {
        _gslinterp_size = 0;
    }
    
    PyArrayObject *_PyVector2 = NULL;
    
    
    PyArrayObject *_PyVector3 = NULL;
    
    arg6 = &temp6;
    if(!PyArg_ParseTupleAndKeywords(args,kwargs,(char *)"OOOdO:gsl_interp_eval_deriv2_e",kwnames,&obj0,&obj1,&obj2,&arg4,&obj4)) goto fail;
    {
        if(SWIG_ConvertPtr(step, (void **) &arg1, gsl_interp)){
            PyErr_SetString(PyExc_TypeError, "Could not convert gsl_interp to pointer");
            goto fail;
        }
        _gslinterp_size = (int) arg1->size;
    }
    {
        ;
    }
    {
        ;
    }
    if ((SWIG_ConvertPtr(obj4,(void **) &arg5, SWIGTYPE_p_gsl_interp_accel,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    {
        _PyVector2 = PyGSL_PyArray_PREPARE_gsl_vector_view(
        $input, PyArray_DOUBLE, 1, _gslinterp_size, 2, NULL);
        if (_PyVector2 == NULL)
        goto fail;
        arg2 = (double *)(_PyVector2->data);
    }
    {
        _PyVector3 = PyGSL_PyArray_PREPARE_gsl_vector_view(
        $input, PyArray_DOUBLE, 1, _gslinterp_size, 3, NULL);
        if (_PyVector3 == NULL)
        goto fail;
        arg3 = (double *)(_PyVector3->data);
    }
    result = (int)gsl_interp_eval_deriv2_e((gsl_interp const *)arg1,(double const (*))arg2,(double const (*))arg3,arg4,arg5,arg6);
    
    resultobj = PyInt_FromLong((long)result);
    {
        PyObject *o = PyFloat_FromDouble((double) (*arg6));
        resultobj = t_output_helper(resultobj,o);
    }
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_gsl_interp_eval_deriv2(PyObject *self, PyObject *args, PyObject *kwargs) {
    PyObject *resultobj;
    gsl_interp *arg1 = (gsl_interp *) 0 ;
    double *arg2 ;
    double *arg3 ;
    double arg4 ;
    gsl_interp_accel *arg5 = (gsl_interp_accel *) 0 ;
    double result;
    PyObject * obj0  = 0 ;
    PyObject * obj1  = 0 ;
    PyObject * obj2  = 0 ;
    PyObject * obj4  = 0 ;
    char *kwnames[] = {
        "IN","xa","ya","x","a", NULL 
    };
    
    {
        _gslinterp_size = 0;
    }
    
    PyArrayObject *_PyVector2 = NULL;
    
    
    PyArrayObject *_PyVector3 = NULL;
    
    if(!PyArg_ParseTupleAndKeywords(args,kwargs,(char *)"OOOdO:gsl_interp_eval_deriv2",kwnames,&obj0,&obj1,&obj2,&arg4,&obj4)) goto fail;
    {
        if(SWIG_ConvertPtr(step, (void **) &arg1, gsl_interp)){
            PyErr_SetString(PyExc_TypeError, "Could not convert gsl_interp to pointer");
            goto fail;
        }
        _gslinterp_size = (int) arg1->size;
    }
    {
        ;
    }
    {
        ;
    }
    if ((SWIG_ConvertPtr(obj4,(void **) &arg5, SWIGTYPE_p_gsl_interp_accel,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    {
        _PyVector2 = PyGSL_PyArray_PREPARE_gsl_vector_view(
        $input, PyArray_DOUBLE, 1, _gslinterp_size, 2, NULL);
        if (_PyVector2 == NULL)
        goto fail;
        arg2 = (double *)(_PyVector2->data);
    }
    {
        _PyVector3 = PyGSL_PyArray_PREPARE_gsl_vector_view(
        $input, PyArray_DOUBLE, 1, _gslinterp_size, 3, NULL);
        if (_PyVector3 == NULL)
        goto fail;
        arg3 = (double *)(_PyVector3->data);
    }
    result = (double)gsl_interp_eval_deriv2((gsl_interp const *)arg1,(double const (*))arg2,(double const (*))arg3,arg4,arg5);
    
    resultobj = PyFloat_FromDouble(result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_gsl_interp_eval_integ_e(PyObject *self, PyObject *args, PyObject *kwargs) {
    PyObject *resultobj;
    gsl_interp *arg1 = (gsl_interp *) 0 ;
    double *arg2 ;
    double *arg3 ;
    double arg4 ;
    double arg5 ;
    gsl_interp_accel *arg6 = (gsl_interp_accel *) 0 ;
    double *arg7 = (double *) 0 ;
    int result;
    double temp7 ;
    PyObject * obj0  = 0 ;
    PyObject * obj1  = 0 ;
    PyObject * obj2  = 0 ;
    PyObject * obj5  = 0 ;
    char *kwnames[] = {
        "IN","xa","ya","a","b","acc", NULL 
    };
    
    {
        _gslinterp_size = 0;
    }
    
    PyArrayObject *_PyVector2 = NULL;
    
    
    PyArrayObject *_PyVector3 = NULL;
    
    arg7 = &temp7;
    if(!PyArg_ParseTupleAndKeywords(args,kwargs,(char *)"OOOddO:gsl_interp_eval_integ_e",kwnames,&obj0,&obj1,&obj2,&arg4,&arg5,&obj5)) goto fail;
    {
        if(SWIG_ConvertPtr(step, (void **) &arg1, gsl_interp)){
            PyErr_SetString(PyExc_TypeError, "Could not convert gsl_interp to pointer");
            goto fail;
        }
        _gslinterp_size = (int) arg1->size;
    }
    {
        ;
    }
    {
        ;
    }
    if ((SWIG_ConvertPtr(obj5,(void **) &arg6, SWIGTYPE_p_gsl_interp_accel,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    {
        _PyVector2 = PyGSL_PyArray_PREPARE_gsl_vector_view(
        $input, PyArray_DOUBLE, 1, _gslinterp_size, 2, NULL);
        if (_PyVector2 == NULL)
        goto fail;
        arg2 = (double *)(_PyVector2->data);
    }
    {
        _PyVector3 = PyGSL_PyArray_PREPARE_gsl_vector_view(
        $input, PyArray_DOUBLE, 1, _gslinterp_size, 3, NULL);
        if (_PyVector3 == NULL)
        goto fail;
        arg3 = (double *)(_PyVector3->data);
    }
    result = (int)gsl_interp_eval_integ_e((gsl_interp const *)arg1,(double const (*))arg2,(double const (*))arg3,arg4,arg5,arg6,arg7);
    
    resultobj = PyInt_FromLong((long)result);
    {
        PyObject *o = PyFloat_FromDouble((double) (*arg7));
        resultobj = t_output_helper(resultobj,o);
    }
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_gsl_interp_eval_integ(PyObject *self, PyObject *args, PyObject *kwargs) {
    PyObject *resultobj;
    gsl_interp *arg1 = (gsl_interp *) 0 ;
    double *arg2 ;
    double *arg3 ;
    double arg4 ;
    double arg5 ;
    gsl_interp_accel *arg6 = (gsl_interp_accel *) 0 ;
    double result;
    PyObject * obj0  = 0 ;
    PyObject * obj1  = 0 ;
    PyObject * obj2  = 0 ;
    PyObject * obj5  = 0 ;
    char *kwnames[] = {
        "IN","xa","ya","a","b","acc", NULL 
    };
    
    {
        _gslinterp_size = 0;
    }
    
    PyArrayObject *_PyVector2 = NULL;
    
    
    PyArrayObject *_PyVector3 = NULL;
    
    if(!PyArg_ParseTupleAndKeywords(args,kwargs,(char *)"OOOddO:gsl_interp_eval_integ",kwnames,&obj0,&obj1,&obj2,&arg4,&arg5,&obj5)) goto fail;
    {
        if(SWIG_ConvertPtr(step, (void **) &arg1, gsl_interp)){
            PyErr_SetString(PyExc_TypeError, "Could not convert gsl_interp to pointer");
            goto fail;
        }
        _gslinterp_size = (int) arg1->size;
    }
    {
        ;
    }
    {
        ;
    }
    if ((SWIG_ConvertPtr(obj5,(void **) &arg6, SWIGTYPE_p_gsl_interp_accel,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    {
        _PyVector2 = PyGSL_PyArray_PREPARE_gsl_vector_view(
        $input, PyArray_DOUBLE, 1, _gslinterp_size, 2, NULL);
        if (_PyVector2 == NULL)
        goto fail;
        arg2 = (double *)(_PyVector2->data);
    }
    {
        _PyVector3 = PyGSL_PyArray_PREPARE_gsl_vector_view(
        $input, PyArray_DOUBLE, 1, _gslinterp_size, 3, NULL);
        if (_PyVector3 == NULL)
        goto fail;
        arg3 = (double *)(_PyVector3->data);
    }
    result = (double)gsl_interp_eval_integ((gsl_interp const *)arg1,(double const (*))arg2,(double const (*))arg3,arg4,arg5,arg6);
    
    resultobj = PyFloat_FromDouble(result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_gsl_interp_free(PyObject *self, PyObject *args, PyObject *kwargs) {
    PyObject *resultobj;
    gsl_interp *arg1 = (gsl_interp *) 0 ;
    PyObject * obj0  = 0 ;
    char *kwnames[] = {
        "interp", NULL 
    };
    
    if(!PyArg_ParseTupleAndKeywords(args,kwargs,(char *)"O:gsl_interp_free",kwnames,&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_gsl_interp,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    gsl_interp_free(arg1);
    
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_gsl_interp_bsearch(PyObject *self, PyObject *args, PyObject *kwargs) {
    PyObject *resultobj;
    double *arg1 ;
    double arg2 ;
    size_t arg3 ;
    size_t arg4 ;
    size_t result;
    PyObject * obj0  = 0 ;
    PyObject * obj2  = 0 ;
    PyObject * obj3  = 0 ;
    char *kwnames[] = {
        "x_array","x","index_lo","index_hi", NULL 
    };
    
    if(!PyArg_ParseTupleAndKeywords(args,kwargs,(char *)"OdOO:gsl_interp_bsearch",kwnames,&obj0,&arg2,&obj2,&obj3)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_double,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    arg3 = (size_t) PyInt_AsLong(obj2);
    if (PyErr_Occurred()) SWIG_fail;
    arg4 = (size_t) PyInt_AsLong(obj3);
    if (PyErr_Occurred()) SWIG_fail;
    result = (size_t)gsl_interp_bsearch((double const (*))arg1,arg2,arg3,arg4);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
    fail:
    return NULL;
}


static PyMethodDef SwigMethods[] = {
	 { (char *)"gsl_spline_alloc", (PyCFunction) _wrap_gsl_spline_alloc, METH_VARARGS | METH_KEYWORDS },
	 { (char *)"gsl_spline_init", (PyCFunction) _wrap_gsl_spline_init, METH_VARARGS | METH_KEYWORDS },
	 { (char *)"gsl_spline_eval_e", (PyCFunction) _wrap_gsl_spline_eval_e, METH_VARARGS | METH_KEYWORDS },
	 { (char *)"gsl_spline_eval", (PyCFunction) _wrap_gsl_spline_eval, METH_VARARGS | METH_KEYWORDS },
	 { (char *)"gsl_spline_eval_deriv_e", (PyCFunction) _wrap_gsl_spline_eval_deriv_e, METH_VARARGS | METH_KEYWORDS },
	 { (char *)"gsl_spline_eval_deriv", (PyCFunction) _wrap_gsl_spline_eval_deriv, METH_VARARGS | METH_KEYWORDS },
	 { (char *)"gsl_spline_eval_deriv2_e", (PyCFunction) _wrap_gsl_spline_eval_deriv2_e, METH_VARARGS | METH_KEYWORDS },
	 { (char *)"gsl_spline_eval_deriv2", (PyCFunction) _wrap_gsl_spline_eval_deriv2, METH_VARARGS | METH_KEYWORDS },
	 { (char *)"gsl_spline_eval_integ_e", (PyCFunction) _wrap_gsl_spline_eval_integ_e, METH_VARARGS | METH_KEYWORDS },
	 { (char *)"gsl_spline_eval_integ", (PyCFunction) _wrap_gsl_spline_eval_integ, METH_VARARGS | METH_KEYWORDS },
	 { (char *)"gsl_spline_free", (PyCFunction) _wrap_gsl_spline_free, METH_VARARGS | METH_KEYWORDS },
	 { (char *)"gsl_interp_accel_alloc", (PyCFunction) _wrap_gsl_interp_accel_alloc, METH_VARARGS | METH_KEYWORDS },
	 { (char *)"gsl_interp_accel_find", (PyCFunction) _wrap_gsl_interp_accel_find, METH_VARARGS | METH_KEYWORDS },
	 { (char *)"gsl_interp_accel_reset", (PyCFunction) _wrap_gsl_interp_accel_reset, METH_VARARGS | METH_KEYWORDS },
	 { (char *)"gsl_interp_accel_free", (PyCFunction) _wrap_gsl_interp_accel_free, METH_VARARGS | METH_KEYWORDS },
	 { (char *)"gsl_interp_alloc", (PyCFunction) _wrap_gsl_interp_alloc, METH_VARARGS | METH_KEYWORDS },
	 { (char *)"gsl_interp_init", (PyCFunction) _wrap_gsl_interp_init, METH_VARARGS | METH_KEYWORDS },
	 { (char *)"gsl_interp_name", (PyCFunction) _wrap_gsl_interp_name, METH_VARARGS | METH_KEYWORDS },
	 { (char *)"gsl_interp_min_size", (PyCFunction) _wrap_gsl_interp_min_size, METH_VARARGS | METH_KEYWORDS },
	 { (char *)"gsl_interp_eval_e", (PyCFunction) _wrap_gsl_interp_eval_e, METH_VARARGS | METH_KEYWORDS },
	 { (char *)"gsl_interp_eval", (PyCFunction) _wrap_gsl_interp_eval, METH_VARARGS | METH_KEYWORDS },
	 { (char *)"gsl_interp_eval_deriv_e", (PyCFunction) _wrap_gsl_interp_eval_deriv_e, METH_VARARGS | METH_KEYWORDS },
	 { (char *)"gsl_interp_eval_deriv", (PyCFunction) _wrap_gsl_interp_eval_deriv, METH_VARARGS | METH_KEYWORDS },
	 { (char *)"gsl_interp_eval_deriv2_e", (PyCFunction) _wrap_gsl_interp_eval_deriv2_e, METH_VARARGS | METH_KEYWORDS },
	 { (char *)"gsl_interp_eval_deriv2", (PyCFunction) _wrap_gsl_interp_eval_deriv2, METH_VARARGS | METH_KEYWORDS },
	 { (char *)"gsl_interp_eval_integ_e", (PyCFunction) _wrap_gsl_interp_eval_integ_e, METH_VARARGS | METH_KEYWORDS },
	 { (char *)"gsl_interp_eval_integ", (PyCFunction) _wrap_gsl_interp_eval_integ, METH_VARARGS | METH_KEYWORDS },
	 { (char *)"gsl_interp_free", (PyCFunction) _wrap_gsl_interp_free, METH_VARARGS | METH_KEYWORDS },
	 { (char *)"gsl_interp_bsearch", (PyCFunction) _wrap_gsl_interp_bsearch, METH_VARARGS | METH_KEYWORDS },
	 { NULL, NULL }
};


/* -------- TYPE CONVERSION AND EQUIVALENCE RULES (BEGIN) -------- */

static swig_type_info _swigt__p_gsl_interp[] = {{"_p_gsl_interp", 0, "gsl_interp *", 0},{"_p_gsl_interp"},{0}};
static swig_type_info _swigt__p_gsl_spline[] = {{"_p_gsl_spline", 0, "gsl_spline *", 0},{"_p_gsl_spline"},{0}};
static swig_type_info _swigt__p_double[] = {{"_p_double", 0, "double *", 0},{"_p_double"},{0}};
static swig_type_info _swigt__p_gsl_interp_type[] = {{"_p_gsl_interp_type", 0, "gsl_interp_type *", 0},{"_p_gsl_interp_type"},{0}};
static swig_type_info _swigt__p_gsl_interp_accel[] = {{"_p_gsl_interp_accel", 0, "gsl_interp_accel *", 0},{"_p_gsl_interp_accel"},{0}};

static swig_type_info *swig_types_initial[] = {
_swigt__p_gsl_interp, 
_swigt__p_gsl_spline, 
_swigt__p_double, 
_swigt__p_gsl_interp_type, 
_swigt__p_gsl_interp_accel, 
0
};


/* -------- TYPE CONVERSION AND EQUIVALENCE RULES (END) -------- */

static swig_const_info swig_const_table[] = {
{0}};

#ifdef __cplusplus
}
#endif

#ifdef __cplusplus
extern "C"
#endif
SWIGEXPORT(void) SWIG_init(void) {
    static PyObject *SWIG_globals = 0; 
    static int       typeinit = 0;
    PyObject *m, *d;
    int       i;
    if (!SWIG_globals) SWIG_globals = SWIG_newvarlink();
    m = Py_InitModule((char *) SWIG_name, SwigMethods);
    d = PyModule_GetDict(m);
    
    if (!typeinit) {
        for (i = 0; swig_types_initial[i]; i++) {
            swig_types[i] = SWIG_TypeRegister(swig_types_initial[i]);
        }
        typeinit = 1;
    }
    SWIG_InstallConstants(d,swig_const_table);
    
    
    import_array();
    
    PyDict_SetItemString(d,(char*)"cvar", SWIG_globals);
    SWIG_addvarlink(SWIG_globals,(char*)"gsl_interp_linear",_wrap_gsl_interp_linear_get, _wrap_gsl_interp_linear_set);
    SWIG_addvarlink(SWIG_globals,(char*)"gsl_interp_polynomial",_wrap_gsl_interp_polynomial_get, _wrap_gsl_interp_polynomial_set);
    SWIG_addvarlink(SWIG_globals,(char*)"gsl_interp_cspline",_wrap_gsl_interp_cspline_get, _wrap_gsl_interp_cspline_set);
    SWIG_addvarlink(SWIG_globals,(char*)"gsl_interp_cspline_periodic",_wrap_gsl_interp_cspline_periodic_get, _wrap_gsl_interp_cspline_periodic_set);
    SWIG_addvarlink(SWIG_globals,(char*)"gsl_interp_akima",_wrap_gsl_interp_akima_get, _wrap_gsl_interp_akima_set);
    SWIG_addvarlink(SWIG_globals,(char*)"gsl_interp_akima_periodic",_wrap_gsl_interp_akima_periodic_get, _wrap_gsl_interp_akima_periodic_set);
}

