#ifndef PYGSL_BLOCK_HELPERS_NUMARRAY_H
#define PYGSL_BLOCK_HELPERS_NUMARRAY_H 1

#ifndef CONTIGUOUS
#define CONTIGUOUS NPY_CONTIGUOUS
#endif

#ifndef _PyGSL_API_MODULE

#endif /* _PyGSL_API_MODULE */

#endif  /* PYGSL_BLOCK_HELPERS_NUMARRAY_H */
