# This file was automatically generated by SWIG (http://www.swig.org).
# Version 2.0.12
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('__block', [dirname(__file__)])
        except ImportError:
            import __block
            return __block
        if fp is not None:
            try:
                _mod = imp.load_module('__block', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    __block = swig_import_helper()
    del swig_import_helper
else:
    import __block
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0



def gsl_vector_set_zero(*args, **kwargs):
  return __block.gsl_vector_set_zero(*args, **kwargs)
gsl_vector_set_zero = __block.gsl_vector_set_zero

def gsl_vector_set_all(*args, **kwargs):
  return __block.gsl_vector_set_all(*args, **kwargs)
gsl_vector_set_all = __block.gsl_vector_set_all

def gsl_vector_set_basis(*args, **kwargs):
  return __block.gsl_vector_set_basis(*args, **kwargs)
gsl_vector_set_basis = __block.gsl_vector_set_basis

def gsl_vector_fread(*args, **kwargs):
  return __block.gsl_vector_fread(*args, **kwargs)
gsl_vector_fread = __block.gsl_vector_fread

def gsl_vector_fwrite(*args, **kwargs):
  return __block.gsl_vector_fwrite(*args, **kwargs)
gsl_vector_fwrite = __block.gsl_vector_fwrite

def gsl_vector_fscanf(*args, **kwargs):
  return __block.gsl_vector_fscanf(*args, **kwargs)
gsl_vector_fscanf = __block.gsl_vector_fscanf

def gsl_vector_fprintf(*args, **kwargs):
  return __block.gsl_vector_fprintf(*args, **kwargs)
gsl_vector_fprintf = __block.gsl_vector_fprintf

def gsl_vector_reverse(*args, **kwargs):
  return __block.gsl_vector_reverse(*args, **kwargs)
gsl_vector_reverse = __block.gsl_vector_reverse

def gsl_vector_swap(*args, **kwargs):
  return __block.gsl_vector_swap(*args, **kwargs)
gsl_vector_swap = __block.gsl_vector_swap

def gsl_vector_swap_elements(*args, **kwargs):
  return __block.gsl_vector_swap_elements(*args, **kwargs)
gsl_vector_swap_elements = __block.gsl_vector_swap_elements

def gsl_vector_max(*args, **kwargs):
  return __block.gsl_vector_max(*args, **kwargs)
gsl_vector_max = __block.gsl_vector_max

def gsl_vector_min(*args, **kwargs):
  return __block.gsl_vector_min(*args, **kwargs)
gsl_vector_min = __block.gsl_vector_min

def gsl_vector_minmax(*args, **kwargs):
  return __block.gsl_vector_minmax(*args, **kwargs)
gsl_vector_minmax = __block.gsl_vector_minmax

def gsl_vector_max_index(*args, **kwargs):
  return __block.gsl_vector_max_index(*args, **kwargs)
gsl_vector_max_index = __block.gsl_vector_max_index

def gsl_vector_min_index(*args, **kwargs):
  return __block.gsl_vector_min_index(*args, **kwargs)
gsl_vector_min_index = __block.gsl_vector_min_index

def gsl_vector_minmax_index(*args, **kwargs):
  return __block.gsl_vector_minmax_index(*args, **kwargs)
gsl_vector_minmax_index = __block.gsl_vector_minmax_index

def gsl_vector_isnull(*args, **kwargs):
  return __block.gsl_vector_isnull(*args, **kwargs)
gsl_vector_isnull = __block.gsl_vector_isnull

def gsl_matrix_set_zero(*args, **kwargs):
  return __block.gsl_matrix_set_zero(*args, **kwargs)
gsl_matrix_set_zero = __block.gsl_matrix_set_zero

def gsl_matrix_set_all(*args, **kwargs):
  return __block.gsl_matrix_set_all(*args, **kwargs)
gsl_matrix_set_all = __block.gsl_matrix_set_all

def gsl_matrix_set_identity(*args, **kwargs):
  return __block.gsl_matrix_set_identity(*args, **kwargs)
gsl_matrix_set_identity = __block.gsl_matrix_set_identity

def gsl_matrix_fread(*args, **kwargs):
  return __block.gsl_matrix_fread(*args, **kwargs)
gsl_matrix_fread = __block.gsl_matrix_fread

def gsl_matrix_fwrite(*args, **kwargs):
  return __block.gsl_matrix_fwrite(*args, **kwargs)
gsl_matrix_fwrite = __block.gsl_matrix_fwrite

def gsl_matrix_fscanf(*args, **kwargs):
  return __block.gsl_matrix_fscanf(*args, **kwargs)
gsl_matrix_fscanf = __block.gsl_matrix_fscanf

def gsl_matrix_fprintf(*args, **kwargs):
  return __block.gsl_matrix_fprintf(*args, **kwargs)
gsl_matrix_fprintf = __block.gsl_matrix_fprintf

def gsl_matrix_swap(*args, **kwargs):
  return __block.gsl_matrix_swap(*args, **kwargs)
gsl_matrix_swap = __block.gsl_matrix_swap

def gsl_matrix_swap_rows(*args, **kwargs):
  return __block.gsl_matrix_swap_rows(*args, **kwargs)
gsl_matrix_swap_rows = __block.gsl_matrix_swap_rows

def gsl_matrix_swap_columns(*args, **kwargs):
  return __block.gsl_matrix_swap_columns(*args, **kwargs)
gsl_matrix_swap_columns = __block.gsl_matrix_swap_columns

def gsl_matrix_swap_rowcol(*args, **kwargs):
  return __block.gsl_matrix_swap_rowcol(*args, **kwargs)
gsl_matrix_swap_rowcol = __block.gsl_matrix_swap_rowcol

def gsl_matrix_transpose(*args, **kwargs):
  return __block.gsl_matrix_transpose(*args, **kwargs)
gsl_matrix_transpose = __block.gsl_matrix_transpose

def gsl_matrix_max(*args, **kwargs):
  return __block.gsl_matrix_max(*args, **kwargs)
gsl_matrix_max = __block.gsl_matrix_max

def gsl_matrix_min(*args, **kwargs):
  return __block.gsl_matrix_min(*args, **kwargs)
gsl_matrix_min = __block.gsl_matrix_min

def gsl_matrix_minmax(*args, **kwargs):
  return __block.gsl_matrix_minmax(*args, **kwargs)
gsl_matrix_minmax = __block.gsl_matrix_minmax

def gsl_matrix_max_index(*args, **kwargs):
  return __block.gsl_matrix_max_index(*args, **kwargs)
gsl_matrix_max_index = __block.gsl_matrix_max_index

def gsl_matrix_min_index(*args, **kwargs):
  return __block.gsl_matrix_min_index(*args, **kwargs)
gsl_matrix_min_index = __block.gsl_matrix_min_index

def gsl_matrix_minmax_index(*args, **kwargs):
  return __block.gsl_matrix_minmax_index(*args, **kwargs)
gsl_matrix_minmax_index = __block.gsl_matrix_minmax_index

def gsl_matrix_isnull(*args, **kwargs):
  return __block.gsl_matrix_isnull(*args, **kwargs)
gsl_matrix_isnull = __block.gsl_matrix_isnull

def gsl_matrix_diagonal(*args, **kwargs):
  return __block.gsl_matrix_diagonal(*args, **kwargs)
gsl_matrix_diagonal = __block.gsl_matrix_diagonal

def gsl_matrix_subdiagonal(*args, **kwargs):
  return __block.gsl_matrix_subdiagonal(*args, **kwargs)
gsl_matrix_subdiagonal = __block.gsl_matrix_subdiagonal

def gsl_matrix_superdiagonal(*args, **kwargs):
  return __block.gsl_matrix_superdiagonal(*args, **kwargs)
gsl_matrix_superdiagonal = __block.gsl_matrix_superdiagonal

def gsl_vector_float_set_zero(*args, **kwargs):
  return __block.gsl_vector_float_set_zero(*args, **kwargs)
gsl_vector_float_set_zero = __block.gsl_vector_float_set_zero

def gsl_vector_float_set_all(*args, **kwargs):
  return __block.gsl_vector_float_set_all(*args, **kwargs)
gsl_vector_float_set_all = __block.gsl_vector_float_set_all

def gsl_vector_float_set_basis(*args, **kwargs):
  return __block.gsl_vector_float_set_basis(*args, **kwargs)
gsl_vector_float_set_basis = __block.gsl_vector_float_set_basis

def gsl_vector_float_fread(*args, **kwargs):
  return __block.gsl_vector_float_fread(*args, **kwargs)
gsl_vector_float_fread = __block.gsl_vector_float_fread

def gsl_vector_float_fwrite(*args, **kwargs):
  return __block.gsl_vector_float_fwrite(*args, **kwargs)
gsl_vector_float_fwrite = __block.gsl_vector_float_fwrite

def gsl_vector_float_fscanf(*args, **kwargs):
  return __block.gsl_vector_float_fscanf(*args, **kwargs)
gsl_vector_float_fscanf = __block.gsl_vector_float_fscanf

def gsl_vector_float_fprintf(*args, **kwargs):
  return __block.gsl_vector_float_fprintf(*args, **kwargs)
gsl_vector_float_fprintf = __block.gsl_vector_float_fprintf

def gsl_vector_float_reverse(*args, **kwargs):
  return __block.gsl_vector_float_reverse(*args, **kwargs)
gsl_vector_float_reverse = __block.gsl_vector_float_reverse

def gsl_vector_float_swap(*args, **kwargs):
  return __block.gsl_vector_float_swap(*args, **kwargs)
gsl_vector_float_swap = __block.gsl_vector_float_swap

def gsl_vector_float_swap_elements(*args, **kwargs):
  return __block.gsl_vector_float_swap_elements(*args, **kwargs)
gsl_vector_float_swap_elements = __block.gsl_vector_float_swap_elements

def gsl_vector_float_max(*args, **kwargs):
  return __block.gsl_vector_float_max(*args, **kwargs)
gsl_vector_float_max = __block.gsl_vector_float_max

def gsl_vector_float_min(*args, **kwargs):
  return __block.gsl_vector_float_min(*args, **kwargs)
gsl_vector_float_min = __block.gsl_vector_float_min

def gsl_vector_float_minmax(*args, **kwargs):
  return __block.gsl_vector_float_minmax(*args, **kwargs)
gsl_vector_float_minmax = __block.gsl_vector_float_minmax

def gsl_vector_float_max_index(*args, **kwargs):
  return __block.gsl_vector_float_max_index(*args, **kwargs)
gsl_vector_float_max_index = __block.gsl_vector_float_max_index

def gsl_vector_float_min_index(*args, **kwargs):
  return __block.gsl_vector_float_min_index(*args, **kwargs)
gsl_vector_float_min_index = __block.gsl_vector_float_min_index

def gsl_vector_float_minmax_index(*args, **kwargs):
  return __block.gsl_vector_float_minmax_index(*args, **kwargs)
gsl_vector_float_minmax_index = __block.gsl_vector_float_minmax_index

def gsl_vector_float_isnull(*args, **kwargs):
  return __block.gsl_vector_float_isnull(*args, **kwargs)
gsl_vector_float_isnull = __block.gsl_vector_float_isnull

def gsl_matrix_float_set_zero(*args, **kwargs):
  return __block.gsl_matrix_float_set_zero(*args, **kwargs)
gsl_matrix_float_set_zero = __block.gsl_matrix_float_set_zero

def gsl_matrix_float_set_all(*args, **kwargs):
  return __block.gsl_matrix_float_set_all(*args, **kwargs)
gsl_matrix_float_set_all = __block.gsl_matrix_float_set_all

def gsl_matrix_float_set_identity(*args, **kwargs):
  return __block.gsl_matrix_float_set_identity(*args, **kwargs)
gsl_matrix_float_set_identity = __block.gsl_matrix_float_set_identity

def gsl_matrix_float_fread(*args, **kwargs):
  return __block.gsl_matrix_float_fread(*args, **kwargs)
gsl_matrix_float_fread = __block.gsl_matrix_float_fread

def gsl_matrix_float_fwrite(*args, **kwargs):
  return __block.gsl_matrix_float_fwrite(*args, **kwargs)
gsl_matrix_float_fwrite = __block.gsl_matrix_float_fwrite

def gsl_matrix_float_fscanf(*args, **kwargs):
  return __block.gsl_matrix_float_fscanf(*args, **kwargs)
gsl_matrix_float_fscanf = __block.gsl_matrix_float_fscanf

def gsl_matrix_float_fprintf(*args, **kwargs):
  return __block.gsl_matrix_float_fprintf(*args, **kwargs)
gsl_matrix_float_fprintf = __block.gsl_matrix_float_fprintf

def gsl_matrix_float_swap(*args, **kwargs):
  return __block.gsl_matrix_float_swap(*args, **kwargs)
gsl_matrix_float_swap = __block.gsl_matrix_float_swap

def gsl_matrix_float_swap_rows(*args, **kwargs):
  return __block.gsl_matrix_float_swap_rows(*args, **kwargs)
gsl_matrix_float_swap_rows = __block.gsl_matrix_float_swap_rows

def gsl_matrix_float_swap_columns(*args, **kwargs):
  return __block.gsl_matrix_float_swap_columns(*args, **kwargs)
gsl_matrix_float_swap_columns = __block.gsl_matrix_float_swap_columns

def gsl_matrix_float_swap_rowcol(*args, **kwargs):
  return __block.gsl_matrix_float_swap_rowcol(*args, **kwargs)
gsl_matrix_float_swap_rowcol = __block.gsl_matrix_float_swap_rowcol

def gsl_matrix_float_transpose(*args, **kwargs):
  return __block.gsl_matrix_float_transpose(*args, **kwargs)
gsl_matrix_float_transpose = __block.gsl_matrix_float_transpose

def gsl_matrix_float_max(*args, **kwargs):
  return __block.gsl_matrix_float_max(*args, **kwargs)
gsl_matrix_float_max = __block.gsl_matrix_float_max

def gsl_matrix_float_min(*args, **kwargs):
  return __block.gsl_matrix_float_min(*args, **kwargs)
gsl_matrix_float_min = __block.gsl_matrix_float_min

def gsl_matrix_float_minmax(*args, **kwargs):
  return __block.gsl_matrix_float_minmax(*args, **kwargs)
gsl_matrix_float_minmax = __block.gsl_matrix_float_minmax

def gsl_matrix_float_max_index(*args, **kwargs):
  return __block.gsl_matrix_float_max_index(*args, **kwargs)
gsl_matrix_float_max_index = __block.gsl_matrix_float_max_index

def gsl_matrix_float_min_index(*args, **kwargs):
  return __block.gsl_matrix_float_min_index(*args, **kwargs)
gsl_matrix_float_min_index = __block.gsl_matrix_float_min_index

def gsl_matrix_float_minmax_index(*args, **kwargs):
  return __block.gsl_matrix_float_minmax_index(*args, **kwargs)
gsl_matrix_float_minmax_index = __block.gsl_matrix_float_minmax_index

def gsl_matrix_float_isnull(*args, **kwargs):
  return __block.gsl_matrix_float_isnull(*args, **kwargs)
gsl_matrix_float_isnull = __block.gsl_matrix_float_isnull

def gsl_matrix_float_diagonal(*args, **kwargs):
  return __block.gsl_matrix_float_diagonal(*args, **kwargs)
gsl_matrix_float_diagonal = __block.gsl_matrix_float_diagonal

def gsl_matrix_float_subdiagonal(*args, **kwargs):
  return __block.gsl_matrix_float_subdiagonal(*args, **kwargs)
gsl_matrix_float_subdiagonal = __block.gsl_matrix_float_subdiagonal

def gsl_matrix_float_superdiagonal(*args, **kwargs):
  return __block.gsl_matrix_float_superdiagonal(*args, **kwargs)
gsl_matrix_float_superdiagonal = __block.gsl_matrix_float_superdiagonal

def gsl_vector_long_set_zero(*args, **kwargs):
  return __block.gsl_vector_long_set_zero(*args, **kwargs)
gsl_vector_long_set_zero = __block.gsl_vector_long_set_zero

def gsl_vector_long_set_all(*args, **kwargs):
  return __block.gsl_vector_long_set_all(*args, **kwargs)
gsl_vector_long_set_all = __block.gsl_vector_long_set_all

def gsl_vector_long_set_basis(*args, **kwargs):
  return __block.gsl_vector_long_set_basis(*args, **kwargs)
gsl_vector_long_set_basis = __block.gsl_vector_long_set_basis

def gsl_vector_long_fread(*args, **kwargs):
  return __block.gsl_vector_long_fread(*args, **kwargs)
gsl_vector_long_fread = __block.gsl_vector_long_fread

def gsl_vector_long_fwrite(*args, **kwargs):
  return __block.gsl_vector_long_fwrite(*args, **kwargs)
gsl_vector_long_fwrite = __block.gsl_vector_long_fwrite

def gsl_vector_long_fscanf(*args, **kwargs):
  return __block.gsl_vector_long_fscanf(*args, **kwargs)
gsl_vector_long_fscanf = __block.gsl_vector_long_fscanf

def gsl_vector_long_fprintf(*args, **kwargs):
  return __block.gsl_vector_long_fprintf(*args, **kwargs)
gsl_vector_long_fprintf = __block.gsl_vector_long_fprintf

def gsl_vector_long_reverse(*args, **kwargs):
  return __block.gsl_vector_long_reverse(*args, **kwargs)
gsl_vector_long_reverse = __block.gsl_vector_long_reverse

def gsl_vector_long_swap(*args, **kwargs):
  return __block.gsl_vector_long_swap(*args, **kwargs)
gsl_vector_long_swap = __block.gsl_vector_long_swap

def gsl_vector_long_swap_elements(*args, **kwargs):
  return __block.gsl_vector_long_swap_elements(*args, **kwargs)
gsl_vector_long_swap_elements = __block.gsl_vector_long_swap_elements

def gsl_vector_long_max(*args, **kwargs):
  return __block.gsl_vector_long_max(*args, **kwargs)
gsl_vector_long_max = __block.gsl_vector_long_max

def gsl_vector_long_min(*args, **kwargs):
  return __block.gsl_vector_long_min(*args, **kwargs)
gsl_vector_long_min = __block.gsl_vector_long_min

def gsl_vector_long_minmax(*args, **kwargs):
  return __block.gsl_vector_long_minmax(*args, **kwargs)
gsl_vector_long_minmax = __block.gsl_vector_long_minmax

def gsl_vector_long_max_index(*args, **kwargs):
  return __block.gsl_vector_long_max_index(*args, **kwargs)
gsl_vector_long_max_index = __block.gsl_vector_long_max_index

def gsl_vector_long_min_index(*args, **kwargs):
  return __block.gsl_vector_long_min_index(*args, **kwargs)
gsl_vector_long_min_index = __block.gsl_vector_long_min_index

def gsl_vector_long_minmax_index(*args, **kwargs):
  return __block.gsl_vector_long_minmax_index(*args, **kwargs)
gsl_vector_long_minmax_index = __block.gsl_vector_long_minmax_index

def gsl_vector_long_isnull(*args, **kwargs):
  return __block.gsl_vector_long_isnull(*args, **kwargs)
gsl_vector_long_isnull = __block.gsl_vector_long_isnull

def gsl_matrix_long_set_zero(*args, **kwargs):
  return __block.gsl_matrix_long_set_zero(*args, **kwargs)
gsl_matrix_long_set_zero = __block.gsl_matrix_long_set_zero

def gsl_matrix_long_set_all(*args, **kwargs):
  return __block.gsl_matrix_long_set_all(*args, **kwargs)
gsl_matrix_long_set_all = __block.gsl_matrix_long_set_all

def gsl_matrix_long_set_identity(*args, **kwargs):
  return __block.gsl_matrix_long_set_identity(*args, **kwargs)
gsl_matrix_long_set_identity = __block.gsl_matrix_long_set_identity

def gsl_matrix_long_fread(*args, **kwargs):
  return __block.gsl_matrix_long_fread(*args, **kwargs)
gsl_matrix_long_fread = __block.gsl_matrix_long_fread

def gsl_matrix_long_fwrite(*args, **kwargs):
  return __block.gsl_matrix_long_fwrite(*args, **kwargs)
gsl_matrix_long_fwrite = __block.gsl_matrix_long_fwrite

def gsl_matrix_long_fscanf(*args, **kwargs):
  return __block.gsl_matrix_long_fscanf(*args, **kwargs)
gsl_matrix_long_fscanf = __block.gsl_matrix_long_fscanf

def gsl_matrix_long_fprintf(*args, **kwargs):
  return __block.gsl_matrix_long_fprintf(*args, **kwargs)
gsl_matrix_long_fprintf = __block.gsl_matrix_long_fprintf

def gsl_matrix_long_swap(*args, **kwargs):
  return __block.gsl_matrix_long_swap(*args, **kwargs)
gsl_matrix_long_swap = __block.gsl_matrix_long_swap

def gsl_matrix_long_swap_rows(*args, **kwargs):
  return __block.gsl_matrix_long_swap_rows(*args, **kwargs)
gsl_matrix_long_swap_rows = __block.gsl_matrix_long_swap_rows

def gsl_matrix_long_swap_columns(*args, **kwargs):
  return __block.gsl_matrix_long_swap_columns(*args, **kwargs)
gsl_matrix_long_swap_columns = __block.gsl_matrix_long_swap_columns

def gsl_matrix_long_swap_rowcol(*args, **kwargs):
  return __block.gsl_matrix_long_swap_rowcol(*args, **kwargs)
gsl_matrix_long_swap_rowcol = __block.gsl_matrix_long_swap_rowcol

def gsl_matrix_long_transpose(*args, **kwargs):
  return __block.gsl_matrix_long_transpose(*args, **kwargs)
gsl_matrix_long_transpose = __block.gsl_matrix_long_transpose

def gsl_matrix_long_max(*args, **kwargs):
  return __block.gsl_matrix_long_max(*args, **kwargs)
gsl_matrix_long_max = __block.gsl_matrix_long_max

def gsl_matrix_long_min(*args, **kwargs):
  return __block.gsl_matrix_long_min(*args, **kwargs)
gsl_matrix_long_min = __block.gsl_matrix_long_min

def gsl_matrix_long_minmax(*args, **kwargs):
  return __block.gsl_matrix_long_minmax(*args, **kwargs)
gsl_matrix_long_minmax = __block.gsl_matrix_long_minmax

def gsl_matrix_long_max_index(*args, **kwargs):
  return __block.gsl_matrix_long_max_index(*args, **kwargs)
gsl_matrix_long_max_index = __block.gsl_matrix_long_max_index

def gsl_matrix_long_min_index(*args, **kwargs):
  return __block.gsl_matrix_long_min_index(*args, **kwargs)
gsl_matrix_long_min_index = __block.gsl_matrix_long_min_index

def gsl_matrix_long_minmax_index(*args, **kwargs):
  return __block.gsl_matrix_long_minmax_index(*args, **kwargs)
gsl_matrix_long_minmax_index = __block.gsl_matrix_long_minmax_index

def gsl_matrix_long_isnull(*args, **kwargs):
  return __block.gsl_matrix_long_isnull(*args, **kwargs)
gsl_matrix_long_isnull = __block.gsl_matrix_long_isnull

def gsl_matrix_long_diagonal(*args, **kwargs):
  return __block.gsl_matrix_long_diagonal(*args, **kwargs)
gsl_matrix_long_diagonal = __block.gsl_matrix_long_diagonal

def gsl_matrix_long_subdiagonal(*args, **kwargs):
  return __block.gsl_matrix_long_subdiagonal(*args, **kwargs)
gsl_matrix_long_subdiagonal = __block.gsl_matrix_long_subdiagonal

def gsl_matrix_long_superdiagonal(*args, **kwargs):
  return __block.gsl_matrix_long_superdiagonal(*args, **kwargs)
gsl_matrix_long_superdiagonal = __block.gsl_matrix_long_superdiagonal

def gsl_vector_int_set_zero(*args, **kwargs):
  return __block.gsl_vector_int_set_zero(*args, **kwargs)
gsl_vector_int_set_zero = __block.gsl_vector_int_set_zero

def gsl_vector_int_set_all(*args, **kwargs):
  return __block.gsl_vector_int_set_all(*args, **kwargs)
gsl_vector_int_set_all = __block.gsl_vector_int_set_all

def gsl_vector_int_set_basis(*args, **kwargs):
  return __block.gsl_vector_int_set_basis(*args, **kwargs)
gsl_vector_int_set_basis = __block.gsl_vector_int_set_basis

def gsl_vector_int_fread(*args, **kwargs):
  return __block.gsl_vector_int_fread(*args, **kwargs)
gsl_vector_int_fread = __block.gsl_vector_int_fread

def gsl_vector_int_fwrite(*args, **kwargs):
  return __block.gsl_vector_int_fwrite(*args, **kwargs)
gsl_vector_int_fwrite = __block.gsl_vector_int_fwrite

def gsl_vector_int_fscanf(*args, **kwargs):
  return __block.gsl_vector_int_fscanf(*args, **kwargs)
gsl_vector_int_fscanf = __block.gsl_vector_int_fscanf

def gsl_vector_int_fprintf(*args, **kwargs):
  return __block.gsl_vector_int_fprintf(*args, **kwargs)
gsl_vector_int_fprintf = __block.gsl_vector_int_fprintf

def gsl_vector_int_reverse(*args, **kwargs):
  return __block.gsl_vector_int_reverse(*args, **kwargs)
gsl_vector_int_reverse = __block.gsl_vector_int_reverse

def gsl_vector_int_swap(*args, **kwargs):
  return __block.gsl_vector_int_swap(*args, **kwargs)
gsl_vector_int_swap = __block.gsl_vector_int_swap

def gsl_vector_int_swap_elements(*args, **kwargs):
  return __block.gsl_vector_int_swap_elements(*args, **kwargs)
gsl_vector_int_swap_elements = __block.gsl_vector_int_swap_elements

def gsl_vector_int_max(*args, **kwargs):
  return __block.gsl_vector_int_max(*args, **kwargs)
gsl_vector_int_max = __block.gsl_vector_int_max

def gsl_vector_int_min(*args, **kwargs):
  return __block.gsl_vector_int_min(*args, **kwargs)
gsl_vector_int_min = __block.gsl_vector_int_min

def gsl_vector_int_minmax(*args, **kwargs):
  return __block.gsl_vector_int_minmax(*args, **kwargs)
gsl_vector_int_minmax = __block.gsl_vector_int_minmax

def gsl_vector_int_max_index(*args, **kwargs):
  return __block.gsl_vector_int_max_index(*args, **kwargs)
gsl_vector_int_max_index = __block.gsl_vector_int_max_index

def gsl_vector_int_min_index(*args, **kwargs):
  return __block.gsl_vector_int_min_index(*args, **kwargs)
gsl_vector_int_min_index = __block.gsl_vector_int_min_index

def gsl_vector_int_minmax_index(*args, **kwargs):
  return __block.gsl_vector_int_minmax_index(*args, **kwargs)
gsl_vector_int_minmax_index = __block.gsl_vector_int_minmax_index

def gsl_vector_int_isnull(*args, **kwargs):
  return __block.gsl_vector_int_isnull(*args, **kwargs)
gsl_vector_int_isnull = __block.gsl_vector_int_isnull

def gsl_matrix_int_set_zero(*args, **kwargs):
  return __block.gsl_matrix_int_set_zero(*args, **kwargs)
gsl_matrix_int_set_zero = __block.gsl_matrix_int_set_zero

def gsl_matrix_int_set_all(*args, **kwargs):
  return __block.gsl_matrix_int_set_all(*args, **kwargs)
gsl_matrix_int_set_all = __block.gsl_matrix_int_set_all

def gsl_matrix_int_set_identity(*args, **kwargs):
  return __block.gsl_matrix_int_set_identity(*args, **kwargs)
gsl_matrix_int_set_identity = __block.gsl_matrix_int_set_identity

def gsl_matrix_int_fread(*args, **kwargs):
  return __block.gsl_matrix_int_fread(*args, **kwargs)
gsl_matrix_int_fread = __block.gsl_matrix_int_fread

def gsl_matrix_int_fwrite(*args, **kwargs):
  return __block.gsl_matrix_int_fwrite(*args, **kwargs)
gsl_matrix_int_fwrite = __block.gsl_matrix_int_fwrite

def gsl_matrix_int_fscanf(*args, **kwargs):
  return __block.gsl_matrix_int_fscanf(*args, **kwargs)
gsl_matrix_int_fscanf = __block.gsl_matrix_int_fscanf

def gsl_matrix_int_fprintf(*args, **kwargs):
  return __block.gsl_matrix_int_fprintf(*args, **kwargs)
gsl_matrix_int_fprintf = __block.gsl_matrix_int_fprintf

def gsl_matrix_int_swap(*args, **kwargs):
  return __block.gsl_matrix_int_swap(*args, **kwargs)
gsl_matrix_int_swap = __block.gsl_matrix_int_swap

def gsl_matrix_int_swap_rows(*args, **kwargs):
  return __block.gsl_matrix_int_swap_rows(*args, **kwargs)
gsl_matrix_int_swap_rows = __block.gsl_matrix_int_swap_rows

def gsl_matrix_int_swap_columns(*args, **kwargs):
  return __block.gsl_matrix_int_swap_columns(*args, **kwargs)
gsl_matrix_int_swap_columns = __block.gsl_matrix_int_swap_columns

def gsl_matrix_int_swap_rowcol(*args, **kwargs):
  return __block.gsl_matrix_int_swap_rowcol(*args, **kwargs)
gsl_matrix_int_swap_rowcol = __block.gsl_matrix_int_swap_rowcol

def gsl_matrix_int_transpose(*args, **kwargs):
  return __block.gsl_matrix_int_transpose(*args, **kwargs)
gsl_matrix_int_transpose = __block.gsl_matrix_int_transpose

def gsl_matrix_int_max(*args, **kwargs):
  return __block.gsl_matrix_int_max(*args, **kwargs)
gsl_matrix_int_max = __block.gsl_matrix_int_max

def gsl_matrix_int_min(*args, **kwargs):
  return __block.gsl_matrix_int_min(*args, **kwargs)
gsl_matrix_int_min = __block.gsl_matrix_int_min

def gsl_matrix_int_minmax(*args, **kwargs):
  return __block.gsl_matrix_int_minmax(*args, **kwargs)
gsl_matrix_int_minmax = __block.gsl_matrix_int_minmax

def gsl_matrix_int_max_index(*args, **kwargs):
  return __block.gsl_matrix_int_max_index(*args, **kwargs)
gsl_matrix_int_max_index = __block.gsl_matrix_int_max_index

def gsl_matrix_int_min_index(*args, **kwargs):
  return __block.gsl_matrix_int_min_index(*args, **kwargs)
gsl_matrix_int_min_index = __block.gsl_matrix_int_min_index

def gsl_matrix_int_minmax_index(*args, **kwargs):
  return __block.gsl_matrix_int_minmax_index(*args, **kwargs)
gsl_matrix_int_minmax_index = __block.gsl_matrix_int_minmax_index

def gsl_matrix_int_isnull(*args, **kwargs):
  return __block.gsl_matrix_int_isnull(*args, **kwargs)
gsl_matrix_int_isnull = __block.gsl_matrix_int_isnull

def gsl_matrix_int_diagonal(*args, **kwargs):
  return __block.gsl_matrix_int_diagonal(*args, **kwargs)
gsl_matrix_int_diagonal = __block.gsl_matrix_int_diagonal

def gsl_matrix_int_subdiagonal(*args, **kwargs):
  return __block.gsl_matrix_int_subdiagonal(*args, **kwargs)
gsl_matrix_int_subdiagonal = __block.gsl_matrix_int_subdiagonal

def gsl_matrix_int_superdiagonal(*args, **kwargs):
  return __block.gsl_matrix_int_superdiagonal(*args, **kwargs)
gsl_matrix_int_superdiagonal = __block.gsl_matrix_int_superdiagonal

def gsl_vector_short_set_zero(*args, **kwargs):
  return __block.gsl_vector_short_set_zero(*args, **kwargs)
gsl_vector_short_set_zero = __block.gsl_vector_short_set_zero

def gsl_vector_short_set_all(*args, **kwargs):
  return __block.gsl_vector_short_set_all(*args, **kwargs)
gsl_vector_short_set_all = __block.gsl_vector_short_set_all

def gsl_vector_short_set_basis(*args, **kwargs):
  return __block.gsl_vector_short_set_basis(*args, **kwargs)
gsl_vector_short_set_basis = __block.gsl_vector_short_set_basis

def gsl_vector_short_fread(*args, **kwargs):
  return __block.gsl_vector_short_fread(*args, **kwargs)
gsl_vector_short_fread = __block.gsl_vector_short_fread

def gsl_vector_short_fwrite(*args, **kwargs):
  return __block.gsl_vector_short_fwrite(*args, **kwargs)
gsl_vector_short_fwrite = __block.gsl_vector_short_fwrite

def gsl_vector_short_fscanf(*args, **kwargs):
  return __block.gsl_vector_short_fscanf(*args, **kwargs)
gsl_vector_short_fscanf = __block.gsl_vector_short_fscanf

def gsl_vector_short_fprintf(*args, **kwargs):
  return __block.gsl_vector_short_fprintf(*args, **kwargs)
gsl_vector_short_fprintf = __block.gsl_vector_short_fprintf

def gsl_vector_short_reverse(*args, **kwargs):
  return __block.gsl_vector_short_reverse(*args, **kwargs)
gsl_vector_short_reverse = __block.gsl_vector_short_reverse

def gsl_vector_short_swap(*args, **kwargs):
  return __block.gsl_vector_short_swap(*args, **kwargs)
gsl_vector_short_swap = __block.gsl_vector_short_swap

def gsl_vector_short_swap_elements(*args, **kwargs):
  return __block.gsl_vector_short_swap_elements(*args, **kwargs)
gsl_vector_short_swap_elements = __block.gsl_vector_short_swap_elements

def gsl_vector_short_max(*args, **kwargs):
  return __block.gsl_vector_short_max(*args, **kwargs)
gsl_vector_short_max = __block.gsl_vector_short_max

def gsl_vector_short_min(*args, **kwargs):
  return __block.gsl_vector_short_min(*args, **kwargs)
gsl_vector_short_min = __block.gsl_vector_short_min

def gsl_vector_short_minmax(*args, **kwargs):
  return __block.gsl_vector_short_minmax(*args, **kwargs)
gsl_vector_short_minmax = __block.gsl_vector_short_minmax

def gsl_vector_short_max_index(*args, **kwargs):
  return __block.gsl_vector_short_max_index(*args, **kwargs)
gsl_vector_short_max_index = __block.gsl_vector_short_max_index

def gsl_vector_short_min_index(*args, **kwargs):
  return __block.gsl_vector_short_min_index(*args, **kwargs)
gsl_vector_short_min_index = __block.gsl_vector_short_min_index

def gsl_vector_short_minmax_index(*args, **kwargs):
  return __block.gsl_vector_short_minmax_index(*args, **kwargs)
gsl_vector_short_minmax_index = __block.gsl_vector_short_minmax_index

def gsl_vector_short_isnull(*args, **kwargs):
  return __block.gsl_vector_short_isnull(*args, **kwargs)
gsl_vector_short_isnull = __block.gsl_vector_short_isnull

def gsl_matrix_short_set_zero(*args, **kwargs):
  return __block.gsl_matrix_short_set_zero(*args, **kwargs)
gsl_matrix_short_set_zero = __block.gsl_matrix_short_set_zero

def gsl_matrix_short_set_all(*args, **kwargs):
  return __block.gsl_matrix_short_set_all(*args, **kwargs)
gsl_matrix_short_set_all = __block.gsl_matrix_short_set_all

def gsl_matrix_short_set_identity(*args, **kwargs):
  return __block.gsl_matrix_short_set_identity(*args, **kwargs)
gsl_matrix_short_set_identity = __block.gsl_matrix_short_set_identity

def gsl_matrix_short_fread(*args, **kwargs):
  return __block.gsl_matrix_short_fread(*args, **kwargs)
gsl_matrix_short_fread = __block.gsl_matrix_short_fread

def gsl_matrix_short_fwrite(*args, **kwargs):
  return __block.gsl_matrix_short_fwrite(*args, **kwargs)
gsl_matrix_short_fwrite = __block.gsl_matrix_short_fwrite

def gsl_matrix_short_fscanf(*args, **kwargs):
  return __block.gsl_matrix_short_fscanf(*args, **kwargs)
gsl_matrix_short_fscanf = __block.gsl_matrix_short_fscanf

def gsl_matrix_short_fprintf(*args, **kwargs):
  return __block.gsl_matrix_short_fprintf(*args, **kwargs)
gsl_matrix_short_fprintf = __block.gsl_matrix_short_fprintf

def gsl_matrix_short_swap(*args, **kwargs):
  return __block.gsl_matrix_short_swap(*args, **kwargs)
gsl_matrix_short_swap = __block.gsl_matrix_short_swap

def gsl_matrix_short_swap_rows(*args, **kwargs):
  return __block.gsl_matrix_short_swap_rows(*args, **kwargs)
gsl_matrix_short_swap_rows = __block.gsl_matrix_short_swap_rows

def gsl_matrix_short_swap_columns(*args, **kwargs):
  return __block.gsl_matrix_short_swap_columns(*args, **kwargs)
gsl_matrix_short_swap_columns = __block.gsl_matrix_short_swap_columns

def gsl_matrix_short_swap_rowcol(*args, **kwargs):
  return __block.gsl_matrix_short_swap_rowcol(*args, **kwargs)
gsl_matrix_short_swap_rowcol = __block.gsl_matrix_short_swap_rowcol

def gsl_matrix_short_transpose(*args, **kwargs):
  return __block.gsl_matrix_short_transpose(*args, **kwargs)
gsl_matrix_short_transpose = __block.gsl_matrix_short_transpose

def gsl_matrix_short_max(*args, **kwargs):
  return __block.gsl_matrix_short_max(*args, **kwargs)
gsl_matrix_short_max = __block.gsl_matrix_short_max

def gsl_matrix_short_min(*args, **kwargs):
  return __block.gsl_matrix_short_min(*args, **kwargs)
gsl_matrix_short_min = __block.gsl_matrix_short_min

def gsl_matrix_short_minmax(*args, **kwargs):
  return __block.gsl_matrix_short_minmax(*args, **kwargs)
gsl_matrix_short_minmax = __block.gsl_matrix_short_minmax

def gsl_matrix_short_max_index(*args, **kwargs):
  return __block.gsl_matrix_short_max_index(*args, **kwargs)
gsl_matrix_short_max_index = __block.gsl_matrix_short_max_index

def gsl_matrix_short_min_index(*args, **kwargs):
  return __block.gsl_matrix_short_min_index(*args, **kwargs)
gsl_matrix_short_min_index = __block.gsl_matrix_short_min_index

def gsl_matrix_short_minmax_index(*args, **kwargs):
  return __block.gsl_matrix_short_minmax_index(*args, **kwargs)
gsl_matrix_short_minmax_index = __block.gsl_matrix_short_minmax_index

def gsl_matrix_short_isnull(*args, **kwargs):
  return __block.gsl_matrix_short_isnull(*args, **kwargs)
gsl_matrix_short_isnull = __block.gsl_matrix_short_isnull

def gsl_matrix_short_diagonal(*args, **kwargs):
  return __block.gsl_matrix_short_diagonal(*args, **kwargs)
gsl_matrix_short_diagonal = __block.gsl_matrix_short_diagonal

def gsl_matrix_short_subdiagonal(*args, **kwargs):
  return __block.gsl_matrix_short_subdiagonal(*args, **kwargs)
gsl_matrix_short_subdiagonal = __block.gsl_matrix_short_subdiagonal

def gsl_matrix_short_superdiagonal(*args, **kwargs):
  return __block.gsl_matrix_short_superdiagonal(*args, **kwargs)
gsl_matrix_short_superdiagonal = __block.gsl_matrix_short_superdiagonal

def gsl_vector_char_set_zero(*args, **kwargs):
  return __block.gsl_vector_char_set_zero(*args, **kwargs)
gsl_vector_char_set_zero = __block.gsl_vector_char_set_zero

def gsl_vector_char_set_all(*args, **kwargs):
  return __block.gsl_vector_char_set_all(*args, **kwargs)
gsl_vector_char_set_all = __block.gsl_vector_char_set_all

def gsl_vector_char_set_basis(*args, **kwargs):
  return __block.gsl_vector_char_set_basis(*args, **kwargs)
gsl_vector_char_set_basis = __block.gsl_vector_char_set_basis

def gsl_vector_char_fread(*args, **kwargs):
  return __block.gsl_vector_char_fread(*args, **kwargs)
gsl_vector_char_fread = __block.gsl_vector_char_fread

def gsl_vector_char_fwrite(*args, **kwargs):
  return __block.gsl_vector_char_fwrite(*args, **kwargs)
gsl_vector_char_fwrite = __block.gsl_vector_char_fwrite

def gsl_vector_char_fscanf(*args, **kwargs):
  return __block.gsl_vector_char_fscanf(*args, **kwargs)
gsl_vector_char_fscanf = __block.gsl_vector_char_fscanf

def gsl_vector_char_fprintf(*args, **kwargs):
  return __block.gsl_vector_char_fprintf(*args, **kwargs)
gsl_vector_char_fprintf = __block.gsl_vector_char_fprintf

def gsl_vector_char_reverse(*args, **kwargs):
  return __block.gsl_vector_char_reverse(*args, **kwargs)
gsl_vector_char_reverse = __block.gsl_vector_char_reverse

def gsl_vector_char_swap(*args, **kwargs):
  return __block.gsl_vector_char_swap(*args, **kwargs)
gsl_vector_char_swap = __block.gsl_vector_char_swap

def gsl_vector_char_swap_elements(*args, **kwargs):
  return __block.gsl_vector_char_swap_elements(*args, **kwargs)
gsl_vector_char_swap_elements = __block.gsl_vector_char_swap_elements

def gsl_vector_char_max(*args, **kwargs):
  return __block.gsl_vector_char_max(*args, **kwargs)
gsl_vector_char_max = __block.gsl_vector_char_max

def gsl_vector_char_min(*args, **kwargs):
  return __block.gsl_vector_char_min(*args, **kwargs)
gsl_vector_char_min = __block.gsl_vector_char_min

def gsl_vector_char_minmax(*args, **kwargs):
  return __block.gsl_vector_char_minmax(*args, **kwargs)
gsl_vector_char_minmax = __block.gsl_vector_char_minmax

def gsl_vector_char_max_index(*args, **kwargs):
  return __block.gsl_vector_char_max_index(*args, **kwargs)
gsl_vector_char_max_index = __block.gsl_vector_char_max_index

def gsl_vector_char_min_index(*args, **kwargs):
  return __block.gsl_vector_char_min_index(*args, **kwargs)
gsl_vector_char_min_index = __block.gsl_vector_char_min_index

def gsl_vector_char_minmax_index(*args, **kwargs):
  return __block.gsl_vector_char_minmax_index(*args, **kwargs)
gsl_vector_char_minmax_index = __block.gsl_vector_char_minmax_index

def gsl_vector_char_isnull(*args, **kwargs):
  return __block.gsl_vector_char_isnull(*args, **kwargs)
gsl_vector_char_isnull = __block.gsl_vector_char_isnull

def gsl_matrix_char_set_zero(*args, **kwargs):
  return __block.gsl_matrix_char_set_zero(*args, **kwargs)
gsl_matrix_char_set_zero = __block.gsl_matrix_char_set_zero

def gsl_matrix_char_set_all(*args, **kwargs):
  return __block.gsl_matrix_char_set_all(*args, **kwargs)
gsl_matrix_char_set_all = __block.gsl_matrix_char_set_all

def gsl_matrix_char_set_identity(*args, **kwargs):
  return __block.gsl_matrix_char_set_identity(*args, **kwargs)
gsl_matrix_char_set_identity = __block.gsl_matrix_char_set_identity

def gsl_matrix_char_fread(*args, **kwargs):
  return __block.gsl_matrix_char_fread(*args, **kwargs)
gsl_matrix_char_fread = __block.gsl_matrix_char_fread

def gsl_matrix_char_fwrite(*args, **kwargs):
  return __block.gsl_matrix_char_fwrite(*args, **kwargs)
gsl_matrix_char_fwrite = __block.gsl_matrix_char_fwrite

def gsl_matrix_char_fscanf(*args, **kwargs):
  return __block.gsl_matrix_char_fscanf(*args, **kwargs)
gsl_matrix_char_fscanf = __block.gsl_matrix_char_fscanf

def gsl_matrix_char_fprintf(*args, **kwargs):
  return __block.gsl_matrix_char_fprintf(*args, **kwargs)
gsl_matrix_char_fprintf = __block.gsl_matrix_char_fprintf

def gsl_matrix_char_swap(*args, **kwargs):
  return __block.gsl_matrix_char_swap(*args, **kwargs)
gsl_matrix_char_swap = __block.gsl_matrix_char_swap

def gsl_matrix_char_swap_rows(*args, **kwargs):
  return __block.gsl_matrix_char_swap_rows(*args, **kwargs)
gsl_matrix_char_swap_rows = __block.gsl_matrix_char_swap_rows

def gsl_matrix_char_swap_columns(*args, **kwargs):
  return __block.gsl_matrix_char_swap_columns(*args, **kwargs)
gsl_matrix_char_swap_columns = __block.gsl_matrix_char_swap_columns

def gsl_matrix_char_swap_rowcol(*args, **kwargs):
  return __block.gsl_matrix_char_swap_rowcol(*args, **kwargs)
gsl_matrix_char_swap_rowcol = __block.gsl_matrix_char_swap_rowcol

def gsl_matrix_char_transpose(*args, **kwargs):
  return __block.gsl_matrix_char_transpose(*args, **kwargs)
gsl_matrix_char_transpose = __block.gsl_matrix_char_transpose

def gsl_matrix_char_max(*args, **kwargs):
  return __block.gsl_matrix_char_max(*args, **kwargs)
gsl_matrix_char_max = __block.gsl_matrix_char_max

def gsl_matrix_char_min(*args, **kwargs):
  return __block.gsl_matrix_char_min(*args, **kwargs)
gsl_matrix_char_min = __block.gsl_matrix_char_min

def gsl_matrix_char_minmax(*args, **kwargs):
  return __block.gsl_matrix_char_minmax(*args, **kwargs)
gsl_matrix_char_minmax = __block.gsl_matrix_char_minmax

def gsl_matrix_char_max_index(*args, **kwargs):
  return __block.gsl_matrix_char_max_index(*args, **kwargs)
gsl_matrix_char_max_index = __block.gsl_matrix_char_max_index

def gsl_matrix_char_min_index(*args, **kwargs):
  return __block.gsl_matrix_char_min_index(*args, **kwargs)
gsl_matrix_char_min_index = __block.gsl_matrix_char_min_index

def gsl_matrix_char_minmax_index(*args, **kwargs):
  return __block.gsl_matrix_char_minmax_index(*args, **kwargs)
gsl_matrix_char_minmax_index = __block.gsl_matrix_char_minmax_index

def gsl_matrix_char_isnull(*args, **kwargs):
  return __block.gsl_matrix_char_isnull(*args, **kwargs)
gsl_matrix_char_isnull = __block.gsl_matrix_char_isnull

def gsl_matrix_char_diagonal(*args, **kwargs):
  return __block.gsl_matrix_char_diagonal(*args, **kwargs)
gsl_matrix_char_diagonal = __block.gsl_matrix_char_diagonal

def gsl_matrix_char_subdiagonal(*args, **kwargs):
  return __block.gsl_matrix_char_subdiagonal(*args, **kwargs)
gsl_matrix_char_subdiagonal = __block.gsl_matrix_char_subdiagonal

def gsl_matrix_char_superdiagonal(*args, **kwargs):
  return __block.gsl_matrix_char_superdiagonal(*args, **kwargs)
gsl_matrix_char_superdiagonal = __block.gsl_matrix_char_superdiagonal

def gsl_vector_complex_set_zero(*args, **kwargs):
  return __block.gsl_vector_complex_set_zero(*args, **kwargs)
gsl_vector_complex_set_zero = __block.gsl_vector_complex_set_zero

def gsl_vector_complex_set_all(*args, **kwargs):
  return __block.gsl_vector_complex_set_all(*args, **kwargs)
gsl_vector_complex_set_all = __block.gsl_vector_complex_set_all

def gsl_vector_complex_set_basis(*args, **kwargs):
  return __block.gsl_vector_complex_set_basis(*args, **kwargs)
gsl_vector_complex_set_basis = __block.gsl_vector_complex_set_basis

def gsl_vector_complex_fread(*args, **kwargs):
  return __block.gsl_vector_complex_fread(*args, **kwargs)
gsl_vector_complex_fread = __block.gsl_vector_complex_fread

def gsl_vector_complex_fwrite(*args, **kwargs):
  return __block.gsl_vector_complex_fwrite(*args, **kwargs)
gsl_vector_complex_fwrite = __block.gsl_vector_complex_fwrite

def gsl_vector_complex_fscanf(*args, **kwargs):
  return __block.gsl_vector_complex_fscanf(*args, **kwargs)
gsl_vector_complex_fscanf = __block.gsl_vector_complex_fscanf

def gsl_vector_complex_fprintf(*args, **kwargs):
  return __block.gsl_vector_complex_fprintf(*args, **kwargs)
gsl_vector_complex_fprintf = __block.gsl_vector_complex_fprintf

def gsl_vector_complex_reverse(*args, **kwargs):
  return __block.gsl_vector_complex_reverse(*args, **kwargs)
gsl_vector_complex_reverse = __block.gsl_vector_complex_reverse

def gsl_vector_complex_swap(*args, **kwargs):
  return __block.gsl_vector_complex_swap(*args, **kwargs)
gsl_vector_complex_swap = __block.gsl_vector_complex_swap

def gsl_vector_complex_swap_elements(*args, **kwargs):
  return __block.gsl_vector_complex_swap_elements(*args, **kwargs)
gsl_vector_complex_swap_elements = __block.gsl_vector_complex_swap_elements

def gsl_vector_complex_isnull(*args, **kwargs):
  return __block.gsl_vector_complex_isnull(*args, **kwargs)
gsl_vector_complex_isnull = __block.gsl_vector_complex_isnull

def gsl_matrix_complex_set_zero(*args, **kwargs):
  return __block.gsl_matrix_complex_set_zero(*args, **kwargs)
gsl_matrix_complex_set_zero = __block.gsl_matrix_complex_set_zero

def gsl_matrix_complex_set_all(*args, **kwargs):
  return __block.gsl_matrix_complex_set_all(*args, **kwargs)
gsl_matrix_complex_set_all = __block.gsl_matrix_complex_set_all

def gsl_matrix_complex_set_identity(*args, **kwargs):
  return __block.gsl_matrix_complex_set_identity(*args, **kwargs)
gsl_matrix_complex_set_identity = __block.gsl_matrix_complex_set_identity

def gsl_matrix_complex_fread(*args, **kwargs):
  return __block.gsl_matrix_complex_fread(*args, **kwargs)
gsl_matrix_complex_fread = __block.gsl_matrix_complex_fread

def gsl_matrix_complex_fwrite(*args, **kwargs):
  return __block.gsl_matrix_complex_fwrite(*args, **kwargs)
gsl_matrix_complex_fwrite = __block.gsl_matrix_complex_fwrite

def gsl_matrix_complex_fscanf(*args, **kwargs):
  return __block.gsl_matrix_complex_fscanf(*args, **kwargs)
gsl_matrix_complex_fscanf = __block.gsl_matrix_complex_fscanf

def gsl_matrix_complex_fprintf(*args, **kwargs):
  return __block.gsl_matrix_complex_fprintf(*args, **kwargs)
gsl_matrix_complex_fprintf = __block.gsl_matrix_complex_fprintf

def gsl_matrix_complex_swap(*args, **kwargs):
  return __block.gsl_matrix_complex_swap(*args, **kwargs)
gsl_matrix_complex_swap = __block.gsl_matrix_complex_swap

def gsl_matrix_complex_swap_rows(*args, **kwargs):
  return __block.gsl_matrix_complex_swap_rows(*args, **kwargs)
gsl_matrix_complex_swap_rows = __block.gsl_matrix_complex_swap_rows

def gsl_matrix_complex_swap_columns(*args, **kwargs):
  return __block.gsl_matrix_complex_swap_columns(*args, **kwargs)
gsl_matrix_complex_swap_columns = __block.gsl_matrix_complex_swap_columns

def gsl_matrix_complex_swap_rowcol(*args, **kwargs):
  return __block.gsl_matrix_complex_swap_rowcol(*args, **kwargs)
gsl_matrix_complex_swap_rowcol = __block.gsl_matrix_complex_swap_rowcol

def gsl_matrix_complex_transpose(*args, **kwargs):
  return __block.gsl_matrix_complex_transpose(*args, **kwargs)
gsl_matrix_complex_transpose = __block.gsl_matrix_complex_transpose

def gsl_matrix_complex_isnull(*args, **kwargs):
  return __block.gsl_matrix_complex_isnull(*args, **kwargs)
gsl_matrix_complex_isnull = __block.gsl_matrix_complex_isnull

def gsl_matrix_complex_diagonal(*args, **kwargs):
  return __block.gsl_matrix_complex_diagonal(*args, **kwargs)
gsl_matrix_complex_diagonal = __block.gsl_matrix_complex_diagonal

def gsl_matrix_complex_subdiagonal(*args, **kwargs):
  return __block.gsl_matrix_complex_subdiagonal(*args, **kwargs)
gsl_matrix_complex_subdiagonal = __block.gsl_matrix_complex_subdiagonal

def gsl_matrix_complex_superdiagonal(*args, **kwargs):
  return __block.gsl_matrix_complex_superdiagonal(*args, **kwargs)
gsl_matrix_complex_superdiagonal = __block.gsl_matrix_complex_superdiagonal

def gsl_vector_complex_float_set_zero(*args, **kwargs):
  return __block.gsl_vector_complex_float_set_zero(*args, **kwargs)
gsl_vector_complex_float_set_zero = __block.gsl_vector_complex_float_set_zero

def gsl_vector_complex_float_set_all(*args, **kwargs):
  return __block.gsl_vector_complex_float_set_all(*args, **kwargs)
gsl_vector_complex_float_set_all = __block.gsl_vector_complex_float_set_all

def gsl_vector_complex_float_set_basis(*args, **kwargs):
  return __block.gsl_vector_complex_float_set_basis(*args, **kwargs)
gsl_vector_complex_float_set_basis = __block.gsl_vector_complex_float_set_basis

def gsl_vector_complex_float_fread(*args, **kwargs):
  return __block.gsl_vector_complex_float_fread(*args, **kwargs)
gsl_vector_complex_float_fread = __block.gsl_vector_complex_float_fread

def gsl_vector_complex_float_fwrite(*args, **kwargs):
  return __block.gsl_vector_complex_float_fwrite(*args, **kwargs)
gsl_vector_complex_float_fwrite = __block.gsl_vector_complex_float_fwrite

def gsl_vector_complex_float_fscanf(*args, **kwargs):
  return __block.gsl_vector_complex_float_fscanf(*args, **kwargs)
gsl_vector_complex_float_fscanf = __block.gsl_vector_complex_float_fscanf

def gsl_vector_complex_float_fprintf(*args, **kwargs):
  return __block.gsl_vector_complex_float_fprintf(*args, **kwargs)
gsl_vector_complex_float_fprintf = __block.gsl_vector_complex_float_fprintf

def gsl_vector_complex_float_reverse(*args, **kwargs):
  return __block.gsl_vector_complex_float_reverse(*args, **kwargs)
gsl_vector_complex_float_reverse = __block.gsl_vector_complex_float_reverse

def gsl_vector_complex_float_swap(*args, **kwargs):
  return __block.gsl_vector_complex_float_swap(*args, **kwargs)
gsl_vector_complex_float_swap = __block.gsl_vector_complex_float_swap

def gsl_vector_complex_float_swap_elements(*args, **kwargs):
  return __block.gsl_vector_complex_float_swap_elements(*args, **kwargs)
gsl_vector_complex_float_swap_elements = __block.gsl_vector_complex_float_swap_elements

def gsl_vector_complex_float_isnull(*args, **kwargs):
  return __block.gsl_vector_complex_float_isnull(*args, **kwargs)
gsl_vector_complex_float_isnull = __block.gsl_vector_complex_float_isnull

def gsl_matrix_complex_float_set_zero(*args, **kwargs):
  return __block.gsl_matrix_complex_float_set_zero(*args, **kwargs)
gsl_matrix_complex_float_set_zero = __block.gsl_matrix_complex_float_set_zero

def gsl_matrix_complex_float_set_all(*args, **kwargs):
  return __block.gsl_matrix_complex_float_set_all(*args, **kwargs)
gsl_matrix_complex_float_set_all = __block.gsl_matrix_complex_float_set_all

def gsl_matrix_complex_float_set_identity(*args, **kwargs):
  return __block.gsl_matrix_complex_float_set_identity(*args, **kwargs)
gsl_matrix_complex_float_set_identity = __block.gsl_matrix_complex_float_set_identity

def gsl_matrix_complex_float_fread(*args, **kwargs):
  return __block.gsl_matrix_complex_float_fread(*args, **kwargs)
gsl_matrix_complex_float_fread = __block.gsl_matrix_complex_float_fread

def gsl_matrix_complex_float_fwrite(*args, **kwargs):
  return __block.gsl_matrix_complex_float_fwrite(*args, **kwargs)
gsl_matrix_complex_float_fwrite = __block.gsl_matrix_complex_float_fwrite

def gsl_matrix_complex_float_fscanf(*args, **kwargs):
  return __block.gsl_matrix_complex_float_fscanf(*args, **kwargs)
gsl_matrix_complex_float_fscanf = __block.gsl_matrix_complex_float_fscanf

def gsl_matrix_complex_float_fprintf(*args, **kwargs):
  return __block.gsl_matrix_complex_float_fprintf(*args, **kwargs)
gsl_matrix_complex_float_fprintf = __block.gsl_matrix_complex_float_fprintf

def gsl_matrix_complex_float_swap(*args, **kwargs):
  return __block.gsl_matrix_complex_float_swap(*args, **kwargs)
gsl_matrix_complex_float_swap = __block.gsl_matrix_complex_float_swap

def gsl_matrix_complex_float_swap_rows(*args, **kwargs):
  return __block.gsl_matrix_complex_float_swap_rows(*args, **kwargs)
gsl_matrix_complex_float_swap_rows = __block.gsl_matrix_complex_float_swap_rows

def gsl_matrix_complex_float_swap_columns(*args, **kwargs):
  return __block.gsl_matrix_complex_float_swap_columns(*args, **kwargs)
gsl_matrix_complex_float_swap_columns = __block.gsl_matrix_complex_float_swap_columns

def gsl_matrix_complex_float_swap_rowcol(*args, **kwargs):
  return __block.gsl_matrix_complex_float_swap_rowcol(*args, **kwargs)
gsl_matrix_complex_float_swap_rowcol = __block.gsl_matrix_complex_float_swap_rowcol

def gsl_matrix_complex_float_transpose(*args, **kwargs):
  return __block.gsl_matrix_complex_float_transpose(*args, **kwargs)
gsl_matrix_complex_float_transpose = __block.gsl_matrix_complex_float_transpose

def gsl_matrix_complex_float_isnull(*args, **kwargs):
  return __block.gsl_matrix_complex_float_isnull(*args, **kwargs)
gsl_matrix_complex_float_isnull = __block.gsl_matrix_complex_float_isnull

def gsl_matrix_complex_float_diagonal(*args, **kwargs):
  return __block.gsl_matrix_complex_float_diagonal(*args, **kwargs)
gsl_matrix_complex_float_diagonal = __block.gsl_matrix_complex_float_diagonal

def gsl_matrix_complex_float_subdiagonal(*args, **kwargs):
  return __block.gsl_matrix_complex_float_subdiagonal(*args, **kwargs)
gsl_matrix_complex_float_subdiagonal = __block.gsl_matrix_complex_float_subdiagonal

def gsl_matrix_complex_float_superdiagonal(*args, **kwargs):
  return __block.gsl_matrix_complex_float_superdiagonal(*args, **kwargs)
gsl_matrix_complex_float_superdiagonal = __block.gsl_matrix_complex_float_superdiagonal
# This file is compatible with both classic and new-style classes.


