#!/usr/bin/env python
# Author : Pierre Schnizer

import sys
import re
import string

match = re.compile('TYPE')
header = """/* -*- C -*- */
/*
    Automatic generated SWIG File.

    This file was automatically generated by """ + sys.argv[0] + """ using
    the template 'gsl_block_generic_typed.i'.

    Apply all changes to these two files!
*/    
"""    
def run():
    for i in ('char', 'short', 'int', 'long', 'float', 'double',
              'complex_float', 'complex'):
        file = open('gsl_block_generic_typed.i')
        text = string.join(file.readlines(), '')
        file.close()
        text1 = match.sub(i, text)
        file = open('/tmp/gsl_block_'+ i + '.i', 'w')
        file.write(header)
        file.write(text1)
        file.close()
if __name__ == '__main__':
    run()
