# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.12
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info >= (2, 7, 0):
    def swig_import_helper():
        import importlib
        pkg = __name__.rpartition('.')[0]
        mname = '.'.join((pkg, '_sf')).lstrip('.')
        try:
            return importlib.import_module(mname)
        except ImportError:
            return importlib.import_module('_sf')
    _sf = swig_import_helper()
    del swig_import_helper
elif _swig_python_version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_sf', [dirname(__file__)])
        except ImportError:
            import _sf
            return _sf
        try:
            _mod = imp.load_module('_sf', fp, pathname, description)
        finally:
            if fp is not None:
                fp.close()
        return _mod
    _sf = swig_import_helper()
    del swig_import_helper
else:
    import _sf
del _swig_python_version_info

try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr(self, class_type, name):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except __builtin__.Exception:
    class _object:
        pass
    _newclass = 0

class gsl_sf_result_struct(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, gsl_sf_result_struct, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, gsl_sf_result_struct, name)
    __repr__ = _swig_repr
    __swig_setmethods__["val"] = _sf.gsl_sf_result_struct_val_set
    __swig_getmethods__["val"] = _sf.gsl_sf_result_struct_val_get
    if _newclass:
        val = _swig_property(_sf.gsl_sf_result_struct_val_get, _sf.gsl_sf_result_struct_val_set)
    __swig_setmethods__["err"] = _sf.gsl_sf_result_struct_err_set
    __swig_getmethods__["err"] = _sf.gsl_sf_result_struct_err_get
    if _newclass:
        err = _swig_property(_sf.gsl_sf_result_struct_err_get, _sf.gsl_sf_result_struct_err_set)

    def __init__(self):
        this = _sf.new_gsl_sf_result_struct()
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _sf.delete_gsl_sf_result_struct
    __del__ = lambda self: None
gsl_sf_result_struct_swigregister = _sf.gsl_sf_result_struct_swigregister
gsl_sf_result_struct_swigregister(gsl_sf_result_struct)

class gsl_sf_result_e10_struct(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, gsl_sf_result_e10_struct, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, gsl_sf_result_e10_struct, name)
    __repr__ = _swig_repr
    __swig_setmethods__["val"] = _sf.gsl_sf_result_e10_struct_val_set
    __swig_getmethods__["val"] = _sf.gsl_sf_result_e10_struct_val_get
    if _newclass:
        val = _swig_property(_sf.gsl_sf_result_e10_struct_val_get, _sf.gsl_sf_result_e10_struct_val_set)
    __swig_setmethods__["err"] = _sf.gsl_sf_result_e10_struct_err_set
    __swig_getmethods__["err"] = _sf.gsl_sf_result_e10_struct_err_get
    if _newclass:
        err = _swig_property(_sf.gsl_sf_result_e10_struct_err_get, _sf.gsl_sf_result_e10_struct_err_set)
    __swig_setmethods__["e10"] = _sf.gsl_sf_result_e10_struct_e10_set
    __swig_getmethods__["e10"] = _sf.gsl_sf_result_e10_struct_e10_get
    if _newclass:
        e10 = _swig_property(_sf.gsl_sf_result_e10_struct_e10_get, _sf.gsl_sf_result_e10_struct_e10_set)

    def __init__(self):
        this = _sf.new_gsl_sf_result_e10_struct()
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _sf.delete_gsl_sf_result_e10_struct
    __del__ = lambda self: None
gsl_sf_result_e10_struct_swigregister = _sf.gsl_sf_result_e10_struct_swigregister
gsl_sf_result_e10_struct_swigregister(gsl_sf_result_e10_struct)


def gsl_sf_airy_Ai_e(x, mode, result):
    return _sf.gsl_sf_airy_Ai_e(x, mode, result)
gsl_sf_airy_Ai_e = _sf.gsl_sf_airy_Ai_e

def gsl_sf_airy_Ai(x, mode):
    return _sf.gsl_sf_airy_Ai(x, mode)
gsl_sf_airy_Ai = _sf.gsl_sf_airy_Ai

def gsl_sf_airy_Bi_e(x, mode, result):
    return _sf.gsl_sf_airy_Bi_e(x, mode, result)
gsl_sf_airy_Bi_e = _sf.gsl_sf_airy_Bi_e

def gsl_sf_airy_Bi(x, mode):
    return _sf.gsl_sf_airy_Bi(x, mode)
gsl_sf_airy_Bi = _sf.gsl_sf_airy_Bi

def gsl_sf_airy_Ai_scaled_e(x, mode, result):
    return _sf.gsl_sf_airy_Ai_scaled_e(x, mode, result)
gsl_sf_airy_Ai_scaled_e = _sf.gsl_sf_airy_Ai_scaled_e

def gsl_sf_airy_Ai_scaled(x, mode):
    return _sf.gsl_sf_airy_Ai_scaled(x, mode)
gsl_sf_airy_Ai_scaled = _sf.gsl_sf_airy_Ai_scaled

def gsl_sf_airy_Bi_scaled_e(x, mode, result):
    return _sf.gsl_sf_airy_Bi_scaled_e(x, mode, result)
gsl_sf_airy_Bi_scaled_e = _sf.gsl_sf_airy_Bi_scaled_e

def gsl_sf_airy_Bi_scaled(x, mode):
    return _sf.gsl_sf_airy_Bi_scaled(x, mode)
gsl_sf_airy_Bi_scaled = _sf.gsl_sf_airy_Bi_scaled

def gsl_sf_airy_Ai_deriv_e(x, mode, result):
    return _sf.gsl_sf_airy_Ai_deriv_e(x, mode, result)
gsl_sf_airy_Ai_deriv_e = _sf.gsl_sf_airy_Ai_deriv_e

def gsl_sf_airy_Ai_deriv(x, mode):
    return _sf.gsl_sf_airy_Ai_deriv(x, mode)
gsl_sf_airy_Ai_deriv = _sf.gsl_sf_airy_Ai_deriv

def gsl_sf_airy_Bi_deriv_e(x, mode, result):
    return _sf.gsl_sf_airy_Bi_deriv_e(x, mode, result)
gsl_sf_airy_Bi_deriv_e = _sf.gsl_sf_airy_Bi_deriv_e

def gsl_sf_airy_Bi_deriv(x, mode):
    return _sf.gsl_sf_airy_Bi_deriv(x, mode)
gsl_sf_airy_Bi_deriv = _sf.gsl_sf_airy_Bi_deriv

def gsl_sf_airy_Ai_deriv_scaled_e(x, mode, result):
    return _sf.gsl_sf_airy_Ai_deriv_scaled_e(x, mode, result)
gsl_sf_airy_Ai_deriv_scaled_e = _sf.gsl_sf_airy_Ai_deriv_scaled_e

def gsl_sf_airy_Ai_deriv_scaled(x, mode):
    return _sf.gsl_sf_airy_Ai_deriv_scaled(x, mode)
gsl_sf_airy_Ai_deriv_scaled = _sf.gsl_sf_airy_Ai_deriv_scaled

def gsl_sf_airy_Bi_deriv_scaled_e(x, mode, result):
    return _sf.gsl_sf_airy_Bi_deriv_scaled_e(x, mode, result)
gsl_sf_airy_Bi_deriv_scaled_e = _sf.gsl_sf_airy_Bi_deriv_scaled_e

def gsl_sf_airy_Bi_deriv_scaled(x, mode):
    return _sf.gsl_sf_airy_Bi_deriv_scaled(x, mode)
gsl_sf_airy_Bi_deriv_scaled = _sf.gsl_sf_airy_Bi_deriv_scaled

def gsl_sf_airy_zero_Ai_e(s, result):
    return _sf.gsl_sf_airy_zero_Ai_e(s, result)
gsl_sf_airy_zero_Ai_e = _sf.gsl_sf_airy_zero_Ai_e

def gsl_sf_airy_zero_Ai(s):
    return _sf.gsl_sf_airy_zero_Ai(s)
gsl_sf_airy_zero_Ai = _sf.gsl_sf_airy_zero_Ai

def gsl_sf_airy_zero_Bi_e(s, result):
    return _sf.gsl_sf_airy_zero_Bi_e(s, result)
gsl_sf_airy_zero_Bi_e = _sf.gsl_sf_airy_zero_Bi_e

def gsl_sf_airy_zero_Bi(s):
    return _sf.gsl_sf_airy_zero_Bi(s)
gsl_sf_airy_zero_Bi = _sf.gsl_sf_airy_zero_Bi

def gsl_sf_airy_zero_Ai_deriv_e(s, result):
    return _sf.gsl_sf_airy_zero_Ai_deriv_e(s, result)
gsl_sf_airy_zero_Ai_deriv_e = _sf.gsl_sf_airy_zero_Ai_deriv_e

def gsl_sf_airy_zero_Ai_deriv(s):
    return _sf.gsl_sf_airy_zero_Ai_deriv(s)
gsl_sf_airy_zero_Ai_deriv = _sf.gsl_sf_airy_zero_Ai_deriv

def gsl_sf_airy_zero_Bi_deriv_e(s, result):
    return _sf.gsl_sf_airy_zero_Bi_deriv_e(s, result)
gsl_sf_airy_zero_Bi_deriv_e = _sf.gsl_sf_airy_zero_Bi_deriv_e

def gsl_sf_airy_zero_Bi_deriv(s):
    return _sf.gsl_sf_airy_zero_Bi_deriv(s)
gsl_sf_airy_zero_Bi_deriv = _sf.gsl_sf_airy_zero_Bi_deriv

def gsl_sf_bessel_J0_e(x, result):
    return _sf.gsl_sf_bessel_J0_e(x, result)
gsl_sf_bessel_J0_e = _sf.gsl_sf_bessel_J0_e

def gsl_sf_bessel_J0(x):
    return _sf.gsl_sf_bessel_J0(x)
gsl_sf_bessel_J0 = _sf.gsl_sf_bessel_J0

def gsl_sf_bessel_J1_e(x, result):
    return _sf.gsl_sf_bessel_J1_e(x, result)
gsl_sf_bessel_J1_e = _sf.gsl_sf_bessel_J1_e

def gsl_sf_bessel_J1(x):
    return _sf.gsl_sf_bessel_J1(x)
gsl_sf_bessel_J1 = _sf.gsl_sf_bessel_J1

def gsl_sf_bessel_Jn_e(n, x, result):
    return _sf.gsl_sf_bessel_Jn_e(n, x, result)
gsl_sf_bessel_Jn_e = _sf.gsl_sf_bessel_Jn_e

def gsl_sf_bessel_Jn(n, x):
    return _sf.gsl_sf_bessel_Jn(n, x)
gsl_sf_bessel_Jn = _sf.gsl_sf_bessel_Jn

def gsl_sf_bessel_Y0_e(x, result):
    return _sf.gsl_sf_bessel_Y0_e(x, result)
gsl_sf_bessel_Y0_e = _sf.gsl_sf_bessel_Y0_e

def gsl_sf_bessel_Y0(x):
    return _sf.gsl_sf_bessel_Y0(x)
gsl_sf_bessel_Y0 = _sf.gsl_sf_bessel_Y0

def gsl_sf_bessel_Y1_e(x, result):
    return _sf.gsl_sf_bessel_Y1_e(x, result)
gsl_sf_bessel_Y1_e = _sf.gsl_sf_bessel_Y1_e

def gsl_sf_bessel_Y1(x):
    return _sf.gsl_sf_bessel_Y1(x)
gsl_sf_bessel_Y1 = _sf.gsl_sf_bessel_Y1

def gsl_sf_bessel_Yn_e(n, x, result):
    return _sf.gsl_sf_bessel_Yn_e(n, x, result)
gsl_sf_bessel_Yn_e = _sf.gsl_sf_bessel_Yn_e

def gsl_sf_bessel_Yn(n, x):
    return _sf.gsl_sf_bessel_Yn(n, x)
gsl_sf_bessel_Yn = _sf.gsl_sf_bessel_Yn

def gsl_sf_bessel_I0_e(x, result):
    return _sf.gsl_sf_bessel_I0_e(x, result)
gsl_sf_bessel_I0_e = _sf.gsl_sf_bessel_I0_e

def gsl_sf_bessel_I0(x):
    return _sf.gsl_sf_bessel_I0(x)
gsl_sf_bessel_I0 = _sf.gsl_sf_bessel_I0

def gsl_sf_bessel_I1_e(x, result):
    return _sf.gsl_sf_bessel_I1_e(x, result)
gsl_sf_bessel_I1_e = _sf.gsl_sf_bessel_I1_e

def gsl_sf_bessel_I1(x):
    return _sf.gsl_sf_bessel_I1(x)
gsl_sf_bessel_I1 = _sf.gsl_sf_bessel_I1

def gsl_sf_bessel_In_e(n, x, result):
    return _sf.gsl_sf_bessel_In_e(n, x, result)
gsl_sf_bessel_In_e = _sf.gsl_sf_bessel_In_e

def gsl_sf_bessel_In(n, x):
    return _sf.gsl_sf_bessel_In(n, x)
gsl_sf_bessel_In = _sf.gsl_sf_bessel_In

def gsl_sf_bessel_I0_scaled_e(x, result):
    return _sf.gsl_sf_bessel_I0_scaled_e(x, result)
gsl_sf_bessel_I0_scaled_e = _sf.gsl_sf_bessel_I0_scaled_e

def gsl_sf_bessel_I0_scaled(x):
    return _sf.gsl_sf_bessel_I0_scaled(x)
gsl_sf_bessel_I0_scaled = _sf.gsl_sf_bessel_I0_scaled

def gsl_sf_bessel_I1_scaled_e(x, result):
    return _sf.gsl_sf_bessel_I1_scaled_e(x, result)
gsl_sf_bessel_I1_scaled_e = _sf.gsl_sf_bessel_I1_scaled_e

def gsl_sf_bessel_I1_scaled(x):
    return _sf.gsl_sf_bessel_I1_scaled(x)
gsl_sf_bessel_I1_scaled = _sf.gsl_sf_bessel_I1_scaled

def gsl_sf_bessel_In_scaled_e(n, x, result):
    return _sf.gsl_sf_bessel_In_scaled_e(n, x, result)
gsl_sf_bessel_In_scaled_e = _sf.gsl_sf_bessel_In_scaled_e

def gsl_sf_bessel_In_scaled(n, x):
    return _sf.gsl_sf_bessel_In_scaled(n, x)
gsl_sf_bessel_In_scaled = _sf.gsl_sf_bessel_In_scaled

def gsl_sf_bessel_K0_e(x, result):
    return _sf.gsl_sf_bessel_K0_e(x, result)
gsl_sf_bessel_K0_e = _sf.gsl_sf_bessel_K0_e

def gsl_sf_bessel_K0(x):
    return _sf.gsl_sf_bessel_K0(x)
gsl_sf_bessel_K0 = _sf.gsl_sf_bessel_K0

def gsl_sf_bessel_K1_e(x, result):
    return _sf.gsl_sf_bessel_K1_e(x, result)
gsl_sf_bessel_K1_e = _sf.gsl_sf_bessel_K1_e

def gsl_sf_bessel_K1(x):
    return _sf.gsl_sf_bessel_K1(x)
gsl_sf_bessel_K1 = _sf.gsl_sf_bessel_K1

def gsl_sf_bessel_Kn_e(n, x, result):
    return _sf.gsl_sf_bessel_Kn_e(n, x, result)
gsl_sf_bessel_Kn_e = _sf.gsl_sf_bessel_Kn_e

def gsl_sf_bessel_Kn(n, x):
    return _sf.gsl_sf_bessel_Kn(n, x)
gsl_sf_bessel_Kn = _sf.gsl_sf_bessel_Kn

def gsl_sf_bessel_K0_scaled_e(x, result):
    return _sf.gsl_sf_bessel_K0_scaled_e(x, result)
gsl_sf_bessel_K0_scaled_e = _sf.gsl_sf_bessel_K0_scaled_e

def gsl_sf_bessel_K0_scaled(x):
    return _sf.gsl_sf_bessel_K0_scaled(x)
gsl_sf_bessel_K0_scaled = _sf.gsl_sf_bessel_K0_scaled

def gsl_sf_bessel_K1_scaled_e(x, result):
    return _sf.gsl_sf_bessel_K1_scaled_e(x, result)
gsl_sf_bessel_K1_scaled_e = _sf.gsl_sf_bessel_K1_scaled_e

def gsl_sf_bessel_K1_scaled(x):
    return _sf.gsl_sf_bessel_K1_scaled(x)
gsl_sf_bessel_K1_scaled = _sf.gsl_sf_bessel_K1_scaled

def gsl_sf_bessel_Kn_scaled_e(n, x, result):
    return _sf.gsl_sf_bessel_Kn_scaled_e(n, x, result)
gsl_sf_bessel_Kn_scaled_e = _sf.gsl_sf_bessel_Kn_scaled_e

def gsl_sf_bessel_Kn_scaled(n, x):
    return _sf.gsl_sf_bessel_Kn_scaled(n, x)
gsl_sf_bessel_Kn_scaled = _sf.gsl_sf_bessel_Kn_scaled

def gsl_sf_bessel_j0_e(x, result):
    return _sf.gsl_sf_bessel_j0_e(x, result)
gsl_sf_bessel_j0_e = _sf.gsl_sf_bessel_j0_e

def gsl_sf_bessel_j0(x):
    return _sf.gsl_sf_bessel_j0(x)
gsl_sf_bessel_j0 = _sf.gsl_sf_bessel_j0

def gsl_sf_bessel_j1_e(x, result):
    return _sf.gsl_sf_bessel_j1_e(x, result)
gsl_sf_bessel_j1_e = _sf.gsl_sf_bessel_j1_e

def gsl_sf_bessel_j1(x):
    return _sf.gsl_sf_bessel_j1(x)
gsl_sf_bessel_j1 = _sf.gsl_sf_bessel_j1

def gsl_sf_bessel_j2_e(x, result):
    return _sf.gsl_sf_bessel_j2_e(x, result)
gsl_sf_bessel_j2_e = _sf.gsl_sf_bessel_j2_e

def gsl_sf_bessel_j2(x):
    return _sf.gsl_sf_bessel_j2(x)
gsl_sf_bessel_j2 = _sf.gsl_sf_bessel_j2

def gsl_sf_bessel_jl_e(l, x, result):
    return _sf.gsl_sf_bessel_jl_e(l, x, result)
gsl_sf_bessel_jl_e = _sf.gsl_sf_bessel_jl_e

def gsl_sf_bessel_jl(l, x):
    return _sf.gsl_sf_bessel_jl(l, x)
gsl_sf_bessel_jl = _sf.gsl_sf_bessel_jl

def gsl_sf_bessel_y0_e(x, result):
    return _sf.gsl_sf_bessel_y0_e(x, result)
gsl_sf_bessel_y0_e = _sf.gsl_sf_bessel_y0_e

def gsl_sf_bessel_y0(x):
    return _sf.gsl_sf_bessel_y0(x)
gsl_sf_bessel_y0 = _sf.gsl_sf_bessel_y0

def gsl_sf_bessel_y1_e(x, result):
    return _sf.gsl_sf_bessel_y1_e(x, result)
gsl_sf_bessel_y1_e = _sf.gsl_sf_bessel_y1_e

def gsl_sf_bessel_y1(x):
    return _sf.gsl_sf_bessel_y1(x)
gsl_sf_bessel_y1 = _sf.gsl_sf_bessel_y1

def gsl_sf_bessel_y2_e(x, result):
    return _sf.gsl_sf_bessel_y2_e(x, result)
gsl_sf_bessel_y2_e = _sf.gsl_sf_bessel_y2_e

def gsl_sf_bessel_y2(x):
    return _sf.gsl_sf_bessel_y2(x)
gsl_sf_bessel_y2 = _sf.gsl_sf_bessel_y2

def gsl_sf_bessel_yl_e(l, x, result):
    return _sf.gsl_sf_bessel_yl_e(l, x, result)
gsl_sf_bessel_yl_e = _sf.gsl_sf_bessel_yl_e

def gsl_sf_bessel_yl(l, x):
    return _sf.gsl_sf_bessel_yl(l, x)
gsl_sf_bessel_yl = _sf.gsl_sf_bessel_yl

def gsl_sf_bessel_i0_scaled_e(x, result):
    return _sf.gsl_sf_bessel_i0_scaled_e(x, result)
gsl_sf_bessel_i0_scaled_e = _sf.gsl_sf_bessel_i0_scaled_e

def gsl_sf_bessel_i0_scaled(x):
    return _sf.gsl_sf_bessel_i0_scaled(x)
gsl_sf_bessel_i0_scaled = _sf.gsl_sf_bessel_i0_scaled

def gsl_sf_bessel_i1_scaled_e(x, result):
    return _sf.gsl_sf_bessel_i1_scaled_e(x, result)
gsl_sf_bessel_i1_scaled_e = _sf.gsl_sf_bessel_i1_scaled_e

def gsl_sf_bessel_i1_scaled(x):
    return _sf.gsl_sf_bessel_i1_scaled(x)
gsl_sf_bessel_i1_scaled = _sf.gsl_sf_bessel_i1_scaled

def gsl_sf_bessel_i2_scaled_e(x, result):
    return _sf.gsl_sf_bessel_i2_scaled_e(x, result)
gsl_sf_bessel_i2_scaled_e = _sf.gsl_sf_bessel_i2_scaled_e

def gsl_sf_bessel_i2_scaled(x):
    return _sf.gsl_sf_bessel_i2_scaled(x)
gsl_sf_bessel_i2_scaled = _sf.gsl_sf_bessel_i2_scaled

def gsl_sf_bessel_il_scaled_e(l, x, result):
    return _sf.gsl_sf_bessel_il_scaled_e(l, x, result)
gsl_sf_bessel_il_scaled_e = _sf.gsl_sf_bessel_il_scaled_e

def gsl_sf_bessel_il_scaled(l, x):
    return _sf.gsl_sf_bessel_il_scaled(l, x)
gsl_sf_bessel_il_scaled = _sf.gsl_sf_bessel_il_scaled

def gsl_sf_bessel_k0_scaled_e(x, result):
    return _sf.gsl_sf_bessel_k0_scaled_e(x, result)
gsl_sf_bessel_k0_scaled_e = _sf.gsl_sf_bessel_k0_scaled_e

def gsl_sf_bessel_k0_scaled(x):
    return _sf.gsl_sf_bessel_k0_scaled(x)
gsl_sf_bessel_k0_scaled = _sf.gsl_sf_bessel_k0_scaled

def gsl_sf_bessel_k1_scaled_e(x, result):
    return _sf.gsl_sf_bessel_k1_scaled_e(x, result)
gsl_sf_bessel_k1_scaled_e = _sf.gsl_sf_bessel_k1_scaled_e

def gsl_sf_bessel_k1_scaled(x):
    return _sf.gsl_sf_bessel_k1_scaled(x)
gsl_sf_bessel_k1_scaled = _sf.gsl_sf_bessel_k1_scaled

def gsl_sf_bessel_k2_scaled_e(x, result):
    return _sf.gsl_sf_bessel_k2_scaled_e(x, result)
gsl_sf_bessel_k2_scaled_e = _sf.gsl_sf_bessel_k2_scaled_e

def gsl_sf_bessel_k2_scaled(x):
    return _sf.gsl_sf_bessel_k2_scaled(x)
gsl_sf_bessel_k2_scaled = _sf.gsl_sf_bessel_k2_scaled

def gsl_sf_bessel_kl_scaled_e(l, x, result):
    return _sf.gsl_sf_bessel_kl_scaled_e(l, x, result)
gsl_sf_bessel_kl_scaled_e = _sf.gsl_sf_bessel_kl_scaled_e

def gsl_sf_bessel_kl_scaled(l, x):
    return _sf.gsl_sf_bessel_kl_scaled(l, x)
gsl_sf_bessel_kl_scaled = _sf.gsl_sf_bessel_kl_scaled

def gsl_sf_bessel_Jnu_e(nu, x, result):
    return _sf.gsl_sf_bessel_Jnu_e(nu, x, result)
gsl_sf_bessel_Jnu_e = _sf.gsl_sf_bessel_Jnu_e

def gsl_sf_bessel_Jnu(nu, x):
    return _sf.gsl_sf_bessel_Jnu(nu, x)
gsl_sf_bessel_Jnu = _sf.gsl_sf_bessel_Jnu

def gsl_sf_bessel_Ynu_e(nu, x, result):
    return _sf.gsl_sf_bessel_Ynu_e(nu, x, result)
gsl_sf_bessel_Ynu_e = _sf.gsl_sf_bessel_Ynu_e

def gsl_sf_bessel_Ynu(nu, x):
    return _sf.gsl_sf_bessel_Ynu(nu, x)
gsl_sf_bessel_Ynu = _sf.gsl_sf_bessel_Ynu

def gsl_sf_bessel_Inu_scaled_e(nu, x, result):
    return _sf.gsl_sf_bessel_Inu_scaled_e(nu, x, result)
gsl_sf_bessel_Inu_scaled_e = _sf.gsl_sf_bessel_Inu_scaled_e

def gsl_sf_bessel_Inu_scaled(nu, x):
    return _sf.gsl_sf_bessel_Inu_scaled(nu, x)
gsl_sf_bessel_Inu_scaled = _sf.gsl_sf_bessel_Inu_scaled

def gsl_sf_bessel_Inu_e(nu, x, result):
    return _sf.gsl_sf_bessel_Inu_e(nu, x, result)
gsl_sf_bessel_Inu_e = _sf.gsl_sf_bessel_Inu_e

def gsl_sf_bessel_Inu(nu, x):
    return _sf.gsl_sf_bessel_Inu(nu, x)
gsl_sf_bessel_Inu = _sf.gsl_sf_bessel_Inu

def gsl_sf_bessel_Knu_scaled_e(nu, x, result):
    return _sf.gsl_sf_bessel_Knu_scaled_e(nu, x, result)
gsl_sf_bessel_Knu_scaled_e = _sf.gsl_sf_bessel_Knu_scaled_e

def gsl_sf_bessel_Knu_scaled(nu, x):
    return _sf.gsl_sf_bessel_Knu_scaled(nu, x)
gsl_sf_bessel_Knu_scaled = _sf.gsl_sf_bessel_Knu_scaled

def gsl_sf_bessel_Knu_scaled_e10_e(nu, x, result):
    return _sf.gsl_sf_bessel_Knu_scaled_e10_e(nu, x, result)
gsl_sf_bessel_Knu_scaled_e10_e = _sf.gsl_sf_bessel_Knu_scaled_e10_e

def gsl_sf_bessel_Knu_e(nu, x, result):
    return _sf.gsl_sf_bessel_Knu_e(nu, x, result)
gsl_sf_bessel_Knu_e = _sf.gsl_sf_bessel_Knu_e

def gsl_sf_bessel_Knu(nu, x):
    return _sf.gsl_sf_bessel_Knu(nu, x)
gsl_sf_bessel_Knu = _sf.gsl_sf_bessel_Knu

def gsl_sf_bessel_lnKnu_e(nu, x, result):
    return _sf.gsl_sf_bessel_lnKnu_e(nu, x, result)
gsl_sf_bessel_lnKnu_e = _sf.gsl_sf_bessel_lnKnu_e

def gsl_sf_bessel_lnKnu(nu, x):
    return _sf.gsl_sf_bessel_lnKnu(nu, x)
gsl_sf_bessel_lnKnu = _sf.gsl_sf_bessel_lnKnu

def gsl_sf_bessel_zero_J0_e(s, result):
    return _sf.gsl_sf_bessel_zero_J0_e(s, result)
gsl_sf_bessel_zero_J0_e = _sf.gsl_sf_bessel_zero_J0_e

def gsl_sf_bessel_zero_J0(s):
    return _sf.gsl_sf_bessel_zero_J0(s)
gsl_sf_bessel_zero_J0 = _sf.gsl_sf_bessel_zero_J0

def gsl_sf_bessel_zero_J1_e(s, result):
    return _sf.gsl_sf_bessel_zero_J1_e(s, result)
gsl_sf_bessel_zero_J1_e = _sf.gsl_sf_bessel_zero_J1_e

def gsl_sf_bessel_zero_J1(s):
    return _sf.gsl_sf_bessel_zero_J1(s)
gsl_sf_bessel_zero_J1 = _sf.gsl_sf_bessel_zero_J1

def gsl_sf_bessel_zero_Jnu_e(nu, s, result):
    return _sf.gsl_sf_bessel_zero_Jnu_e(nu, s, result)
gsl_sf_bessel_zero_Jnu_e = _sf.gsl_sf_bessel_zero_Jnu_e

def gsl_sf_bessel_zero_Jnu(nu, s):
    return _sf.gsl_sf_bessel_zero_Jnu(nu, s)
gsl_sf_bessel_zero_Jnu = _sf.gsl_sf_bessel_zero_Jnu

def gsl_sf_clausen_e(x, result):
    return _sf.gsl_sf_clausen_e(x, result)
gsl_sf_clausen_e = _sf.gsl_sf_clausen_e

def gsl_sf_clausen(x):
    return _sf.gsl_sf_clausen(x)
gsl_sf_clausen = _sf.gsl_sf_clausen

def gsl_sf_hydrogenicR_1_e(Z, r, result):
    return _sf.gsl_sf_hydrogenicR_1_e(Z, r, result)
gsl_sf_hydrogenicR_1_e = _sf.gsl_sf_hydrogenicR_1_e

def gsl_sf_hydrogenicR_1(Z, r):
    return _sf.gsl_sf_hydrogenicR_1(Z, r)
gsl_sf_hydrogenicR_1 = _sf.gsl_sf_hydrogenicR_1

def gsl_sf_hydrogenicR_e(n, l, Z, r, result):
    return _sf.gsl_sf_hydrogenicR_e(n, l, Z, r, result)
gsl_sf_hydrogenicR_e = _sf.gsl_sf_hydrogenicR_e

def gsl_sf_hydrogenicR(n, l, Z, r):
    return _sf.gsl_sf_hydrogenicR(n, l, Z, r)
gsl_sf_hydrogenicR = _sf.gsl_sf_hydrogenicR

def gsl_sf_coulomb_wave_FG_e(eta, x, lam_F, k_lam_G, F, Fp, G, Gp, exp_F, exp_G):
    return _sf.gsl_sf_coulomb_wave_FG_e(eta, x, lam_F, k_lam_G, F, Fp, G, Gp, exp_F, exp_G)
gsl_sf_coulomb_wave_FG_e = _sf.gsl_sf_coulomb_wave_FG_e

def gsl_sf_coulomb_CL_e(L, eta, result):
    return _sf.gsl_sf_coulomb_CL_e(L, eta, result)
gsl_sf_coulomb_CL_e = _sf.gsl_sf_coulomb_CL_e

def gsl_sf_coupling_3j_e(two_ja, two_jb, two_jc, two_ma, two_mb, two_mc, result):
    return _sf.gsl_sf_coupling_3j_e(two_ja, two_jb, two_jc, two_ma, two_mb, two_mc, result)
gsl_sf_coupling_3j_e = _sf.gsl_sf_coupling_3j_e

def gsl_sf_coupling_3j(two_ja, two_jb, two_jc, two_ma, two_mb, two_mc):
    return _sf.gsl_sf_coupling_3j(two_ja, two_jb, two_jc, two_ma, two_mb, two_mc)
gsl_sf_coupling_3j = _sf.gsl_sf_coupling_3j

def gsl_sf_coupling_6j_e(two_ja, two_jb, two_jc, two_jd, two_je, two_jf, result):
    return _sf.gsl_sf_coupling_6j_e(two_ja, two_jb, two_jc, two_jd, two_je, two_jf, result)
gsl_sf_coupling_6j_e = _sf.gsl_sf_coupling_6j_e

def gsl_sf_coupling_6j(two_ja, two_jb, two_jc, two_jd, two_je, two_jf):
    return _sf.gsl_sf_coupling_6j(two_ja, two_jb, two_jc, two_jd, two_je, two_jf)
gsl_sf_coupling_6j = _sf.gsl_sf_coupling_6j

def gsl_sf_coupling_RacahW_e(two_ja, two_jb, two_jc, two_jd, two_je, two_jf, result):
    return _sf.gsl_sf_coupling_RacahW_e(two_ja, two_jb, two_jc, two_jd, two_je, two_jf, result)
gsl_sf_coupling_RacahW_e = _sf.gsl_sf_coupling_RacahW_e

def gsl_sf_coupling_RacahW(two_ja, two_jb, two_jc, two_jd, two_je, two_jf):
    return _sf.gsl_sf_coupling_RacahW(two_ja, two_jb, two_jc, two_jd, two_je, two_jf)
gsl_sf_coupling_RacahW = _sf.gsl_sf_coupling_RacahW

def gsl_sf_coupling_9j_e(two_ja, two_jb, two_jc, two_jd, two_je, two_jf, two_jg, two_jh, two_ji, result):
    return _sf.gsl_sf_coupling_9j_e(two_ja, two_jb, two_jc, two_jd, two_je, two_jf, two_jg, two_jh, two_ji, result)
gsl_sf_coupling_9j_e = _sf.gsl_sf_coupling_9j_e

def gsl_sf_coupling_9j(two_ja, two_jb, two_jc, two_jd, two_je, two_jf, two_jg, two_jh, two_ji):
    return _sf.gsl_sf_coupling_9j(two_ja, two_jb, two_jc, two_jd, two_je, two_jf, two_jg, two_jh, two_ji)
gsl_sf_coupling_9j = _sf.gsl_sf_coupling_9j

def gsl_sf_dawson_e(x, result):
    return _sf.gsl_sf_dawson_e(x, result)
gsl_sf_dawson_e = _sf.gsl_sf_dawson_e

def gsl_sf_dawson(x):
    return _sf.gsl_sf_dawson(x)
gsl_sf_dawson = _sf.gsl_sf_dawson

def gsl_sf_debye_1_e(x, result):
    return _sf.gsl_sf_debye_1_e(x, result)
gsl_sf_debye_1_e = _sf.gsl_sf_debye_1_e

def gsl_sf_debye_1(x):
    return _sf.gsl_sf_debye_1(x)
gsl_sf_debye_1 = _sf.gsl_sf_debye_1

def gsl_sf_debye_2_e(x, result):
    return _sf.gsl_sf_debye_2_e(x, result)
gsl_sf_debye_2_e = _sf.gsl_sf_debye_2_e

def gsl_sf_debye_2(x):
    return _sf.gsl_sf_debye_2(x)
gsl_sf_debye_2 = _sf.gsl_sf_debye_2

def gsl_sf_debye_3_e(x, result):
    return _sf.gsl_sf_debye_3_e(x, result)
gsl_sf_debye_3_e = _sf.gsl_sf_debye_3_e

def gsl_sf_debye_3(x):
    return _sf.gsl_sf_debye_3(x)
gsl_sf_debye_3 = _sf.gsl_sf_debye_3

def gsl_sf_debye_4_e(x, result):
    return _sf.gsl_sf_debye_4_e(x, result)
gsl_sf_debye_4_e = _sf.gsl_sf_debye_4_e

def gsl_sf_debye_4(x):
    return _sf.gsl_sf_debye_4(x)
gsl_sf_debye_4 = _sf.gsl_sf_debye_4

def gsl_sf_debye_5_e(x, result):
    return _sf.gsl_sf_debye_5_e(x, result)
gsl_sf_debye_5_e = _sf.gsl_sf_debye_5_e

def gsl_sf_debye_5(x):
    return _sf.gsl_sf_debye_5(x)
gsl_sf_debye_5 = _sf.gsl_sf_debye_5

def gsl_sf_debye_6_e(x, result):
    return _sf.gsl_sf_debye_6_e(x, result)
gsl_sf_debye_6_e = _sf.gsl_sf_debye_6_e

def gsl_sf_debye_6(x):
    return _sf.gsl_sf_debye_6(x)
gsl_sf_debye_6 = _sf.gsl_sf_debye_6

def gsl_sf_dilog_e(x, result):
    return _sf.gsl_sf_dilog_e(x, result)
gsl_sf_dilog_e = _sf.gsl_sf_dilog_e

def gsl_sf_dilog(x):
    return _sf.gsl_sf_dilog(x)
gsl_sf_dilog = _sf.gsl_sf_dilog

def gsl_sf_complex_dilog_xy_e(x, y, result_re, result_im):
    return _sf.gsl_sf_complex_dilog_xy_e(x, y, result_re, result_im)
gsl_sf_complex_dilog_xy_e = _sf.gsl_sf_complex_dilog_xy_e

def gsl_sf_complex_dilog_e(r, theta, result_re, result_im):
    return _sf.gsl_sf_complex_dilog_e(r, theta, result_re, result_im)
gsl_sf_complex_dilog_e = _sf.gsl_sf_complex_dilog_e

def gsl_sf_complex_spence_xy_e(x, y, real_sp, imag_sp):
    return _sf.gsl_sf_complex_spence_xy_e(x, y, real_sp, imag_sp)
gsl_sf_complex_spence_xy_e = _sf.gsl_sf_complex_spence_xy_e

def gsl_sf_multiply_e(x, y, result):
    return _sf.gsl_sf_multiply_e(x, y, result)
gsl_sf_multiply_e = _sf.gsl_sf_multiply_e

def gsl_sf_multiply(x, y):
    return _sf.gsl_sf_multiply(x, y)
gsl_sf_multiply = _sf.gsl_sf_multiply

def gsl_sf_multiply_err_e(x, dx, y, dy, result):
    return _sf.gsl_sf_multiply_err_e(x, dx, y, dy, result)
gsl_sf_multiply_err_e = _sf.gsl_sf_multiply_err_e

def gsl_sf_ellint_Kcomp_e(k, mode, result):
    return _sf.gsl_sf_ellint_Kcomp_e(k, mode, result)
gsl_sf_ellint_Kcomp_e = _sf.gsl_sf_ellint_Kcomp_e

def gsl_sf_ellint_Kcomp(k, mode):
    return _sf.gsl_sf_ellint_Kcomp(k, mode)
gsl_sf_ellint_Kcomp = _sf.gsl_sf_ellint_Kcomp

def gsl_sf_ellint_Ecomp_e(k, mode, result):
    return _sf.gsl_sf_ellint_Ecomp_e(k, mode, result)
gsl_sf_ellint_Ecomp_e = _sf.gsl_sf_ellint_Ecomp_e

def gsl_sf_ellint_Ecomp(k, mode):
    return _sf.gsl_sf_ellint_Ecomp(k, mode)
gsl_sf_ellint_Ecomp = _sf.gsl_sf_ellint_Ecomp

def gsl_sf_ellint_Pcomp_e(k, n, mode, result):
    return _sf.gsl_sf_ellint_Pcomp_e(k, n, mode, result)
gsl_sf_ellint_Pcomp_e = _sf.gsl_sf_ellint_Pcomp_e

def gsl_sf_ellint_Pcomp(k, n, mode):
    return _sf.gsl_sf_ellint_Pcomp(k, n, mode)
gsl_sf_ellint_Pcomp = _sf.gsl_sf_ellint_Pcomp

def gsl_sf_ellint_Dcomp_e(k, mode, result):
    return _sf.gsl_sf_ellint_Dcomp_e(k, mode, result)
gsl_sf_ellint_Dcomp_e = _sf.gsl_sf_ellint_Dcomp_e

def gsl_sf_ellint_Dcomp(k, mode):
    return _sf.gsl_sf_ellint_Dcomp(k, mode)
gsl_sf_ellint_Dcomp = _sf.gsl_sf_ellint_Dcomp

def gsl_sf_ellint_F_e(phi, k, mode, result):
    return _sf.gsl_sf_ellint_F_e(phi, k, mode, result)
gsl_sf_ellint_F_e = _sf.gsl_sf_ellint_F_e

def gsl_sf_ellint_F(phi, k, mode):
    return _sf.gsl_sf_ellint_F(phi, k, mode)
gsl_sf_ellint_F = _sf.gsl_sf_ellint_F

def gsl_sf_ellint_E_e(phi, k, mode, result):
    return _sf.gsl_sf_ellint_E_e(phi, k, mode, result)
gsl_sf_ellint_E_e = _sf.gsl_sf_ellint_E_e

def gsl_sf_ellint_E(phi, k, mode):
    return _sf.gsl_sf_ellint_E(phi, k, mode)
gsl_sf_ellint_E = _sf.gsl_sf_ellint_E

def gsl_sf_ellint_P_e(phi, k, n, mode, result):
    return _sf.gsl_sf_ellint_P_e(phi, k, n, mode, result)
gsl_sf_ellint_P_e = _sf.gsl_sf_ellint_P_e

def gsl_sf_ellint_P(phi, k, n, mode):
    return _sf.gsl_sf_ellint_P(phi, k, n, mode)
gsl_sf_ellint_P = _sf.gsl_sf_ellint_P

def gsl_sf_ellint_D_e(phi, k, mode, result):
    return _sf.gsl_sf_ellint_D_e(phi, k, mode, result)
gsl_sf_ellint_D_e = _sf.gsl_sf_ellint_D_e

def gsl_sf_ellint_D(phi, k, mode):
    return _sf.gsl_sf_ellint_D(phi, k, mode)
gsl_sf_ellint_D = _sf.gsl_sf_ellint_D

def gsl_sf_ellint_RC_e(x, y, mode, result):
    return _sf.gsl_sf_ellint_RC_e(x, y, mode, result)
gsl_sf_ellint_RC_e = _sf.gsl_sf_ellint_RC_e

def gsl_sf_ellint_RC(x, y, mode):
    return _sf.gsl_sf_ellint_RC(x, y, mode)
gsl_sf_ellint_RC = _sf.gsl_sf_ellint_RC

def gsl_sf_ellint_RD_e(x, y, z, mode, result):
    return _sf.gsl_sf_ellint_RD_e(x, y, z, mode, result)
gsl_sf_ellint_RD_e = _sf.gsl_sf_ellint_RD_e

def gsl_sf_ellint_RD(x, y, z, mode):
    return _sf.gsl_sf_ellint_RD(x, y, z, mode)
gsl_sf_ellint_RD = _sf.gsl_sf_ellint_RD

def gsl_sf_ellint_RF_e(x, y, z, mode, result):
    return _sf.gsl_sf_ellint_RF_e(x, y, z, mode, result)
gsl_sf_ellint_RF_e = _sf.gsl_sf_ellint_RF_e

def gsl_sf_ellint_RF(x, y, z, mode):
    return _sf.gsl_sf_ellint_RF(x, y, z, mode)
gsl_sf_ellint_RF = _sf.gsl_sf_ellint_RF

def gsl_sf_ellint_RJ_e(x, y, z, p, mode, result):
    return _sf.gsl_sf_ellint_RJ_e(x, y, z, p, mode, result)
gsl_sf_ellint_RJ_e = _sf.gsl_sf_ellint_RJ_e

def gsl_sf_ellint_RJ(x, y, z, p, mode):
    return _sf.gsl_sf_ellint_RJ(x, y, z, p, mode)
gsl_sf_ellint_RJ = _sf.gsl_sf_ellint_RJ

def gsl_sf_elljac_e(u, m, sn, cn, dn):
    return _sf.gsl_sf_elljac_e(u, m, sn, cn, dn)
gsl_sf_elljac_e = _sf.gsl_sf_elljac_e

def gsl_sf_erfc_e(x, result):
    return _sf.gsl_sf_erfc_e(x, result)
gsl_sf_erfc_e = _sf.gsl_sf_erfc_e

def gsl_sf_erfc(x):
    return _sf.gsl_sf_erfc(x)
gsl_sf_erfc = _sf.gsl_sf_erfc

def gsl_sf_log_erfc_e(x, result):
    return _sf.gsl_sf_log_erfc_e(x, result)
gsl_sf_log_erfc_e = _sf.gsl_sf_log_erfc_e

def gsl_sf_log_erfc(x):
    return _sf.gsl_sf_log_erfc(x)
gsl_sf_log_erfc = _sf.gsl_sf_log_erfc

def gsl_sf_erf_e(x, result):
    return _sf.gsl_sf_erf_e(x, result)
gsl_sf_erf_e = _sf.gsl_sf_erf_e

def gsl_sf_erf(x):
    return _sf.gsl_sf_erf(x)
gsl_sf_erf = _sf.gsl_sf_erf

def gsl_sf_erf_Z_e(x, result):
    return _sf.gsl_sf_erf_Z_e(x, result)
gsl_sf_erf_Z_e = _sf.gsl_sf_erf_Z_e

def gsl_sf_erf_Q_e(x, result):
    return _sf.gsl_sf_erf_Q_e(x, result)
gsl_sf_erf_Q_e = _sf.gsl_sf_erf_Q_e

def gsl_sf_erf_Z(x):
    return _sf.gsl_sf_erf_Z(x)
gsl_sf_erf_Z = _sf.gsl_sf_erf_Z

def gsl_sf_erf_Q(x):
    return _sf.gsl_sf_erf_Q(x)
gsl_sf_erf_Q = _sf.gsl_sf_erf_Q

def gsl_sf_hazard_e(x, result):
    return _sf.gsl_sf_hazard_e(x, result)
gsl_sf_hazard_e = _sf.gsl_sf_hazard_e

def gsl_sf_hazard(x):
    return _sf.gsl_sf_hazard(x)
gsl_sf_hazard = _sf.gsl_sf_hazard

def gsl_sf_exp_e(x, result):
    return _sf.gsl_sf_exp_e(x, result)
gsl_sf_exp_e = _sf.gsl_sf_exp_e

def gsl_sf_exp(x):
    return _sf.gsl_sf_exp(x)
gsl_sf_exp = _sf.gsl_sf_exp

def gsl_sf_exp_e10_e(x, result):
    return _sf.gsl_sf_exp_e10_e(x, result)
gsl_sf_exp_e10_e = _sf.gsl_sf_exp_e10_e

def gsl_sf_exp_mult_e(x, y, result):
    return _sf.gsl_sf_exp_mult_e(x, y, result)
gsl_sf_exp_mult_e = _sf.gsl_sf_exp_mult_e

def gsl_sf_exp_mult(x, y):
    return _sf.gsl_sf_exp_mult(x, y)
gsl_sf_exp_mult = _sf.gsl_sf_exp_mult

def gsl_sf_exp_mult_e10_e(x, y, result):
    return _sf.gsl_sf_exp_mult_e10_e(x, y, result)
gsl_sf_exp_mult_e10_e = _sf.gsl_sf_exp_mult_e10_e

def gsl_sf_expm1_e(x, result):
    return _sf.gsl_sf_expm1_e(x, result)
gsl_sf_expm1_e = _sf.gsl_sf_expm1_e

def gsl_sf_expm1(x):
    return _sf.gsl_sf_expm1(x)
gsl_sf_expm1 = _sf.gsl_sf_expm1

def gsl_sf_exprel_e(x, result):
    return _sf.gsl_sf_exprel_e(x, result)
gsl_sf_exprel_e = _sf.gsl_sf_exprel_e

def gsl_sf_exprel(x):
    return _sf.gsl_sf_exprel(x)
gsl_sf_exprel = _sf.gsl_sf_exprel

def gsl_sf_exprel_2_e(x, result):
    return _sf.gsl_sf_exprel_2_e(x, result)
gsl_sf_exprel_2_e = _sf.gsl_sf_exprel_2_e

def gsl_sf_exprel_2(x):
    return _sf.gsl_sf_exprel_2(x)
gsl_sf_exprel_2 = _sf.gsl_sf_exprel_2

def gsl_sf_exprel_n_e(n, x, result):
    return _sf.gsl_sf_exprel_n_e(n, x, result)
gsl_sf_exprel_n_e = _sf.gsl_sf_exprel_n_e

def gsl_sf_exprel_n(n, x):
    return _sf.gsl_sf_exprel_n(n, x)
gsl_sf_exprel_n = _sf.gsl_sf_exprel_n

def gsl_sf_exprel_n_CF_e(n, x, result):
    return _sf.gsl_sf_exprel_n_CF_e(n, x, result)
gsl_sf_exprel_n_CF_e = _sf.gsl_sf_exprel_n_CF_e

def gsl_sf_exp_err_e(x, dx, result):
    return _sf.gsl_sf_exp_err_e(x, dx, result)
gsl_sf_exp_err_e = _sf.gsl_sf_exp_err_e

def gsl_sf_exp_err_e10_e(x, dx, result):
    return _sf.gsl_sf_exp_err_e10_e(x, dx, result)
gsl_sf_exp_err_e10_e = _sf.gsl_sf_exp_err_e10_e

def gsl_sf_exp_mult_err_e(x, dx, y, dy, result):
    return _sf.gsl_sf_exp_mult_err_e(x, dx, y, dy, result)
gsl_sf_exp_mult_err_e = _sf.gsl_sf_exp_mult_err_e

def gsl_sf_exp_mult_err_e10_e(x, dx, y, dy, result):
    return _sf.gsl_sf_exp_mult_err_e10_e(x, dx, y, dy, result)
gsl_sf_exp_mult_err_e10_e = _sf.gsl_sf_exp_mult_err_e10_e

def gsl_sf_expint_E1_e(x, result):
    return _sf.gsl_sf_expint_E1_e(x, result)
gsl_sf_expint_E1_e = _sf.gsl_sf_expint_E1_e

def gsl_sf_expint_E1(x):
    return _sf.gsl_sf_expint_E1(x)
gsl_sf_expint_E1 = _sf.gsl_sf_expint_E1

def gsl_sf_expint_E2_e(x, result):
    return _sf.gsl_sf_expint_E2_e(x, result)
gsl_sf_expint_E2_e = _sf.gsl_sf_expint_E2_e

def gsl_sf_expint_E2(x):
    return _sf.gsl_sf_expint_E2(x)
gsl_sf_expint_E2 = _sf.gsl_sf_expint_E2

def gsl_sf_expint_En_e(n, x, result):
    return _sf.gsl_sf_expint_En_e(n, x, result)
gsl_sf_expint_En_e = _sf.gsl_sf_expint_En_e

def gsl_sf_expint_En(n, x):
    return _sf.gsl_sf_expint_En(n, x)
gsl_sf_expint_En = _sf.gsl_sf_expint_En

def gsl_sf_expint_E1_scaled_e(x, result):
    return _sf.gsl_sf_expint_E1_scaled_e(x, result)
gsl_sf_expint_E1_scaled_e = _sf.gsl_sf_expint_E1_scaled_e

def gsl_sf_expint_E1_scaled(x):
    return _sf.gsl_sf_expint_E1_scaled(x)
gsl_sf_expint_E1_scaled = _sf.gsl_sf_expint_E1_scaled

def gsl_sf_expint_E2_scaled_e(x, result):
    return _sf.gsl_sf_expint_E2_scaled_e(x, result)
gsl_sf_expint_E2_scaled_e = _sf.gsl_sf_expint_E2_scaled_e

def gsl_sf_expint_E2_scaled(x):
    return _sf.gsl_sf_expint_E2_scaled(x)
gsl_sf_expint_E2_scaled = _sf.gsl_sf_expint_E2_scaled

def gsl_sf_expint_En_scaled_e(n, x, result):
    return _sf.gsl_sf_expint_En_scaled_e(n, x, result)
gsl_sf_expint_En_scaled_e = _sf.gsl_sf_expint_En_scaled_e

def gsl_sf_expint_En_scaled(n, x):
    return _sf.gsl_sf_expint_En_scaled(n, x)
gsl_sf_expint_En_scaled = _sf.gsl_sf_expint_En_scaled

def gsl_sf_expint_Ei_e(x, result):
    return _sf.gsl_sf_expint_Ei_e(x, result)
gsl_sf_expint_Ei_e = _sf.gsl_sf_expint_Ei_e

def gsl_sf_expint_Ei(x):
    return _sf.gsl_sf_expint_Ei(x)
gsl_sf_expint_Ei = _sf.gsl_sf_expint_Ei

def gsl_sf_expint_Ei_scaled_e(x, result):
    return _sf.gsl_sf_expint_Ei_scaled_e(x, result)
gsl_sf_expint_Ei_scaled_e = _sf.gsl_sf_expint_Ei_scaled_e

def gsl_sf_expint_Ei_scaled(x):
    return _sf.gsl_sf_expint_Ei_scaled(x)
gsl_sf_expint_Ei_scaled = _sf.gsl_sf_expint_Ei_scaled

def gsl_sf_Shi_e(x, result):
    return _sf.gsl_sf_Shi_e(x, result)
gsl_sf_Shi_e = _sf.gsl_sf_Shi_e

def gsl_sf_Shi(x):
    return _sf.gsl_sf_Shi(x)
gsl_sf_Shi = _sf.gsl_sf_Shi

def gsl_sf_Chi_e(x, result):
    return _sf.gsl_sf_Chi_e(x, result)
gsl_sf_Chi_e = _sf.gsl_sf_Chi_e

def gsl_sf_Chi(x):
    return _sf.gsl_sf_Chi(x)
gsl_sf_Chi = _sf.gsl_sf_Chi

def gsl_sf_expint_3_e(x, result):
    return _sf.gsl_sf_expint_3_e(x, result)
gsl_sf_expint_3_e = _sf.gsl_sf_expint_3_e

def gsl_sf_expint_3(x):
    return _sf.gsl_sf_expint_3(x)
gsl_sf_expint_3 = _sf.gsl_sf_expint_3

def gsl_sf_Si_e(x, result):
    return _sf.gsl_sf_Si_e(x, result)
gsl_sf_Si_e = _sf.gsl_sf_Si_e

def gsl_sf_Si(x):
    return _sf.gsl_sf_Si(x)
gsl_sf_Si = _sf.gsl_sf_Si

def gsl_sf_Ci_e(x, result):
    return _sf.gsl_sf_Ci_e(x, result)
gsl_sf_Ci_e = _sf.gsl_sf_Ci_e

def gsl_sf_Ci(x):
    return _sf.gsl_sf_Ci(x)
gsl_sf_Ci = _sf.gsl_sf_Ci

def gsl_sf_atanint_e(x, result):
    return _sf.gsl_sf_atanint_e(x, result)
gsl_sf_atanint_e = _sf.gsl_sf_atanint_e

def gsl_sf_atanint(x):
    return _sf.gsl_sf_atanint(x)
gsl_sf_atanint = _sf.gsl_sf_atanint

def gsl_sf_fermi_dirac_m1_e(x, result):
    return _sf.gsl_sf_fermi_dirac_m1_e(x, result)
gsl_sf_fermi_dirac_m1_e = _sf.gsl_sf_fermi_dirac_m1_e

def gsl_sf_fermi_dirac_m1(x):
    return _sf.gsl_sf_fermi_dirac_m1(x)
gsl_sf_fermi_dirac_m1 = _sf.gsl_sf_fermi_dirac_m1

def gsl_sf_fermi_dirac_0_e(x, result):
    return _sf.gsl_sf_fermi_dirac_0_e(x, result)
gsl_sf_fermi_dirac_0_e = _sf.gsl_sf_fermi_dirac_0_e

def gsl_sf_fermi_dirac_0(x):
    return _sf.gsl_sf_fermi_dirac_0(x)
gsl_sf_fermi_dirac_0 = _sf.gsl_sf_fermi_dirac_0

def gsl_sf_fermi_dirac_1_e(x, result):
    return _sf.gsl_sf_fermi_dirac_1_e(x, result)
gsl_sf_fermi_dirac_1_e = _sf.gsl_sf_fermi_dirac_1_e

def gsl_sf_fermi_dirac_1(x):
    return _sf.gsl_sf_fermi_dirac_1(x)
gsl_sf_fermi_dirac_1 = _sf.gsl_sf_fermi_dirac_1

def gsl_sf_fermi_dirac_2_e(x, result):
    return _sf.gsl_sf_fermi_dirac_2_e(x, result)
gsl_sf_fermi_dirac_2_e = _sf.gsl_sf_fermi_dirac_2_e

def gsl_sf_fermi_dirac_2(x):
    return _sf.gsl_sf_fermi_dirac_2(x)
gsl_sf_fermi_dirac_2 = _sf.gsl_sf_fermi_dirac_2

def gsl_sf_fermi_dirac_int_e(j, x, result):
    return _sf.gsl_sf_fermi_dirac_int_e(j, x, result)
gsl_sf_fermi_dirac_int_e = _sf.gsl_sf_fermi_dirac_int_e

def gsl_sf_fermi_dirac_int(j, x):
    return _sf.gsl_sf_fermi_dirac_int(j, x)
gsl_sf_fermi_dirac_int = _sf.gsl_sf_fermi_dirac_int

def gsl_sf_fermi_dirac_mhalf_e(x, result):
    return _sf.gsl_sf_fermi_dirac_mhalf_e(x, result)
gsl_sf_fermi_dirac_mhalf_e = _sf.gsl_sf_fermi_dirac_mhalf_e

def gsl_sf_fermi_dirac_mhalf(x):
    return _sf.gsl_sf_fermi_dirac_mhalf(x)
gsl_sf_fermi_dirac_mhalf = _sf.gsl_sf_fermi_dirac_mhalf

def gsl_sf_fermi_dirac_half_e(x, result):
    return _sf.gsl_sf_fermi_dirac_half_e(x, result)
gsl_sf_fermi_dirac_half_e = _sf.gsl_sf_fermi_dirac_half_e

def gsl_sf_fermi_dirac_half(x):
    return _sf.gsl_sf_fermi_dirac_half(x)
gsl_sf_fermi_dirac_half = _sf.gsl_sf_fermi_dirac_half

def gsl_sf_fermi_dirac_3half_e(x, result):
    return _sf.gsl_sf_fermi_dirac_3half_e(x, result)
gsl_sf_fermi_dirac_3half_e = _sf.gsl_sf_fermi_dirac_3half_e

def gsl_sf_fermi_dirac_3half(x):
    return _sf.gsl_sf_fermi_dirac_3half(x)
gsl_sf_fermi_dirac_3half = _sf.gsl_sf_fermi_dirac_3half

def gsl_sf_fermi_dirac_inc_0_e(x, b, result):
    return _sf.gsl_sf_fermi_dirac_inc_0_e(x, b, result)
gsl_sf_fermi_dirac_inc_0_e = _sf.gsl_sf_fermi_dirac_inc_0_e

def gsl_sf_fermi_dirac_inc_0(x, b):
    return _sf.gsl_sf_fermi_dirac_inc_0(x, b)
gsl_sf_fermi_dirac_inc_0 = _sf.gsl_sf_fermi_dirac_inc_0

def gsl_sf_lngamma_e(x, result):
    return _sf.gsl_sf_lngamma_e(x, result)
gsl_sf_lngamma_e = _sf.gsl_sf_lngamma_e

def gsl_sf_lngamma(x):
    return _sf.gsl_sf_lngamma(x)
gsl_sf_lngamma = _sf.gsl_sf_lngamma

def gsl_sf_lngamma_sgn_e(x, result_lg, sgn):
    return _sf.gsl_sf_lngamma_sgn_e(x, result_lg, sgn)
gsl_sf_lngamma_sgn_e = _sf.gsl_sf_lngamma_sgn_e

def gsl_sf_gamma_e(x, result):
    return _sf.gsl_sf_gamma_e(x, result)
gsl_sf_gamma_e = _sf.gsl_sf_gamma_e

def gsl_sf_gamma(x):
    return _sf.gsl_sf_gamma(x)
gsl_sf_gamma = _sf.gsl_sf_gamma

def gsl_sf_gammastar_e(x, result):
    return _sf.gsl_sf_gammastar_e(x, result)
gsl_sf_gammastar_e = _sf.gsl_sf_gammastar_e

def gsl_sf_gammastar(x):
    return _sf.gsl_sf_gammastar(x)
gsl_sf_gammastar = _sf.gsl_sf_gammastar

def gsl_sf_gammainv_e(x, result):
    return _sf.gsl_sf_gammainv_e(x, result)
gsl_sf_gammainv_e = _sf.gsl_sf_gammainv_e

def gsl_sf_gammainv(x):
    return _sf.gsl_sf_gammainv(x)
gsl_sf_gammainv = _sf.gsl_sf_gammainv

def gsl_sf_lngamma_complex_e(zr, zi, lnr, arg):
    return _sf.gsl_sf_lngamma_complex_e(zr, zi, lnr, arg)
gsl_sf_lngamma_complex_e = _sf.gsl_sf_lngamma_complex_e

def gsl_sf_taylorcoeff_e(n, x, result):
    return _sf.gsl_sf_taylorcoeff_e(n, x, result)
gsl_sf_taylorcoeff_e = _sf.gsl_sf_taylorcoeff_e

def gsl_sf_taylorcoeff(n, x):
    return _sf.gsl_sf_taylorcoeff(n, x)
gsl_sf_taylorcoeff = _sf.gsl_sf_taylorcoeff

def gsl_sf_fact_e(n, result):
    return _sf.gsl_sf_fact_e(n, result)
gsl_sf_fact_e = _sf.gsl_sf_fact_e

def gsl_sf_fact(n):
    return _sf.gsl_sf_fact(n)
gsl_sf_fact = _sf.gsl_sf_fact

def gsl_sf_doublefact_e(n, result):
    return _sf.gsl_sf_doublefact_e(n, result)
gsl_sf_doublefact_e = _sf.gsl_sf_doublefact_e

def gsl_sf_doublefact(n):
    return _sf.gsl_sf_doublefact(n)
gsl_sf_doublefact = _sf.gsl_sf_doublefact

def gsl_sf_lnfact_e(n, result):
    return _sf.gsl_sf_lnfact_e(n, result)
gsl_sf_lnfact_e = _sf.gsl_sf_lnfact_e

def gsl_sf_lnfact(n):
    return _sf.gsl_sf_lnfact(n)
gsl_sf_lnfact = _sf.gsl_sf_lnfact

def gsl_sf_lndoublefact_e(n, result):
    return _sf.gsl_sf_lndoublefact_e(n, result)
gsl_sf_lndoublefact_e = _sf.gsl_sf_lndoublefact_e

def gsl_sf_lndoublefact(n):
    return _sf.gsl_sf_lndoublefact(n)
gsl_sf_lndoublefact = _sf.gsl_sf_lndoublefact

def gsl_sf_lnchoose_e(n, m, result):
    return _sf.gsl_sf_lnchoose_e(n, m, result)
gsl_sf_lnchoose_e = _sf.gsl_sf_lnchoose_e

def gsl_sf_lnchoose(n, m):
    return _sf.gsl_sf_lnchoose(n, m)
gsl_sf_lnchoose = _sf.gsl_sf_lnchoose

def gsl_sf_choose_e(n, m, result):
    return _sf.gsl_sf_choose_e(n, m, result)
gsl_sf_choose_e = _sf.gsl_sf_choose_e

def gsl_sf_choose(n, m):
    return _sf.gsl_sf_choose(n, m)
gsl_sf_choose = _sf.gsl_sf_choose

def gsl_sf_lnpoch_e(a, x, result):
    return _sf.gsl_sf_lnpoch_e(a, x, result)
gsl_sf_lnpoch_e = _sf.gsl_sf_lnpoch_e

def gsl_sf_lnpoch(a, x):
    return _sf.gsl_sf_lnpoch(a, x)
gsl_sf_lnpoch = _sf.gsl_sf_lnpoch

def gsl_sf_lnpoch_sgn_e(a, x, result, sgn):
    return _sf.gsl_sf_lnpoch_sgn_e(a, x, result, sgn)
gsl_sf_lnpoch_sgn_e = _sf.gsl_sf_lnpoch_sgn_e

def gsl_sf_poch_e(a, x, result):
    return _sf.gsl_sf_poch_e(a, x, result)
gsl_sf_poch_e = _sf.gsl_sf_poch_e

def gsl_sf_poch(a, x):
    return _sf.gsl_sf_poch(a, x)
gsl_sf_poch = _sf.gsl_sf_poch

def gsl_sf_pochrel_e(a, x, result):
    return _sf.gsl_sf_pochrel_e(a, x, result)
gsl_sf_pochrel_e = _sf.gsl_sf_pochrel_e

def gsl_sf_pochrel(a, x):
    return _sf.gsl_sf_pochrel(a, x)
gsl_sf_pochrel = _sf.gsl_sf_pochrel

def gsl_sf_gamma_inc_Q_e(a, x, result):
    return _sf.gsl_sf_gamma_inc_Q_e(a, x, result)
gsl_sf_gamma_inc_Q_e = _sf.gsl_sf_gamma_inc_Q_e

def gsl_sf_gamma_inc_Q(a, x):
    return _sf.gsl_sf_gamma_inc_Q(a, x)
gsl_sf_gamma_inc_Q = _sf.gsl_sf_gamma_inc_Q

def gsl_sf_gamma_inc_P_e(a, x, result):
    return _sf.gsl_sf_gamma_inc_P_e(a, x, result)
gsl_sf_gamma_inc_P_e = _sf.gsl_sf_gamma_inc_P_e

def gsl_sf_gamma_inc_P(a, x):
    return _sf.gsl_sf_gamma_inc_P(a, x)
gsl_sf_gamma_inc_P = _sf.gsl_sf_gamma_inc_P

def gsl_sf_gamma_inc_e(a, x, result):
    return _sf.gsl_sf_gamma_inc_e(a, x, result)
gsl_sf_gamma_inc_e = _sf.gsl_sf_gamma_inc_e

def gsl_sf_gamma_inc(a, x):
    return _sf.gsl_sf_gamma_inc(a, x)
gsl_sf_gamma_inc = _sf.gsl_sf_gamma_inc

def gsl_sf_lnbeta_e(a, b, result):
    return _sf.gsl_sf_lnbeta_e(a, b, result)
gsl_sf_lnbeta_e = _sf.gsl_sf_lnbeta_e

def gsl_sf_lnbeta(a, b):
    return _sf.gsl_sf_lnbeta(a, b)
gsl_sf_lnbeta = _sf.gsl_sf_lnbeta

def gsl_sf_lnbeta_sgn_e(x, y, result, sgn):
    return _sf.gsl_sf_lnbeta_sgn_e(x, y, result, sgn)
gsl_sf_lnbeta_sgn_e = _sf.gsl_sf_lnbeta_sgn_e

def gsl_sf_beta_e(a, b, result):
    return _sf.gsl_sf_beta_e(a, b, result)
gsl_sf_beta_e = _sf.gsl_sf_beta_e

def gsl_sf_beta(a, b):
    return _sf.gsl_sf_beta(a, b)
gsl_sf_beta = _sf.gsl_sf_beta

def gsl_sf_beta_inc_e(a, b, x, result):
    return _sf.gsl_sf_beta_inc_e(a, b, x, result)
gsl_sf_beta_inc_e = _sf.gsl_sf_beta_inc_e

def gsl_sf_beta_inc(a, b, x):
    return _sf.gsl_sf_beta_inc(a, b, x)
gsl_sf_beta_inc = _sf.gsl_sf_beta_inc
GSL_SF_GAMMA_XMAX = _sf.GSL_SF_GAMMA_XMAX
GSL_SF_FACT_NMAX = _sf.GSL_SF_FACT_NMAX
GSL_SF_DOUBLEFACT_NMAX = _sf.GSL_SF_DOUBLEFACT_NMAX

def gsl_sf_gegenpoly_1_e(arg1, x, result):
    return _sf.gsl_sf_gegenpoly_1_e(arg1, x, result)
gsl_sf_gegenpoly_1_e = _sf.gsl_sf_gegenpoly_1_e

def gsl_sf_gegenpoly_2_e(arg1, x, result):
    return _sf.gsl_sf_gegenpoly_2_e(arg1, x, result)
gsl_sf_gegenpoly_2_e = _sf.gsl_sf_gegenpoly_2_e

def gsl_sf_gegenpoly_3_e(arg1, x, result):
    return _sf.gsl_sf_gegenpoly_3_e(arg1, x, result)
gsl_sf_gegenpoly_3_e = _sf.gsl_sf_gegenpoly_3_e

def gsl_sf_gegenpoly_1(arg1, x):
    return _sf.gsl_sf_gegenpoly_1(arg1, x)
gsl_sf_gegenpoly_1 = _sf.gsl_sf_gegenpoly_1

def gsl_sf_gegenpoly_2(arg1, x):
    return _sf.gsl_sf_gegenpoly_2(arg1, x)
gsl_sf_gegenpoly_2 = _sf.gsl_sf_gegenpoly_2

def gsl_sf_gegenpoly_3(arg1, x):
    return _sf.gsl_sf_gegenpoly_3(arg1, x)
gsl_sf_gegenpoly_3 = _sf.gsl_sf_gegenpoly_3

def gsl_sf_gegenpoly_n_e(n, arg2, x, result):
    return _sf.gsl_sf_gegenpoly_n_e(n, arg2, x, result)
gsl_sf_gegenpoly_n_e = _sf.gsl_sf_gegenpoly_n_e

def gsl_sf_gegenpoly_n(n, arg2, x):
    return _sf.gsl_sf_gegenpoly_n(n, arg2, x)
gsl_sf_gegenpoly_n = _sf.gsl_sf_gegenpoly_n

def gsl_sf_hyperg_0F1_e(c, x, result):
    return _sf.gsl_sf_hyperg_0F1_e(c, x, result)
gsl_sf_hyperg_0F1_e = _sf.gsl_sf_hyperg_0F1_e

def gsl_sf_hyperg_0F1(c, x):
    return _sf.gsl_sf_hyperg_0F1(c, x)
gsl_sf_hyperg_0F1 = _sf.gsl_sf_hyperg_0F1

def gsl_sf_hyperg_1F1_int_e(m, n, x, result):
    return _sf.gsl_sf_hyperg_1F1_int_e(m, n, x, result)
gsl_sf_hyperg_1F1_int_e = _sf.gsl_sf_hyperg_1F1_int_e

def gsl_sf_hyperg_1F1_int(m, n, x):
    return _sf.gsl_sf_hyperg_1F1_int(m, n, x)
gsl_sf_hyperg_1F1_int = _sf.gsl_sf_hyperg_1F1_int

def gsl_sf_hyperg_1F1_e(a, b, x, result):
    return _sf.gsl_sf_hyperg_1F1_e(a, b, x, result)
gsl_sf_hyperg_1F1_e = _sf.gsl_sf_hyperg_1F1_e

def gsl_sf_hyperg_1F1(a, b, x):
    return _sf.gsl_sf_hyperg_1F1(a, b, x)
gsl_sf_hyperg_1F1 = _sf.gsl_sf_hyperg_1F1

def gsl_sf_hyperg_U_int_e(m, n, x, result):
    return _sf.gsl_sf_hyperg_U_int_e(m, n, x, result)
gsl_sf_hyperg_U_int_e = _sf.gsl_sf_hyperg_U_int_e

def gsl_sf_hyperg_U_int(m, n, x):
    return _sf.gsl_sf_hyperg_U_int(m, n, x)
gsl_sf_hyperg_U_int = _sf.gsl_sf_hyperg_U_int

def gsl_sf_hyperg_U_int_e10_e(m, n, x, result):
    return _sf.gsl_sf_hyperg_U_int_e10_e(m, n, x, result)
gsl_sf_hyperg_U_int_e10_e = _sf.gsl_sf_hyperg_U_int_e10_e

def gsl_sf_hyperg_U_e(a, b, x, result):
    return _sf.gsl_sf_hyperg_U_e(a, b, x, result)
gsl_sf_hyperg_U_e = _sf.gsl_sf_hyperg_U_e

def gsl_sf_hyperg_U(a, b, x):
    return _sf.gsl_sf_hyperg_U(a, b, x)
gsl_sf_hyperg_U = _sf.gsl_sf_hyperg_U

def gsl_sf_hyperg_U_e10_e(a, b, x, result):
    return _sf.gsl_sf_hyperg_U_e10_e(a, b, x, result)
gsl_sf_hyperg_U_e10_e = _sf.gsl_sf_hyperg_U_e10_e

def gsl_sf_hyperg_2F1_e(a, b, c, x, result):
    return _sf.gsl_sf_hyperg_2F1_e(a, b, c, x, result)
gsl_sf_hyperg_2F1_e = _sf.gsl_sf_hyperg_2F1_e

def gsl_sf_hyperg_2F1(a, b, c, x):
    return _sf.gsl_sf_hyperg_2F1(a, b, c, x)
gsl_sf_hyperg_2F1 = _sf.gsl_sf_hyperg_2F1

def gsl_sf_hyperg_2F1_conj_e(aR, aI, c, x, result):
    return _sf.gsl_sf_hyperg_2F1_conj_e(aR, aI, c, x, result)
gsl_sf_hyperg_2F1_conj_e = _sf.gsl_sf_hyperg_2F1_conj_e

def gsl_sf_hyperg_2F1_conj(aR, aI, c, x):
    return _sf.gsl_sf_hyperg_2F1_conj(aR, aI, c, x)
gsl_sf_hyperg_2F1_conj = _sf.gsl_sf_hyperg_2F1_conj

def gsl_sf_hyperg_2F1_renorm_e(a, b, c, x, result):
    return _sf.gsl_sf_hyperg_2F1_renorm_e(a, b, c, x, result)
gsl_sf_hyperg_2F1_renorm_e = _sf.gsl_sf_hyperg_2F1_renorm_e

def gsl_sf_hyperg_2F1_renorm(a, b, c, x):
    return _sf.gsl_sf_hyperg_2F1_renorm(a, b, c, x)
gsl_sf_hyperg_2F1_renorm = _sf.gsl_sf_hyperg_2F1_renorm

def gsl_sf_hyperg_2F1_conj_renorm_e(aR, aI, c, x, result):
    return _sf.gsl_sf_hyperg_2F1_conj_renorm_e(aR, aI, c, x, result)
gsl_sf_hyperg_2F1_conj_renorm_e = _sf.gsl_sf_hyperg_2F1_conj_renorm_e

def gsl_sf_hyperg_2F1_conj_renorm(aR, aI, c, x):
    return _sf.gsl_sf_hyperg_2F1_conj_renorm(aR, aI, c, x)
gsl_sf_hyperg_2F1_conj_renorm = _sf.gsl_sf_hyperg_2F1_conj_renorm

def gsl_sf_hyperg_2F0_e(a, b, x, result):
    return _sf.gsl_sf_hyperg_2F0_e(a, b, x, result)
gsl_sf_hyperg_2F0_e = _sf.gsl_sf_hyperg_2F0_e

def gsl_sf_hyperg_2F0(a, b, x):
    return _sf.gsl_sf_hyperg_2F0(a, b, x)
gsl_sf_hyperg_2F0 = _sf.gsl_sf_hyperg_2F0

def gsl_sf_laguerre_1_e(a, x, result):
    return _sf.gsl_sf_laguerre_1_e(a, x, result)
gsl_sf_laguerre_1_e = _sf.gsl_sf_laguerre_1_e

def gsl_sf_laguerre_2_e(a, x, result):
    return _sf.gsl_sf_laguerre_2_e(a, x, result)
gsl_sf_laguerre_2_e = _sf.gsl_sf_laguerre_2_e

def gsl_sf_laguerre_3_e(a, x, result):
    return _sf.gsl_sf_laguerre_3_e(a, x, result)
gsl_sf_laguerre_3_e = _sf.gsl_sf_laguerre_3_e

def gsl_sf_laguerre_1(a, x):
    return _sf.gsl_sf_laguerre_1(a, x)
gsl_sf_laguerre_1 = _sf.gsl_sf_laguerre_1

def gsl_sf_laguerre_2(a, x):
    return _sf.gsl_sf_laguerre_2(a, x)
gsl_sf_laguerre_2 = _sf.gsl_sf_laguerre_2

def gsl_sf_laguerre_3(a, x):
    return _sf.gsl_sf_laguerre_3(a, x)
gsl_sf_laguerre_3 = _sf.gsl_sf_laguerre_3

def gsl_sf_laguerre_n_e(n, a, x, result):
    return _sf.gsl_sf_laguerre_n_e(n, a, x, result)
gsl_sf_laguerre_n_e = _sf.gsl_sf_laguerre_n_e

def gsl_sf_laguerre_n(n, a, x):
    return _sf.gsl_sf_laguerre_n(n, a, x)
gsl_sf_laguerre_n = _sf.gsl_sf_laguerre_n

def gsl_sf_lambert_W0_e(x, result):
    return _sf.gsl_sf_lambert_W0_e(x, result)
gsl_sf_lambert_W0_e = _sf.gsl_sf_lambert_W0_e

def gsl_sf_lambert_W0(x):
    return _sf.gsl_sf_lambert_W0(x)
gsl_sf_lambert_W0 = _sf.gsl_sf_lambert_W0

def gsl_sf_lambert_Wm1_e(x, result):
    return _sf.gsl_sf_lambert_Wm1_e(x, result)
gsl_sf_lambert_Wm1_e = _sf.gsl_sf_lambert_Wm1_e

def gsl_sf_lambert_Wm1(x):
    return _sf.gsl_sf_lambert_Wm1(x)
gsl_sf_lambert_Wm1 = _sf.gsl_sf_lambert_Wm1

def gsl_sf_legendre_Pl_e(l, x, result):
    return _sf.gsl_sf_legendre_Pl_e(l, x, result)
gsl_sf_legendre_Pl_e = _sf.gsl_sf_legendre_Pl_e

def gsl_sf_legendre_Pl(l, x):
    return _sf.gsl_sf_legendre_Pl(l, x)
gsl_sf_legendre_Pl = _sf.gsl_sf_legendre_Pl

def gsl_sf_legendre_P1_e(x, result):
    return _sf.gsl_sf_legendre_P1_e(x, result)
gsl_sf_legendre_P1_e = _sf.gsl_sf_legendre_P1_e

def gsl_sf_legendre_P2_e(x, result):
    return _sf.gsl_sf_legendre_P2_e(x, result)
gsl_sf_legendre_P2_e = _sf.gsl_sf_legendre_P2_e

def gsl_sf_legendre_P3_e(x, result):
    return _sf.gsl_sf_legendre_P3_e(x, result)
gsl_sf_legendre_P3_e = _sf.gsl_sf_legendre_P3_e

def gsl_sf_legendre_P1(x):
    return _sf.gsl_sf_legendre_P1(x)
gsl_sf_legendre_P1 = _sf.gsl_sf_legendre_P1

def gsl_sf_legendre_P2(x):
    return _sf.gsl_sf_legendre_P2(x)
gsl_sf_legendre_P2 = _sf.gsl_sf_legendre_P2

def gsl_sf_legendre_P3(x):
    return _sf.gsl_sf_legendre_P3(x)
gsl_sf_legendre_P3 = _sf.gsl_sf_legendre_P3

def gsl_sf_legendre_Q0_e(x, result):
    return _sf.gsl_sf_legendre_Q0_e(x, result)
gsl_sf_legendre_Q0_e = _sf.gsl_sf_legendre_Q0_e

def gsl_sf_legendre_Q0(x):
    return _sf.gsl_sf_legendre_Q0(x)
gsl_sf_legendre_Q0 = _sf.gsl_sf_legendre_Q0

def gsl_sf_legendre_Q1_e(x, result):
    return _sf.gsl_sf_legendre_Q1_e(x, result)
gsl_sf_legendre_Q1_e = _sf.gsl_sf_legendre_Q1_e

def gsl_sf_legendre_Q1(x):
    return _sf.gsl_sf_legendre_Q1(x)
gsl_sf_legendre_Q1 = _sf.gsl_sf_legendre_Q1

def gsl_sf_legendre_Ql_e(l, x, result):
    return _sf.gsl_sf_legendre_Ql_e(l, x, result)
gsl_sf_legendre_Ql_e = _sf.gsl_sf_legendre_Ql_e

def gsl_sf_legendre_Ql(l, x):
    return _sf.gsl_sf_legendre_Ql(l, x)
gsl_sf_legendre_Ql = _sf.gsl_sf_legendre_Ql

def gsl_sf_legendre_Plm_e(l, m, x, result):
    return _sf.gsl_sf_legendre_Plm_e(l, m, x, result)
gsl_sf_legendre_Plm_e = _sf.gsl_sf_legendre_Plm_e

def gsl_sf_legendre_Plm(l, m, x):
    return _sf.gsl_sf_legendre_Plm(l, m, x)
gsl_sf_legendre_Plm = _sf.gsl_sf_legendre_Plm

def gsl_sf_legendre_sphPlm_e(l, m, x, result):
    return _sf.gsl_sf_legendre_sphPlm_e(l, m, x, result)
gsl_sf_legendre_sphPlm_e = _sf.gsl_sf_legendre_sphPlm_e

def gsl_sf_legendre_sphPlm(l, m, x):
    return _sf.gsl_sf_legendre_sphPlm(l, m, x)
gsl_sf_legendre_sphPlm = _sf.gsl_sf_legendre_sphPlm

def gsl_sf_conicalP_half_e(arg1, x, result):
    return _sf.gsl_sf_conicalP_half_e(arg1, x, result)
gsl_sf_conicalP_half_e = _sf.gsl_sf_conicalP_half_e

def gsl_sf_conicalP_half(arg1, x):
    return _sf.gsl_sf_conicalP_half(arg1, x)
gsl_sf_conicalP_half = _sf.gsl_sf_conicalP_half

def gsl_sf_conicalP_mhalf_e(arg1, x, result):
    return _sf.gsl_sf_conicalP_mhalf_e(arg1, x, result)
gsl_sf_conicalP_mhalf_e = _sf.gsl_sf_conicalP_mhalf_e

def gsl_sf_conicalP_mhalf(arg1, x):
    return _sf.gsl_sf_conicalP_mhalf(arg1, x)
gsl_sf_conicalP_mhalf = _sf.gsl_sf_conicalP_mhalf

def gsl_sf_conicalP_0_e(arg1, x, result):
    return _sf.gsl_sf_conicalP_0_e(arg1, x, result)
gsl_sf_conicalP_0_e = _sf.gsl_sf_conicalP_0_e

def gsl_sf_conicalP_0(arg1, x):
    return _sf.gsl_sf_conicalP_0(arg1, x)
gsl_sf_conicalP_0 = _sf.gsl_sf_conicalP_0

def gsl_sf_conicalP_1_e(arg1, x, result):
    return _sf.gsl_sf_conicalP_1_e(arg1, x, result)
gsl_sf_conicalP_1_e = _sf.gsl_sf_conicalP_1_e

def gsl_sf_conicalP_1(arg1, x):
    return _sf.gsl_sf_conicalP_1(arg1, x)
gsl_sf_conicalP_1 = _sf.gsl_sf_conicalP_1

def gsl_sf_conicalP_sph_reg_e(l, arg2, x, result):
    return _sf.gsl_sf_conicalP_sph_reg_e(l, arg2, x, result)
gsl_sf_conicalP_sph_reg_e = _sf.gsl_sf_conicalP_sph_reg_e

def gsl_sf_conicalP_sph_reg(l, arg2, x):
    return _sf.gsl_sf_conicalP_sph_reg(l, arg2, x)
gsl_sf_conicalP_sph_reg = _sf.gsl_sf_conicalP_sph_reg

def gsl_sf_conicalP_cyl_reg_e(m, arg2, x, result):
    return _sf.gsl_sf_conicalP_cyl_reg_e(m, arg2, x, result)
gsl_sf_conicalP_cyl_reg_e = _sf.gsl_sf_conicalP_cyl_reg_e

def gsl_sf_conicalP_cyl_reg(m, arg2, x):
    return _sf.gsl_sf_conicalP_cyl_reg(m, arg2, x)
gsl_sf_conicalP_cyl_reg = _sf.gsl_sf_conicalP_cyl_reg

def gsl_sf_legendre_H3d_0_e(arg1, eta, result):
    return _sf.gsl_sf_legendre_H3d_0_e(arg1, eta, result)
gsl_sf_legendre_H3d_0_e = _sf.gsl_sf_legendre_H3d_0_e

def gsl_sf_legendre_H3d_0(arg1, eta):
    return _sf.gsl_sf_legendre_H3d_0(arg1, eta)
gsl_sf_legendre_H3d_0 = _sf.gsl_sf_legendre_H3d_0

def gsl_sf_legendre_H3d_1_e(arg1, eta, result):
    return _sf.gsl_sf_legendre_H3d_1_e(arg1, eta, result)
gsl_sf_legendre_H3d_1_e = _sf.gsl_sf_legendre_H3d_1_e

def gsl_sf_legendre_H3d_1(arg1, eta):
    return _sf.gsl_sf_legendre_H3d_1(arg1, eta)
gsl_sf_legendre_H3d_1 = _sf.gsl_sf_legendre_H3d_1

def gsl_sf_legendre_H3d_e(l, arg2, eta, result):
    return _sf.gsl_sf_legendre_H3d_e(l, arg2, eta, result)
gsl_sf_legendre_H3d_e = _sf.gsl_sf_legendre_H3d_e

def gsl_sf_legendre_H3d(l, arg2, eta):
    return _sf.gsl_sf_legendre_H3d(l, arg2, eta)
gsl_sf_legendre_H3d = _sf.gsl_sf_legendre_H3d
GSL_SF_LEGENDRE_SCHMIDT = _sf.GSL_SF_LEGENDRE_SCHMIDT
GSL_SF_LEGENDRE_SPHARM = _sf.GSL_SF_LEGENDRE_SPHARM
GSL_SF_LEGENDRE_FULL = _sf.GSL_SF_LEGENDRE_FULL
GSL_SF_LEGENDRE_NONE = _sf.GSL_SF_LEGENDRE_NONE

def gsl_sf_log_e(x, result):
    return _sf.gsl_sf_log_e(x, result)
gsl_sf_log_e = _sf.gsl_sf_log_e

def gsl_sf_log(x):
    return _sf.gsl_sf_log(x)
gsl_sf_log = _sf.gsl_sf_log

def gsl_sf_log_abs_e(x, result):
    return _sf.gsl_sf_log_abs_e(x, result)
gsl_sf_log_abs_e = _sf.gsl_sf_log_abs_e

def gsl_sf_log_abs(x):
    return _sf.gsl_sf_log_abs(x)
gsl_sf_log_abs = _sf.gsl_sf_log_abs

def gsl_sf_complex_log_e(zr, zi, lnr, theta):
    return _sf.gsl_sf_complex_log_e(zr, zi, lnr, theta)
gsl_sf_complex_log_e = _sf.gsl_sf_complex_log_e

def gsl_sf_log_1plusx_e(x, result):
    return _sf.gsl_sf_log_1plusx_e(x, result)
gsl_sf_log_1plusx_e = _sf.gsl_sf_log_1plusx_e

def gsl_sf_log_1plusx(x):
    return _sf.gsl_sf_log_1plusx(x)
gsl_sf_log_1plusx = _sf.gsl_sf_log_1plusx

def gsl_sf_log_1plusx_mx_e(x, result):
    return _sf.gsl_sf_log_1plusx_mx_e(x, result)
gsl_sf_log_1plusx_mx_e = _sf.gsl_sf_log_1plusx_mx_e

def gsl_sf_log_1plusx_mx(x):
    return _sf.gsl_sf_log_1plusx_mx(x)
gsl_sf_log_1plusx_mx = _sf.gsl_sf_log_1plusx_mx
GSL_SF_MATHIEU_COEFF = _sf.GSL_SF_MATHIEU_COEFF

def gsl_sf_mathieu_a_e(order, qq, result):
    return _sf.gsl_sf_mathieu_a_e(order, qq, result)
gsl_sf_mathieu_a_e = _sf.gsl_sf_mathieu_a_e

def gsl_sf_mathieu_a(order, qq):
    return _sf.gsl_sf_mathieu_a(order, qq)
gsl_sf_mathieu_a = _sf.gsl_sf_mathieu_a

def gsl_sf_mathieu_b_e(order, qq, result):
    return _sf.gsl_sf_mathieu_b_e(order, qq, result)
gsl_sf_mathieu_b_e = _sf.gsl_sf_mathieu_b_e

def gsl_sf_mathieu_b(order, qq):
    return _sf.gsl_sf_mathieu_b(order, qq)
gsl_sf_mathieu_b = _sf.gsl_sf_mathieu_b

def gsl_sf_mathieu_ce_e(order, qq, zz, result):
    return _sf.gsl_sf_mathieu_ce_e(order, qq, zz, result)
gsl_sf_mathieu_ce_e = _sf.gsl_sf_mathieu_ce_e

def gsl_sf_mathieu_ce(order, qq, zz):
    return _sf.gsl_sf_mathieu_ce(order, qq, zz)
gsl_sf_mathieu_ce = _sf.gsl_sf_mathieu_ce

def gsl_sf_mathieu_se_e(order, qq, zz, result):
    return _sf.gsl_sf_mathieu_se_e(order, qq, zz, result)
gsl_sf_mathieu_se_e = _sf.gsl_sf_mathieu_se_e

def gsl_sf_mathieu_se(order, qq, zz):
    return _sf.gsl_sf_mathieu_se(order, qq, zz)
gsl_sf_mathieu_se = _sf.gsl_sf_mathieu_se

def gsl_sf_mathieu_Mc_e(kind, order, qq, zz, result):
    return _sf.gsl_sf_mathieu_Mc_e(kind, order, qq, zz, result)
gsl_sf_mathieu_Mc_e = _sf.gsl_sf_mathieu_Mc_e

def gsl_sf_mathieu_Mc(kind, order, qq, zz):
    return _sf.gsl_sf_mathieu_Mc(kind, order, qq, zz)
gsl_sf_mathieu_Mc = _sf.gsl_sf_mathieu_Mc

def gsl_sf_mathieu_Ms_e(kind, order, qq, zz, result):
    return _sf.gsl_sf_mathieu_Ms_e(kind, order, qq, zz, result)
gsl_sf_mathieu_Ms_e = _sf.gsl_sf_mathieu_Ms_e

def gsl_sf_mathieu_Ms(kind, order, qq, zz):
    return _sf.gsl_sf_mathieu_Ms(kind, order, qq, zz)
gsl_sf_mathieu_Ms = _sf.gsl_sf_mathieu_Ms

def gsl_sf_pow_int_e(x, n, result):
    return _sf.gsl_sf_pow_int_e(x, n, result)
gsl_sf_pow_int_e = _sf.gsl_sf_pow_int_e

def gsl_sf_pow_int(x, n):
    return _sf.gsl_sf_pow_int(x, n)
gsl_sf_pow_int = _sf.gsl_sf_pow_int

def gsl_sf_psi_int_e(n, result):
    return _sf.gsl_sf_psi_int_e(n, result)
gsl_sf_psi_int_e = _sf.gsl_sf_psi_int_e

def gsl_sf_psi_int(n):
    return _sf.gsl_sf_psi_int(n)
gsl_sf_psi_int = _sf.gsl_sf_psi_int

def gsl_sf_psi_e(x, result):
    return _sf.gsl_sf_psi_e(x, result)
gsl_sf_psi_e = _sf.gsl_sf_psi_e

def gsl_sf_psi(x):
    return _sf.gsl_sf_psi(x)
gsl_sf_psi = _sf.gsl_sf_psi

def gsl_sf_psi_1piy_e(y, result):
    return _sf.gsl_sf_psi_1piy_e(y, result)
gsl_sf_psi_1piy_e = _sf.gsl_sf_psi_1piy_e

def gsl_sf_psi_1piy(y):
    return _sf.gsl_sf_psi_1piy(y)
gsl_sf_psi_1piy = _sf.gsl_sf_psi_1piy

def gsl_sf_complex_psi_e(x, y, result_re, result_im):
    return _sf.gsl_sf_complex_psi_e(x, y, result_re, result_im)
gsl_sf_complex_psi_e = _sf.gsl_sf_complex_psi_e

def gsl_sf_psi_1_int_e(n, result):
    return _sf.gsl_sf_psi_1_int_e(n, result)
gsl_sf_psi_1_int_e = _sf.gsl_sf_psi_1_int_e

def gsl_sf_psi_1_int(n):
    return _sf.gsl_sf_psi_1_int(n)
gsl_sf_psi_1_int = _sf.gsl_sf_psi_1_int

def gsl_sf_psi_1_e(x, result):
    return _sf.gsl_sf_psi_1_e(x, result)
gsl_sf_psi_1_e = _sf.gsl_sf_psi_1_e

def gsl_sf_psi_1(x):
    return _sf.gsl_sf_psi_1(x)
gsl_sf_psi_1 = _sf.gsl_sf_psi_1

def gsl_sf_psi_n_e(n, x, result):
    return _sf.gsl_sf_psi_n_e(n, x, result)
gsl_sf_psi_n_e = _sf.gsl_sf_psi_n_e

def gsl_sf_psi_n(n, x):
    return _sf.gsl_sf_psi_n(n, x)
gsl_sf_psi_n = _sf.gsl_sf_psi_n

def gsl_sf_synchrotron_1_e(x, result):
    return _sf.gsl_sf_synchrotron_1_e(x, result)
gsl_sf_synchrotron_1_e = _sf.gsl_sf_synchrotron_1_e

def gsl_sf_synchrotron_1(x):
    return _sf.gsl_sf_synchrotron_1(x)
gsl_sf_synchrotron_1 = _sf.gsl_sf_synchrotron_1

def gsl_sf_synchrotron_2_e(x, result):
    return _sf.gsl_sf_synchrotron_2_e(x, result)
gsl_sf_synchrotron_2_e = _sf.gsl_sf_synchrotron_2_e

def gsl_sf_synchrotron_2(x):
    return _sf.gsl_sf_synchrotron_2(x)
gsl_sf_synchrotron_2 = _sf.gsl_sf_synchrotron_2

def gsl_sf_transport_2_e(x, result):
    return _sf.gsl_sf_transport_2_e(x, result)
gsl_sf_transport_2_e = _sf.gsl_sf_transport_2_e

def gsl_sf_transport_2(x):
    return _sf.gsl_sf_transport_2(x)
gsl_sf_transport_2 = _sf.gsl_sf_transport_2

def gsl_sf_transport_3_e(x, result):
    return _sf.gsl_sf_transport_3_e(x, result)
gsl_sf_transport_3_e = _sf.gsl_sf_transport_3_e

def gsl_sf_transport_3(x):
    return _sf.gsl_sf_transport_3(x)
gsl_sf_transport_3 = _sf.gsl_sf_transport_3

def gsl_sf_transport_4_e(x, result):
    return _sf.gsl_sf_transport_4_e(x, result)
gsl_sf_transport_4_e = _sf.gsl_sf_transport_4_e

def gsl_sf_transport_4(x):
    return _sf.gsl_sf_transport_4(x)
gsl_sf_transport_4 = _sf.gsl_sf_transport_4

def gsl_sf_transport_5_e(x, result):
    return _sf.gsl_sf_transport_5_e(x, result)
gsl_sf_transport_5_e = _sf.gsl_sf_transport_5_e

def gsl_sf_transport_5(x):
    return _sf.gsl_sf_transport_5(x)
gsl_sf_transport_5 = _sf.gsl_sf_transport_5

def gsl_sf_sin_e(x, result):
    return _sf.gsl_sf_sin_e(x, result)
gsl_sf_sin_e = _sf.gsl_sf_sin_e

def gsl_sf_sin(x):
    return _sf.gsl_sf_sin(x)
gsl_sf_sin = _sf.gsl_sf_sin

def gsl_sf_cos_e(x, result):
    return _sf.gsl_sf_cos_e(x, result)
gsl_sf_cos_e = _sf.gsl_sf_cos_e

def gsl_sf_cos(x):
    return _sf.gsl_sf_cos(x)
gsl_sf_cos = _sf.gsl_sf_cos

def gsl_sf_hypot_e(x, y, result):
    return _sf.gsl_sf_hypot_e(x, y, result)
gsl_sf_hypot_e = _sf.gsl_sf_hypot_e

def gsl_sf_hypot(x, y):
    return _sf.gsl_sf_hypot(x, y)
gsl_sf_hypot = _sf.gsl_sf_hypot

def gsl_sf_complex_sin_e(zr, zi, szr, szi):
    return _sf.gsl_sf_complex_sin_e(zr, zi, szr, szi)
gsl_sf_complex_sin_e = _sf.gsl_sf_complex_sin_e

def gsl_sf_complex_cos_e(zr, zi, czr, czi):
    return _sf.gsl_sf_complex_cos_e(zr, zi, czr, czi)
gsl_sf_complex_cos_e = _sf.gsl_sf_complex_cos_e

def gsl_sf_complex_logsin_e(zr, zi, lszr, lszi):
    return _sf.gsl_sf_complex_logsin_e(zr, zi, lszr, lszi)
gsl_sf_complex_logsin_e = _sf.gsl_sf_complex_logsin_e

def gsl_sf_sinc_e(x, result):
    return _sf.gsl_sf_sinc_e(x, result)
gsl_sf_sinc_e = _sf.gsl_sf_sinc_e

def gsl_sf_sinc(x):
    return _sf.gsl_sf_sinc(x)
gsl_sf_sinc = _sf.gsl_sf_sinc

def gsl_sf_lnsinh_e(x, result):
    return _sf.gsl_sf_lnsinh_e(x, result)
gsl_sf_lnsinh_e = _sf.gsl_sf_lnsinh_e

def gsl_sf_lnsinh(x):
    return _sf.gsl_sf_lnsinh(x)
gsl_sf_lnsinh = _sf.gsl_sf_lnsinh

def gsl_sf_lncosh_e(x, result):
    return _sf.gsl_sf_lncosh_e(x, result)
gsl_sf_lncosh_e = _sf.gsl_sf_lncosh_e

def gsl_sf_lncosh(x):
    return _sf.gsl_sf_lncosh(x)
gsl_sf_lncosh = _sf.gsl_sf_lncosh

def gsl_sf_sin_err_e(x, dx, result):
    return _sf.gsl_sf_sin_err_e(x, dx, result)
gsl_sf_sin_err_e = _sf.gsl_sf_sin_err_e

def gsl_sf_cos_err_e(x, dx, result):
    return _sf.gsl_sf_cos_err_e(x, dx, result)
gsl_sf_cos_err_e = _sf.gsl_sf_cos_err_e

def gsl_sf_angle_restrict_symm_e(theta):
    return _sf.gsl_sf_angle_restrict_symm_e(theta)
gsl_sf_angle_restrict_symm_e = _sf.gsl_sf_angle_restrict_symm_e

def gsl_sf_angle_restrict_symm(theta):
    return _sf.gsl_sf_angle_restrict_symm(theta)
gsl_sf_angle_restrict_symm = _sf.gsl_sf_angle_restrict_symm

def gsl_sf_angle_restrict_pos(theta):
    return _sf.gsl_sf_angle_restrict_pos(theta)
gsl_sf_angle_restrict_pos = _sf.gsl_sf_angle_restrict_pos

def gsl_sf_angle_restrict_symm_err_e(theta, result):
    return _sf.gsl_sf_angle_restrict_symm_err_e(theta, result)
gsl_sf_angle_restrict_symm_err_e = _sf.gsl_sf_angle_restrict_symm_err_e

def gsl_sf_angle_restrict_pos_err_e(theta, result):
    return _sf.gsl_sf_angle_restrict_pos_err_e(theta, result)
gsl_sf_angle_restrict_pos_err_e = _sf.gsl_sf_angle_restrict_pos_err_e

def gsl_sf_zeta_int_e(n, result):
    return _sf.gsl_sf_zeta_int_e(n, result)
gsl_sf_zeta_int_e = _sf.gsl_sf_zeta_int_e

def gsl_sf_zeta_int(n):
    return _sf.gsl_sf_zeta_int(n)
gsl_sf_zeta_int = _sf.gsl_sf_zeta_int

def gsl_sf_zeta_e(s, result):
    return _sf.gsl_sf_zeta_e(s, result)
gsl_sf_zeta_e = _sf.gsl_sf_zeta_e

def gsl_sf_zeta(s):
    return _sf.gsl_sf_zeta(s)
gsl_sf_zeta = _sf.gsl_sf_zeta

def gsl_sf_zetam1_e(s, result):
    return _sf.gsl_sf_zetam1_e(s, result)
gsl_sf_zetam1_e = _sf.gsl_sf_zetam1_e

def gsl_sf_zetam1(s):
    return _sf.gsl_sf_zetam1(s)
gsl_sf_zetam1 = _sf.gsl_sf_zetam1

def gsl_sf_zetam1_int_e(s, result):
    return _sf.gsl_sf_zetam1_int_e(s, result)
gsl_sf_zetam1_int_e = _sf.gsl_sf_zetam1_int_e

def gsl_sf_zetam1_int(s):
    return _sf.gsl_sf_zetam1_int(s)
gsl_sf_zetam1_int = _sf.gsl_sf_zetam1_int

def gsl_sf_hzeta_e(s, q, result):
    return _sf.gsl_sf_hzeta_e(s, q, result)
gsl_sf_hzeta_e = _sf.gsl_sf_hzeta_e

def gsl_sf_hzeta(s, q):
    return _sf.gsl_sf_hzeta(s, q)
gsl_sf_hzeta = _sf.gsl_sf_hzeta

def gsl_sf_eta_int_e(n, result):
    return _sf.gsl_sf_eta_int_e(n, result)
gsl_sf_eta_int_e = _sf.gsl_sf_eta_int_e

def gsl_sf_eta_int(n):
    return _sf.gsl_sf_eta_int(n)
gsl_sf_eta_int = _sf.gsl_sf_eta_int

def gsl_sf_eta_e(s, result):
    return _sf.gsl_sf_eta_e(s, result)
gsl_sf_eta_e = _sf.gsl_sf_eta_e

def gsl_sf_eta(s):
    return _sf.gsl_sf_eta(s)
gsl_sf_eta = _sf.gsl_sf_eta

def gsl_complex_polar(r, theta):
    return _sf.gsl_complex_polar(r, theta)
gsl_complex_polar = _sf.gsl_complex_polar

def gsl_complex_rect(x, y):
    return _sf.gsl_complex_rect(x, y)
gsl_complex_rect = _sf.gsl_complex_rect

def gsl_complex_arg(z):
    return _sf.gsl_complex_arg(z)
gsl_complex_arg = _sf.gsl_complex_arg

def gsl_complex_abs(z):
    return _sf.gsl_complex_abs(z)
gsl_complex_abs = _sf.gsl_complex_abs

def gsl_complex_abs2(z):
    return _sf.gsl_complex_abs2(z)
gsl_complex_abs2 = _sf.gsl_complex_abs2

def gsl_complex_logabs(z):
    return _sf.gsl_complex_logabs(z)
gsl_complex_logabs = _sf.gsl_complex_logabs

def gsl_complex_add(a, b):
    return _sf.gsl_complex_add(a, b)
gsl_complex_add = _sf.gsl_complex_add

def gsl_complex_sub(a, b):
    return _sf.gsl_complex_sub(a, b)
gsl_complex_sub = _sf.gsl_complex_sub

def gsl_complex_mul(a, b):
    return _sf.gsl_complex_mul(a, b)
gsl_complex_mul = _sf.gsl_complex_mul

def gsl_complex_div(a, b):
    return _sf.gsl_complex_div(a, b)
gsl_complex_div = _sf.gsl_complex_div

def gsl_complex_add_real(a, x):
    return _sf.gsl_complex_add_real(a, x)
gsl_complex_add_real = _sf.gsl_complex_add_real

def gsl_complex_sub_real(a, x):
    return _sf.gsl_complex_sub_real(a, x)
gsl_complex_sub_real = _sf.gsl_complex_sub_real

def gsl_complex_mul_real(a, x):
    return _sf.gsl_complex_mul_real(a, x)
gsl_complex_mul_real = _sf.gsl_complex_mul_real

def gsl_complex_div_real(a, x):
    return _sf.gsl_complex_div_real(a, x)
gsl_complex_div_real = _sf.gsl_complex_div_real

def gsl_complex_add_imag(a, y):
    return _sf.gsl_complex_add_imag(a, y)
gsl_complex_add_imag = _sf.gsl_complex_add_imag

def gsl_complex_sub_imag(a, y):
    return _sf.gsl_complex_sub_imag(a, y)
gsl_complex_sub_imag = _sf.gsl_complex_sub_imag

def gsl_complex_mul_imag(a, y):
    return _sf.gsl_complex_mul_imag(a, y)
gsl_complex_mul_imag = _sf.gsl_complex_mul_imag

def gsl_complex_div_imag(a, y):
    return _sf.gsl_complex_div_imag(a, y)
gsl_complex_div_imag = _sf.gsl_complex_div_imag

def gsl_complex_conjugate(z):
    return _sf.gsl_complex_conjugate(z)
gsl_complex_conjugate = _sf.gsl_complex_conjugate

def gsl_complex_inverse(a):
    return _sf.gsl_complex_inverse(a)
gsl_complex_inverse = _sf.gsl_complex_inverse

def gsl_complex_negative(a):
    return _sf.gsl_complex_negative(a)
gsl_complex_negative = _sf.gsl_complex_negative

def gsl_complex_sqrt(z):
    return _sf.gsl_complex_sqrt(z)
gsl_complex_sqrt = _sf.gsl_complex_sqrt

def gsl_complex_sqrt_real(x):
    return _sf.gsl_complex_sqrt_real(x)
gsl_complex_sqrt_real = _sf.gsl_complex_sqrt_real

def gsl_complex_pow(a, b):
    return _sf.gsl_complex_pow(a, b)
gsl_complex_pow = _sf.gsl_complex_pow

def gsl_complex_pow_real(a, b):
    return _sf.gsl_complex_pow_real(a, b)
gsl_complex_pow_real = _sf.gsl_complex_pow_real

def gsl_complex_exp(a):
    return _sf.gsl_complex_exp(a)
gsl_complex_exp = _sf.gsl_complex_exp

def gsl_complex_log(a):
    return _sf.gsl_complex_log(a)
gsl_complex_log = _sf.gsl_complex_log

def gsl_complex_log10(a):
    return _sf.gsl_complex_log10(a)
gsl_complex_log10 = _sf.gsl_complex_log10

def gsl_complex_log_b(a, b):
    return _sf.gsl_complex_log_b(a, b)
gsl_complex_log_b = _sf.gsl_complex_log_b

def gsl_complex_sin(a):
    return _sf.gsl_complex_sin(a)
gsl_complex_sin = _sf.gsl_complex_sin

def gsl_complex_cos(a):
    return _sf.gsl_complex_cos(a)
gsl_complex_cos = _sf.gsl_complex_cos

def gsl_complex_sec(a):
    return _sf.gsl_complex_sec(a)
gsl_complex_sec = _sf.gsl_complex_sec

def gsl_complex_csc(a):
    return _sf.gsl_complex_csc(a)
gsl_complex_csc = _sf.gsl_complex_csc

def gsl_complex_tan(a):
    return _sf.gsl_complex_tan(a)
gsl_complex_tan = _sf.gsl_complex_tan

def gsl_complex_cot(a):
    return _sf.gsl_complex_cot(a)
gsl_complex_cot = _sf.gsl_complex_cot

def gsl_complex_arcsin(a):
    return _sf.gsl_complex_arcsin(a)
gsl_complex_arcsin = _sf.gsl_complex_arcsin

def gsl_complex_arcsin_real(a):
    return _sf.gsl_complex_arcsin_real(a)
gsl_complex_arcsin_real = _sf.gsl_complex_arcsin_real

def gsl_complex_arccos(a):
    return _sf.gsl_complex_arccos(a)
gsl_complex_arccos = _sf.gsl_complex_arccos

def gsl_complex_arccos_real(a):
    return _sf.gsl_complex_arccos_real(a)
gsl_complex_arccos_real = _sf.gsl_complex_arccos_real

def gsl_complex_arcsec(a):
    return _sf.gsl_complex_arcsec(a)
gsl_complex_arcsec = _sf.gsl_complex_arcsec

def gsl_complex_arcsec_real(a):
    return _sf.gsl_complex_arcsec_real(a)
gsl_complex_arcsec_real = _sf.gsl_complex_arcsec_real

def gsl_complex_arccsc(a):
    return _sf.gsl_complex_arccsc(a)
gsl_complex_arccsc = _sf.gsl_complex_arccsc

def gsl_complex_arccsc_real(a):
    return _sf.gsl_complex_arccsc_real(a)
gsl_complex_arccsc_real = _sf.gsl_complex_arccsc_real

def gsl_complex_arctan(a):
    return _sf.gsl_complex_arctan(a)
gsl_complex_arctan = _sf.gsl_complex_arctan

def gsl_complex_arccot(a):
    return _sf.gsl_complex_arccot(a)
gsl_complex_arccot = _sf.gsl_complex_arccot

def gsl_complex_sinh(a):
    return _sf.gsl_complex_sinh(a)
gsl_complex_sinh = _sf.gsl_complex_sinh

def gsl_complex_cosh(a):
    return _sf.gsl_complex_cosh(a)
gsl_complex_cosh = _sf.gsl_complex_cosh

def gsl_complex_sech(a):
    return _sf.gsl_complex_sech(a)
gsl_complex_sech = _sf.gsl_complex_sech

def gsl_complex_csch(a):
    return _sf.gsl_complex_csch(a)
gsl_complex_csch = _sf.gsl_complex_csch

def gsl_complex_tanh(a):
    return _sf.gsl_complex_tanh(a)
gsl_complex_tanh = _sf.gsl_complex_tanh

def gsl_complex_coth(a):
    return _sf.gsl_complex_coth(a)
gsl_complex_coth = _sf.gsl_complex_coth

def gsl_complex_arcsinh(a):
    return _sf.gsl_complex_arcsinh(a)
gsl_complex_arcsinh = _sf.gsl_complex_arcsinh

def gsl_complex_arccosh(a):
    return _sf.gsl_complex_arccosh(a)
gsl_complex_arccosh = _sf.gsl_complex_arccosh

def gsl_complex_arccosh_real(a):
    return _sf.gsl_complex_arccosh_real(a)
gsl_complex_arccosh_real = _sf.gsl_complex_arccosh_real

def gsl_complex_arcsech(a):
    return _sf.gsl_complex_arcsech(a)
gsl_complex_arcsech = _sf.gsl_complex_arcsech

def gsl_complex_arccsch(a):
    return _sf.gsl_complex_arccsch(a)
gsl_complex_arccsch = _sf.gsl_complex_arccsch

def gsl_complex_arctanh(a):
    return _sf.gsl_complex_arctanh(a)
gsl_complex_arctanh = _sf.gsl_complex_arctanh

def gsl_complex_arctanh_real(a):
    return _sf.gsl_complex_arctanh_real(a)
gsl_complex_arctanh_real = _sf.gsl_complex_arctanh_real

def gsl_complex_arccoth(a):
    return _sf.gsl_complex_arccoth(a)
gsl_complex_arccoth = _sf.gsl_complex_arccoth

def gsl_log1p(x):
    return _sf.gsl_log1p(x)
gsl_log1p = _sf.gsl_log1p

def gsl_expm1(x):
    return _sf.gsl_expm1(x)
gsl_expm1 = _sf.gsl_expm1

def gsl_hypot(x, y):
    return _sf.gsl_hypot(x, y)
gsl_hypot = _sf.gsl_hypot

def gsl_hypot3(x, y, z):
    return _sf.gsl_hypot3(x, y, z)
gsl_hypot3 = _sf.gsl_hypot3

def gsl_acosh(x):
    return _sf.gsl_acosh(x)
gsl_acosh = _sf.gsl_acosh

def gsl_asinh(x):
    return _sf.gsl_asinh(x)
gsl_asinh = _sf.gsl_asinh

def gsl_atanh(x):
    return _sf.gsl_atanh(x)
gsl_atanh = _sf.gsl_atanh

def gsl_isnan(x):
    return _sf.gsl_isnan(x)
gsl_isnan = _sf.gsl_isnan

def gsl_isinf(x):
    return _sf.gsl_isinf(x)
gsl_isinf = _sf.gsl_isinf

def gsl_finite(x):
    return _sf.gsl_finite(x)
gsl_finite = _sf.gsl_finite

def gsl_nan():
    return _sf.gsl_nan()
gsl_nan = _sf.gsl_nan

def gsl_posinf():
    return _sf.gsl_posinf()
gsl_posinf = _sf.gsl_posinf

def gsl_neginf():
    return _sf.gsl_neginf()
gsl_neginf = _sf.gsl_neginf

def gsl_fdiv(x, y):
    return _sf.gsl_fdiv(x, y)
gsl_fdiv = _sf.gsl_fdiv

def gsl_coerce_double(x):
    return _sf.gsl_coerce_double(x)
gsl_coerce_double = _sf.gsl_coerce_double

def gsl_ldexp(x, e):
    return _sf.gsl_ldexp(x, e)
gsl_ldexp = _sf.gsl_ldexp

def gsl_frexp(x, e):
    return _sf.gsl_frexp(x, e)
gsl_frexp = _sf.gsl_frexp

def gsl_fcmp(x1, x2, epsilon):
    return _sf.gsl_fcmp(x1, x2, epsilon)
gsl_fcmp = _sf.gsl_fcmp
# This file is compatible with both classic and new-style classes.


