{"e",M_E,"e"},
{"log2e",M_LOG2E,"log_2 (e)"},
{"log10e",M_LOG10E,"log_10 (e)"},
{"sqrt2",M_SQRT2,"sqrt(2)"},
{"sqrt1_2",M_SQRT1_2,"sqrt(1/2)"},
{"sqrt3",M_SQRT3,"sqrt(3)"},
{"pi",M_PI,"pi"},
{"pi_2",M_PI_2,"pi/2"},
{"pi_4",M_PI_4,"pi/4"},
{"sqrtpi",M_SQRTPI,"sqrt(pi)"},
{"2_sqrtpi",M_2_SQRTPI,"2/sqrt(pi)"},
{"1_pi",M_1_PI,"1/pi"},
{"2_pi",M_2_PI,"2/pi"},
{"ln10",M_LN10,"ln(10)"},
{"ln2",M_LN2,"ln(2)"},
{"lnpi",M_LNPI,"ln(pi)"},
{"euler",M_EULER,"Euler constant"},
